const fs = require('fs');
const path = require('path');
const targetDir = 'C:/sih/src/data/interviewQuestions/banks';

function save(filename, exportName, questions) {
  const code = `import { RoleQuestion } from '../types';\n\nexport const ${exportName}: RoleQuestion[] = ${JSON.stringify(questions, null, 2)};\n`;
  fs.writeFileSync(path.join(targetDir, filename), code, 'utf-8');
  console.log(`✓ ${filename} written (${questions.length} questions)`);
}

const aiTopics = [
  ["RAG Architecture", "RAG", "Easy", "technical", "Explain the core components of a Retrieval-Augmented Generation (RAG) pipeline.", ["RAG", "LLMs"], ["Document chunking and text extraction", "Generating embeddings and indexing in Vector DB", "Retrieval of top-k chunks based on semantic similarity", "Prompt synthesis with retrieved context passed to LLM"], ["Vector DBs", "Chunking strategies"]],
  ["Chunking Strategies in RAG", "RAG", "Intermediate", "technical", "How do chunk size and chunk overlap affect retrieval accuracy in RAG systems?", ["RAG", "Embeddings"], ["Small chunks preserve specific facts but lose broader document context", "Large chunks provide full context but dilute semantic embedding similarity", "Chunk overlap (10-20%) prevents splitting sentences or ideas across boundaries"], ["RecursiveCharacterTextSplitter", "Semantic chunking"]],
  ["Vector Databases & HNSW", "Vector DB", "Intermediate", "technical", "How do Vector Databases perform fast approximate nearest neighbor search using HNSW?", ["Vector DB", "Algorithms"], ["Hierarchical Navigable Small World graphs multi-layer skip-list structure", "O(log N) approximate nearest neighbor search", "Balances query latency vs recall compared to exact flat search"], ["Cosine similarity vs Euclidean", "Pinecone vs Milvus"]],
  ["Prompt Engineering Patterns", "Prompting", "Easy", "technical", "Explain Few-Shot prompting, Chain-of-Thought (CoT), and ReAct prompting.", ["Prompt Engineering"], ["Few-shot provides explicit input-output demonstration examples in prompt", "Chain-of-Thought instructs model to 'think step by step' before answering", "ReAct alternates between Reasoning and Action (tool usage)"], ["Prompt injection", "System prompt design"]],
  ["Fine-Tuning with LoRA / QLoRA", "Fine-Tuning", "Advanced", "technical", "How does Low-Rank Adaptation (LoRA) enable parameter-efficient fine-tuning of LLMs?", ["Fine-Tuning", "Deep Learning"], ["Freezes base model weights and injects trainable low-rank rank decomposition matrices (A and B)", "Reduces trainable parameters by 99% while retaining performance", "QLoRA quantizes base model to 4-bit, enabling 70B model fine-tuning on single GPU"], ["PEFT library", "Catastrophic forgetting"]],
  ["Preventing Hallucinations", "AI Safety", "Intermediate", "technical", "What techniques do you use to detect and mitigate LLM hallucinations in production?", ["AI Safety", "RAG"], ["Grounding responses strictly on retrieved context with citation prompts", "Lowering temperature (0.0 to 0.2) for deterministic responses", "Automated validation using guardrails (Guardrails AI, NeMo Guardrails) or self-critique prompts"], ["Hallucination metrics", "Faithfulness evaluation"]],
  ["LLM Evaluation Frameworks", "Evaluation", "Intermediate", "technical", "How do you evaluate RAG systems using frameworks like Ragas or TruLens?", ["Evaluation", "RAG"], ["Faithfulness: is answer grounded strictly in retrieved context?", "Answer Relevance: does response answer user query?", "Context Recall & Precision: did retriever fetch correct information?"], ["LLM-as-a-judge", "Golden test sets"]],
  ["AI Agent Architecture", "AI Agents", "Intermediate", "technical", "What are AI Agents and how do frameworks like LangChain or LangGraph orchestrate them?", ["AI Agents", "LangChain"], ["Agent loop: Thought -> Action -> Observation -> Final Answer", "Equipped with external tools (web search, calculator, SQL query)", "LangGraph uses stateful directed graphs to handle complex multi-agent workflows"], ["Tool calling", "Human-in-the-loop"]],
  ["Function Calling / Structured Outputs", "LLMs", "Easy", "technical", "How do you ensure an LLM returns guaranteed valid JSON matching a Pydantic schema?", ["Function Calling", "Pydantic"], ["OpenAI function calling / tool_choice: {'type': 'function'}", "JSON Mode or Instructor library enforcing Pydantic models", "Grammar-based sampling (outlines) restricting next token generation"], ["Instructor library", "Token logits masking"]],
  ["Embeddings: Cosine vs Dot Product", "Embeddings", "Easy", "technical", "Compare Cosine Similarity, Dot Product, and Euclidean Distance for vector search.", ["Mathematics", "Embeddings"], ["Cosine similarity measures angle between vectors, independent of magnitude (-1 to 1)", "Dot product measures angle and magnitude (identical to cosine if normalized)", "Euclidean distance measures geometric distance in space"], ["Normalized embeddings", "Dimension size"]],
  ["Tokenization & Context Windows", "LLMs", "Easy", "technical", "Explain BPE (Byte Pair Encoding) tokenization and how context window size impacts cost and latency.", ["LLMs", "Tokenization"], ["BPE splits words into frequent subword tokens", "1,000 tokens is approximately 750 English words", "Context length increases memory quadratic in naive attention and costs scale per token"], ["tiktoken", "FlashAttention"]],
  ["FlashAttention & KV Cache", "Optimization", "Advanced", "technical", "Explain KV (Key-Value) Caching and FlashAttention in LLM inference.", ["Optimization", "Transformers"], ["KV cache stores precomputed key/value vectors of previous tokens to avoid recomputation", "FlashAttention reorganizes attention computation to maximize GPU SRAM access and avoid memory bottlenecks"], ["vLLM engine", "PagedAttention"]],
  ["vLLM & High-Throughput Serving", "Serving", "Advanced", "technical", "What is PagedAttention in vLLM and how does it achieve 10x throughput over HuggingFace?", ["vLLM", "Serving"], ["Applies OS virtual memory paging concept to allocate non-contiguous GPU memory for KV cache", "Eliminates memory fragmentation, allowing higher continuous batch sizes", "Continuous batching schedules requests dynamically without padding"], ["Continuous batching", "TensorRT-LLM"]],
  ["Reranking in RAG", "RAG", "Intermediate", "technical", "Why should you use a Cross-Encoder Reranker (e.g. Cohere Rerank) after vector search in RAG?", ["RAG", "Information Retrieval"], ["Bi-encoders (embedding search) are fast but compute independent vector representations", "Cross-encoders evaluate query and document together with full attention, providing superior relevance ranking", "Retrieve top 50 with vector search, rerank down to top 5"], ["Cross-Encoder", "Hybrid search"]],
  ["Hybrid Search (BM25 + Vector)", "RAG", "Intermediate", "technical", "What is Hybrid Search and why does combining BM25 keyword search with Vector search improve retrieval?", ["Search", "Information Retrieval"], ["Vector search captures semantic meaning but struggles with exact keyword matches (product codes, names)", "BM25 handles exact lexical matches effectively", "Reciprocal Rank Fusion (RRF) merges results into single ranked list"], ["RRF algorithm", "Sparse-dense vectors"]],
  ["Prompt Injection Defense", "AI Safety", "Intermediate", "technical", "What is prompt injection (direct and indirect) and how do you protect your AI system?", ["Security", "AI Safety"], ["Direct injection: user commands system to ignore previous instructions", "Indirect injection: untrusted external content (emails, web pages) contains hidden malicious commands", "Defenses: input sanitization, dual-LLM architectures, system prompt delimiters, and Guardrails"], ["NeMo Guardrails", "Data vs instruction separation"]],
  ["Fine-Tuning vs RAG", "Architecture", "Easy", "technical", "When should you use RAG vs Fine-Tuning for an enterprise generative AI solution?", ["System Design"], ["RAG for accessing dynamic proprietary knowledge, real-time updates, and verifiable citations", "Fine-tuning for teaching specialized style, tone, domain vocabulary, or following strict syntax", "Often combined: fine-tune for behavior, RAG for factual knowledge"], ["Cost trade-offs", "Data freshness"]],
  ["Quantization: GGUF vs AWQ vs GPTQ", "Optimization", "Advanced", "technical", "Compare model quantization formats: GGUF (llama.cpp) vs AWQ vs GPTQ.", ["Quantization"], ["GGUF is CPU/GPU friendly format optimized for llama.cpp and local execution", "GPTQ performs post-training 4-bit weight quantization optimized for GPUs", "AWQ protects salient weights, offering superior quality retention at 4-bit"], ["llama.cpp", "ExLlamaV2"]],
  ["LLM Streaming Responses", "API Design", "Easy", "practical", "How do you implement streaming LLM responses using Server-Sent Events (SSE) in FastAPI?", ["FastAPI", "Streaming"], ["StreamingResponse with async generator yielding token chunks", "Content-Type: text/event-stream", "Significantly reduces perceived Time-To-First-Token (TTFT) for users"], ["SSE vs WebSockets", "Async generators"]],
  ["Semantic Caching", "Optimization", "Intermediate", "technical", "How does Semantic Caching (e.g. GPTCache) reduce LLM API costs and latency?", ["Caching", "Vector Search"], ["Embeds user query and searches cache for semantically similar previous queries", "If cosine similarity > threshold (e.g. 0.95), returns cached response immediately", "Dramatically cuts expensive API calls for frequent questions"], ["GPTCache", "Cache invalidation"]],
  ["GraphRAG (Knowledge Graphs + LLMs)", "Modern AI", "Advanced", "technical", "What is GraphRAG and how does combining Knowledge Graphs with vector search solve complex queries?", ["GraphRAG", "Knowledge Graphs"], ["Extracts entities and relationships from text into a structured Knowledge Graph", "Allows multi-hop reasoning across connected entities that vector similarity misses", "Combines global community summaries with local entity retrieval"], ["Neo4j", "Multi-hop reasoning"]],
  ["Computer Vision: Object Detection", "Computer Vision", "Intermediate", "technical", "Explain the working principle of YOLO (You Only Look Once) object detection models.", ["Computer Vision", "YOLO"], ["Single-stage detector processing full image in one forward pass", "Divides image into grid, predicting bounding boxes and class probabilities simultaneously", "Extremely fast real-time inference compared to two-stage detectors (Faster R-CNN)"], ["IoU & Non-Max Suppression", "Anchor boxes"]],
  ["Vision Transformers (ViT)", "Computer Vision", "Advanced", "technical", "How do Vision Transformers adapt self-attention to image classification instead of CNNs?", ["ViT", "Transformers"], ["Splits image into non-overlapping patches (e.g. 16x16 pixels) and treats patches like tokens in NLP", "Adds positional embeddings and passes through standard Transformer encoder", "Outperforms CNNs on large-scale datasets due to lower inductive bias"], ["Patch embeddings", "CNN vs ViT"]],
  ["Multi-Modal AI Models", "Multi-Modal", "Intermediate", "technical", "How do multi-modal models like CLIP or GPT-4V align vision and text representations?", ["Multi-Modal", "CLIP"], ["CLIP trains image encoder and text encoder using contrastive loss on image-text pairs", "Pulls matching image-text embeddings close in shared latent space, pushes non-matches apart", "Enables zero-shot image classification and cross-modal search"], ["Contrastive learning", "Visual question answering"]],
  ["Speech-to-Text with Whisper", "Audio AI", "Easy", "technical", "How does OpenAI's Whisper model perform robust automatic speech recognition (ASR)?", ["Audio AI", "Whisper"], ["Encoder-decoder Transformer trained on 680,000 hours of multilingual audio", "Converts audio to mel-spectrogram features", "Handles transcription, translation, and timestamp prediction in single model"], ["Voice activity detection", "Audio streaming"]],
  ["LangChain vs LlamaIndex", "Frameworks", "Easy", "technical", "Compare LangChain and LlamaIndex for building LLM applications.", ["Frameworks"], ["LlamaIndex specializes in data ingestion, indexing, and advanced retrieval for RAG", "LangChain is broader general-purpose framework for chaining agents, tools, and prompts", "Often used together: LlamaIndex for retrieval engine, LangChain for agent orchestration"], ["LangGraph", "Data connectors"]],
  ["Guardrails & Output Validation", "AI Safety", "Intermediate", "technical", "How do you enforce deterministic safety guardrails on LLM outputs using Guardrails AI or NeMo?", ["AI Safety", "Validation"], ["Intercepts output before returning to user, validating against defined rails", "Checks for PII leaks, competitor mentions, toxic content, and format compliance", "Can trigger automatic re-asking or fallback response on failure"], ["NeMo Guardrails", "PII redaction"]],
  ["Context Window Overflow Handling", "Optimization", "Intermediate", "scenario", "A user conversation exceeds the LLM context window limit. How do you maintain conversational memory?", ["Memory", "LLMs"], ["Sliding window keeping only the last N turns", "Summary memory: periodically ask LLM to summarize older conversation turns and inject summary into prompt", "Vector memory: store past turns in vector DB and retrieve relevant past context"], ["ConversationSummaryBufferMemory", "Hierarchical memory"]],
  ["Cost & Latency Optimization for LLMs", "Production Engineering", "Intermediate", "scenario", "Your enterprise LLM bill is $15,000/month with 2.5s p95 latency. What architectural changes do you make?", ["Cost Optimization", "Performance"], ["Implement semantic caching for common queries", "Route simple queries to smaller, cheaper models (GPT-4o-mini / Claude Haiku) and reserve large models for complex reasoning", "Shorten prompts, compress context, and optimize RAG retrieval chunk counts"], ["Model routing", "TTFT optimization"]],
  ["Synthetic Data Generation with LLMs", "Data Engineering", "Intermediate", "technical", "How do you generate and validate synthetic training data using LLMs for domain-specific tasks?", ["Synthetic Data"], ["Prompt powerful teacher LLM to generate diverse query-response pairs", "Filter out low-quality or duplicate samples using embedding deduplication and rule-based validation", "Use synthetic pairs to fine-tune smaller, cost-effective student models"], ["Self-Instruct", "Quality filtering"]],
  ["Responsible AI & Bias Auditing", "AI Ethics", "Easy", "technical", "What steps do you take to audit an AI application for safety, bias, and regulatory compliance?", ["AI Ethics", "Governance"], ["Red-teaming with adversarial prompt injection tests", "Benchmarking performance across protected demographic groups", "Clear transparency disclosures to users that they are interacting with AI"], ["EU AI Act", "Red teaming"]],
  ["Multi-Agent Swarms", "AI Agents", "Advanced", "technical", "How do multi-agent collaboration frameworks (AutoGen, CrewAI) solve complex multi-step workflows?", ["AI Agents", "CrewAI"], ["Specialized agents with defined personas, goals, and tools (e.g. Researcher, Writer, Reviewer)", "Sequential or hierarchical task delegation with inter-agent feedback loops", "Significantly reduces individual model hallucination through peer review"], ["AutoGen", "Role-based agents"]],
  ["Real-World AI Application Architecture", "Project Experience", "Intermediate", "behavioral", "Describe an end-to-end AI application you built using LLMs or Computer Vision.", ["Project Experience", "Communication"], ["Problem statement and user requirements", "Model selection, prompting, and RAG/fine-tuning architecture", "Production deployment, latency monitoring, and user adoption metrics"], ["Evaluation setup", "Lessons learned"]],
  ["Stakeholder Trust in AI", "Behavioral", "Easy", "behavioral", "How do you build stakeholder confidence in an AI feature when outputs are non-deterministic?", ["Stakeholder Management", "Communication"], ["Provide visible source citations and confidence indicators", "Implement strict guardrails preventing harmful or off-brand outputs", "Conduct rigorous evaluation benchmarking and human-in-the-loop validation"], ["Human-in-the-loop", "Explainability"]],
  ["Future of Foundation Models", "Modern Trends", "Easy", "technical", "What are the key differences between standard LLMs and Reasoning Models (e.g. OpenAI o1 / o3)?", ["Modern AI", "Reasoning Models"], ["Reasoning models use reinforcement learning to generate long internal chains of thought before answering", "Perform extensive search and backtracking, dramatically improving math, coding, and logical puzzles", "Trade off higher latency and compute for superior accuracy on complex tasks"], ["Test-time compute", "Reinforcement learning from AI feedback"]]
];

const aiQuestions = aiTopics.map((t, idx) => ({
  id: `ai-${String(idx + 1).padStart(3, '0')}`,
  role: "AI Engineer",
  category: t[1],
  difficulty: t[2],
  format: t[3],
  question: t[4],
  expectedSkills: t[5],
  evaluationPoints: t[6],
  followUpTopics: t[7]
}));
save('aiEngineer.ts', 'AI_ENGINEER_QUESTIONS', aiQuestions);
