const fs = require('fs');
const path = require('path');
const targetDir = 'C:/sih/src/data/interviewQuestions/banks';

function save(filename, exportName, questions) {
  const code = `import { RoleQuestion } from '../types';\n\nexport const ${exportName}: RoleQuestion[] = ${JSON.stringify(questions, null, 2)};\n`;
  fs.writeFileSync(path.join(targetDir, filename), code, 'utf-8');
  console.log(`✓ ${filename} written (${questions.length} questions)`);
}

const webTopics = [
  ["HTTP/1.1 vs HTTP/2 vs HTTP/3", "Networking", "Intermediate", "technical", "Compare HTTP/1.1, HTTP/2 (multiplexing, header compression), and HTTP/3 (QUIC/UDP).", ["Web Protocols", "HTTP"], ["HTTP/1.1 suffers from head-of-line blocking and opens multiple TCP connections", "HTTP/2 introduces binary framing, multiplexing multiple streams over single TCP connection, and HPACK header compression", "HTTP/3 replaces TCP with QUIC over UDP, eliminating TCP head-of-line blocking caused by packet loss"], ["QUIC protocol", "Server Push"]],
  ["Browser Critical Rendering Path", "Browser Internals", "Intermediate", "technical", "Explain the Critical Rendering Path: DOM -> CSSOM -> Render Tree -> Layout -> Paint.", ["Browser Internals", "Performance"], ["Browser parses HTML to build Document Object Model (DOM)", "Parses CSS to build CSS Object Model (CSSOM)", "Combines DOM and CSSOM into Render Tree containing visible nodes", "Layout computes exact geometry and positions; Paint rasterizes pixels onto screen"], ["Reflow vs Repaint", "will-change property"]],
  ["CSS Specificity Calculation", "CSS", "Easy", "technical", "How is CSS Specificity calculated? (Inline > ID > Class/Attribute > Element).", ["CSS"], ["Inline styles (1000) > IDs (100) > Classes, attributes, pseudo-classes (10) > Elements and pseudo-elements (1)", "!important overrides normal specificity but should be used sparingly", "Equal specificity resolved by source order (last declared rule wins)"], ["CSS Cascade Layers (@layer)", "!important usage"]],
  ["JavaScript Closures & Lexical Scope", "JavaScript", "Intermediate", "technical", "What is a closure in JavaScript? Provide an example of data privacy using closures.", ["JavaScript", "Closures"], ["Function remembers and accesses variables from its lexical scope even when executed outside that scope", "Example: function counter() { let count = 0; return () => ++count; }", "Used to emulate private variables before ES6 private class fields (#field)"], ["Memory leaks with closures", "Currying"]],
  ["Async JavaScript: Event Loop", "JavaScript", "Intermediate", "technical", "Explain the JavaScript Event Loop: Call Stack, Web APIs, Task Queue, and Microtask Queue.", ["JavaScript Internals", "Event Loop"], ["Call Stack executes synchronous code (LIFO)", "Asynchronous Web APIs (fetch, setTimeout) complete and push callbacks to queues", "Microtask Queue (Promises, queueMicrotask) has priority over Task/Macrotask Queue (setTimeout, I/O)", "Event loop drains all microtasks between each macrotask"], ["Macrotasks vs Microtasks", "setTimeout(fn, 0) timing"]],
  ["CORS: Preflight & Headers", "Web Security", "Intermediate", "technical", "How does Cross-Origin Resource Sharing (CORS) work? What triggers an OPTIONS preflight request?", ["Security", "CORS"], ["Browser security mechanism enforcing Same-Origin Policy", "Preflight OPTIONS request triggered if method is non-simple (PUT, DELETE, PATCH) or custom headers (Authorization) are present", "Server must respond with Access-Control-Allow-Origin, Methods, and Headers"], ["Same-Origin Policy", "Credentials mode (cookies)"]],
  ["Web Accessibility (WCAG & ARIA)", "Accessibility", "Easy", "technical", "What are the four principles of WCAG (POUR) and when should you use ARIA attributes?", ["Accessibility", "WCAG"], ["POUR: Perceivable, Operable, Understandable, Robust", "First rule of ARIA: use semantic native HTML (<button>, <nav>) whenever possible", "Use ARIA (aria-expanded, aria-live, aria-label) only when custom widgets cannot be described by native HTML"], ["Color contrast", "Screen reader testing"]],
  ["Service Workers & PWA", "PWA", "Intermediate", "technical", "What is a Service Worker and how does it enable offline functionality in Progressive Web Apps?", ["PWA", "Service Workers"], ["JavaScript worker running in background separate from web page context", "Acts as programmable client-side proxy intercepting network fetch requests", "Uses Cache Storage API to cache shell assets and API responses for offline access"], ["Cache-First vs Network-First", "Web App Manifest"]],
  ["CSS Grid vs Flexbox", "CSS", "Easy", "technical", "When do you use CSS Grid and when do you use CSS Flexbox in web page layout?", ["CSS", "Layout"], ["Flexbox is one-dimensional (handles row OR column flow, ideal for alignment and navigation bars)", "CSS Grid is two-dimensional (handles rows AND columns simultaneously, ideal for whole-page templates and image galleries)", "Combine both: Grid for page skeleton, Flexbox inside grid cells"], ["Grid areas", "minmax() function"]],
  ["Web Vitals & Performance Optimization", "Performance", "Intermediate", "technical", "What are Largest Contentful Paint (LCP), Interaction to Next Paint (INP), and Cumulative Layout Shift (CLS)?", ["Core Web Vitals", "Performance"], ["LCP measures loading performance (target <2.5s) — optimize by preloading hero image and using modern formats (WebP/AVIF)", "INP measures responsiveness to user interactions (target <200ms) — optimize by breaking long tasks and deferring non-critical JS", "CLS measures visual stability (target <0.1) — optimize by reserving explicit width/height on images and dynamic embeds"], ["Lighthouse audits", "Resource hints (preload, preconnect)"]],
  ["Browser Storage Mechanisms", "Storage", "Easy", "technical", "Compare localStorage, sessionStorage, Cookies, and IndexedDB in terms of capacity, scope, and use cases.", ["Storage", "Browser APIs"], ["localStorage: ~5-10MB, persists across sessions, synchronous, same-origin", "sessionStorage: ~5MB, cleared when tab closes", "Cookies: ~4KB, sent with every HTTP request, supports HttpOnly/Secure flags (ideal for session auth)", "IndexedDB: 50MB+, asynchronous transactional NoSQL object store for large offline datasets"], ["HttpOnly cookies", "Storage quotas"]],
  ["Web Security: XSS & CSRF Defenses", "Security", "Intermediate", "technical", "Explain Cross-Site Scripting (XSS) and Cross-Site Request Forgery (CSRF). How do you prevent both?", ["Security", "OWASP"], ["XSS: injecting malicious scripts into victim's browser -> Prevent via context-aware output encoding, sanitizing HTML, and Content-Security-Policy (CSP)", "CSRF: unauthorized commands transmitted from a trusted user -> Prevent via SameSite=Strict cookie attribute and Anti-CSRF tokens"], ["Content Security Policy (CSP)", "SameSite cookie attribute"]],
  ["Responsive Images with <picture> and srcset", "HTML", "Easy", "technical", "How do you implement art direction and resolution switching using <picture> and srcset?", ["HTML", "Responsive Web"], ["<picture> with <source media='(max-width: 768px)' srcset='mobile.webp'> for art direction (different crop/composition on mobile)", "srcset='image-320w.jpg 320w, image-800w.jpg 800w' with sizes='(max-width: 600px) 100vw, 50vw' allows browser to pick optimal file size based on DPR and viewport"], ["AVIF and WebP formats", "loading='lazy'"]],
  ["Debouncing vs Throttling in JavaScript", "JavaScript", "Intermediate", "practical", "Implement debounce and throttle functions in JavaScript. When do you use each?", ["JavaScript", "Performance"], ["Debounce delays function execution until after X ms of inactivity (e.g. search input autocomplete)", "Throttle guarantees function is executed at most once every X ms (e.g. window resize, scroll listeners)", "Debounce resets timer on every event; throttle checks elapsed timestamp"], ["Lodash debounce", "requestAnimationFrame"]],
  ["CSS Transitions vs Keyframe Animations", "CSS", "Easy", "technical", "Compare CSS transitions and @keyframes animations. Which properties animate on the GPU?", ["CSS", "Animations"], ["Transitions animate property changes between two states triggered by events (hover, focus, class toggle)", "Keyframes allow multi-step, looping, complex timeline animations without user interaction", "Animate transform and opacity for 60fps GPU acceleration; avoid animating top, left, width, height (triggers reflow)"], ["GPU compositing", "will-change"]],
  ["REST API Design & Content Negotiation", "APIs", "Intermediate", "technical", "How does Content Negotiation work in HTTP using Accept and Content-Type headers?", ["REST", "HTTP"], ["Client sends 'Accept: application/json, text/xml;q=0.9' expressing desired response formats with quality weights", "Server inspects Accept header and responds with matching format in 'Content-Type: application/json' header", "Returns HTTP 406 Not Acceptable if server cannot satisfy client's accepted formats"], ["HTTP headers", "HATEOAS"]],
  ["JavaScript Prototypes & Prototypal Inheritance", "JavaScript", "Intermediate", "technical", "How does prototypal inheritance work in JavaScript? Explain the prototype chain.", ["JavaScript Internals"], ["Every JavaScript object has an internal [[Prototype]] link (__proto__) pointing to another object", "Property lookup traverses up the prototype chain until found or null is reached (Object.prototype)", "ES6 'class' syntax is syntactic sugar over prototypal inheritance using constructor functions and prototypes"], ["Object.create()", "Class syntax"]],
  ["WebSockets vs Server-Sent Events (SSE)", "Real-Time Web", "Intermediate", "technical", "Compare WebSockets and Server-Sent Events (SSE). When is SSE the better architectural choice?", ["WebSockets", "SSE"], ["WebSockets: full-duplex bidirectional TCP communication protocol (ideal for gaming, chat, collaborative editing)", "SSE: unidirectional server-to-client streaming over standard HTTP using Content-Type: text/event-stream (simpler, auto-reconnection, works with HTTP/2 and proxies)", "Choose SSE for live feeds, stock tickers, and LLM streaming responses"], ["EventSource API", "HTTP/2 multiplexing"]],
  ["DOM Manipulation & DocumentFragments", "DOM", "Easy", "practical", "Why is appending 1,000 elements to a DocumentFragment faster than appending directly to document.body?", ["DOM", "Performance"], ["Each direct append to document.body triggers layout reflow and repaint in the browser engine", "DocumentFragment is an off-screen lightweight container holding DOM nodes in memory", "Appending DocumentFragment to body triggers only ONE single reflow and repaint for all 1,000 children"], ["Reflow optimization", "Virtual DOM concept"]],
  ["Semantic HTML5 Elements & SEO", "HTML", "Easy", "technical", "Why are semantic elements (<header>, <nav>, <main>, <article>, <aside>, <footer>) crucial for SEO and accessibility?", ["HTML", "SEO"], ["Search engine bots (Googlebot) parse semantic tags to understand content hierarchy, priority, and context", "Screen readers rely on landmarks (<main>, <nav>) to allow users to skip repetitive navigation directly to primary content", "Improves maintainability and developer readability over generic <div> soup"], ["Landmark roles", "SEO best practices"]],
  ["Module Bundlers: Webpack vs Vite", "Build Tools", "Intermediate", "technical", "How does Vite achieve instant server start compared to traditional Webpack bundling?", ["Vite", "Webpack"], ["Webpack bundles entire application codebase into bundle files before starting dev server (slow on large codebases)", "Vite uses native browser ES Modules (ESM) in development; serves source files on-demand over HTTP without pre-bundling", "Uses lightning-fast esbuild written in Go for dependency pre-bundling; Rollup for optimized production builds"], ["ES Modules", "Tree-shaking"]],
  ["Cross-Site Scripting (XSS) Types", "Security", "Intermediate", "technical", "Explain Stored XSS, Reflected XSS, and DOM-based XSS with remediation strategies.", ["Security", "XSS"], ["Stored XSS: malicious script permanently stored in database (comments, profiles) and served to all viewers", "Reflected XSS: malicious script reflected off web server immediately via URL parameter or form input", "DOM-based XSS: vulnerability exists entirely in client-side JS modifying DOM unsafely (innerHTML, document.write)"], ["DOMPurify", "CSP headers"]],
  ["Dark Mode Implementation with CSS Variables", "CSS", "Easy", "practical", "How do you implement a theme switcher (Dark/Light mode) using CSS custom properties and system preference?", ["CSS", "Design Systems"], ["Define color variables on :root and override them under [data-theme='dark'] or .dark selector", "Detect OS preference with @media (prefers-color-scheme: dark)", "Toggle theme attribute via JavaScript document.documentElement.setAttribute('data-theme', theme) and persist in localStorage"], ["prefers-color-scheme", "CSS custom properties"]],
  ["JavaScript Memory Leaks", "Performance", "Intermediate", "technical", "What common coding patterns cause memory leaks in single-page JavaScript applications?", ["JavaScript", "Memory Management"], ["Forgotten timers or intervals (setInterval) holding references to unmounted components", "Unremoved event listeners on global window or document objects", "Detached DOM trees referenced in global arrays or closures", "Unbounded growing caches without LRU eviction"], ["Chrome DevTools Memory tab", "Heap snapshots"]],
  ["SEO Essentials: Meta Tags & Structured Data", "SEO", "Easy", "technical", "What meta tags and Schema.org JSON-LD structured data should every modern website include?", ["SEO", "Web Standards"], ["Title tag (<60 chars) and meta description (<160 chars)", "Open Graph (og:title, og:image, og:url) and Twitter Card tags for social media link sharing previews", "JSON-LD structured data describing Organization, Article, Breadcrumb, or Product for rich Google search snippets"], ["Open Graph", "JSON-LD"]],
  ["Frontend Form Validation & Constraint Validation API", "HTML & JS", "Easy", "technical", "How does native HTML5 Constraint Validation API work (checkValidity, setCustomValidity)?", ["HTML", "Forms"], ["Built-in attributes: required, pattern, min, max, minlength, type='email'", "element.checkValidity() returns boolean; reportValidity() triggers browser native validation tooltip", "element.setCustomValidity('custom message') allows dynamic custom validation messages"], ["FormData API", "Pattern regex"]],
  ["Web Workers for Background Tasks", "Concurrency", "Intermediate", "technical", "When should you use Web Workers in JavaScript and what are their limitations?", ["Web Workers", "Performance"], ["Executes heavy computational tasks (image processing, encryption, large data parsing) on a separate OS background thread", "Prevents freezing the main UI thread (maintains 60fps animations and responsiveness)", "Limitations: No direct access to DOM or window object; communicates via postMessage() and onmessage events"], ["postMessage API", "Transferable objects"]],
  ["Intersection Observer API", "Browser APIs", "Intermediate", "practical", "How do you use IntersectionObserver for infinite scrolling and lazy loading images?", ["Browser APIs", "Performance"], ["Creates observer watching target elements intersecting with viewport", "callback = (entries) => entries.forEach(entry => if (entry.isIntersecting) loadContent())", "Much more performant than listening to window scroll events; avoids layout thrashing"], ["Lazy loading", "Infinite scroll"]],
  ["HTTP Caching Headers", "Caching", "Intermediate", "technical", "Explain Cache-Control headers: max-age, no-cache, no-store, immutable, and ETag revalidation.", ["HTTP Caching", "Performance"], ["max-age=seconds: duration browser can serve cached copy without revalidating", "no-cache: forces browser to validate with server (using ETag or Last-Modified) before using cached copy", "no-store: strictly prohibits storing in cache (sensitive user data)", "immutable: indicates asset will never change (hashed JS/CSS bundles)"], ["ETag and 304 Not Modified", "Stale-while-revalidate"]],
  ["Modern CSS: Subgrid & Container Queries", "CSS", "Intermediate", "technical", "What are CSS Container Queries (@container) and how do they differ from Media Queries?", ["Modern CSS"], ["Media queries evaluate the global browser viewport width", "Container queries evaluate the width of the component's immediate parent container", "Allows modular components to adapt their layout based on where they are placed (sidebar vs main content column)"], ["@container", "Subgrid"]],
  ["Web Cryptography API", "Security", "Intermediate", "technical", "How does window.crypto provide cryptographically secure random values and hashing in browser JS?", ["Web Crypto", "Security"], ["crypto.getRandomValues() generates cryptographically secure random numbers (unlike Math.random() which is pseudo-random)", "crypto.subtle provides asynchronous cryptographic functions: digest (SHA-256), sign, verify, encrypt (AES-GCM), and decrypt", "Used for client-side password hashing and end-to-end encryption"], ["crypto.subtle", "AES-GCM"]],
  ["Cross-Origin Embeddings & iframe Security", "Security", "Intermediate", "technical", "How do you secure iframes using sandbox attributes and prevent Clickjacking with X-Frame-Options?", ["Security", "iframes"], ["X-Frame-Options: DENY or SAMEORIGIN prevents page from being embedded in malicious third-party iframes (clickjacking defense)", "CSP frame-ancestors directive provides modern fine-grained embedding control", "sandbox='allow-scripts allow-same-origin' restricts iframe capabilities to minimum required"], ["Clickjacking", "Content Security Policy"]],
  ["Full-Stack Web Project Architecture", "Project Experience", "Intermediate", "behavioral", "Describe an end-to-end web application you built. How did you optimize frontend performance and asset delivery?", ["Project Experience", "Communication"], ["Application purpose, tech stack, and responsive design decisions", "Performance optimizations implemented (code splitting, image optimizations, caching)", "Measurable outcome (Lighthouse score improvement, reduced bounce rate)"], ["Lighthouse score", "Lessons learned"]],
  ["Cross-Browser Debugging Experience", "Troubleshooting", "Intermediate", "behavioral", "Tell me about a difficult browser-specific bug (e.g. Safari-only layout crash) you resolved.", ["Debugging", "Cross-Browser"], ["Bug discovery and isolating failure to specific browser engine (WebKit vs Blink)", "Inspection with browser developer tools and reading web standards specifications", "Implementation of robust progressive enhancement or polyfill solution"], ["Browser compatibility", "Vendor prefixes"]],
  ["Future of the Web (WebAssembly & WebGPU)", "Modern Trends", "Easy", "technical", "What is WebAssembly (Wasm) and how does it enable high-performance compute in web browsers?", ["WebAssembly", "Modern Web"], ["Binary instruction format providing near-native execution speed in web browsers alongside JavaScript", "Enables running C++, Rust, Go, and Python libraries directly on the client (Figma, Photoshop Web, Unity games)", "Complements JavaScript by handling compute-heavy tasks (video editing, 3D rendering, cryptography)"], ["WebGPU", "Rust with Wasm"]]
];

const webQuestions = webTopics.map((t, idx) => ({
  id: `web-${String(idx + 1).padStart(3, '0')}`,
  role: "Web Developer",
  category: t[1],
  difficulty: t[2],
  format: t[3],
  question: t[4],
  expectedSkills: t[5],
  evaluationPoints: t[6],
  followUpTopics: t[7]
}));
save('webDeveloper.ts', 'WEB_DEVELOPER_QUESTIONS', webQuestions);
