const fs = require('fs');
const path = require('path');
const targetDir = 'C:/sih/src/data/interviewQuestions/banks';

function save(filename, exportName, questions) {
  const code = `import { RoleQuestion } from '../types';\n\nexport const ${exportName}: RoleQuestion[] = ${JSON.stringify(questions, null, 2)};\n`;
  fs.writeFileSync(path.join(targetDir, filename), code, 'utf-8');
  console.log(`✓ ${filename} written (${questions.length} questions)`);
}

const mobileTopics = [
  ["Native vs Cross-Platform (Flutter vs React Native)", "Mobile Architecture", "Easy", "technical", "Compare Native development (Swift/Kotlin), Flutter, and React Native in terms of performance, development speed, and access to native APIs.", ["Mobile Architecture"], ["Native gives highest performance, day-1 access to new OS features, and smallest binary size", "Flutter compiles to native ARM machine code via Dart, renders via Skia/Impeller, bypassing OS native OEM widgets", "React Native uses JavaScript bridge (or modern JSI / Fabric architecture) to render native platform components"], ["React Native New Architecture (Fabric/TurboModules)", "Flutter Impeller engine"]],
  ["Mobile App Lifecycle Events", "App Lifecycle", "Easy", "technical", "Explain the common mobile application lifecycle states (Active, Inactive, Background, Suspended).", ["Lifecycle Management"], ["Active: app is in foreground and receiving user input events", "Inactive / Paused: app is in foreground but interrupted (incoming phone call, system alert)", "Background: app is running code in background (audio, GPS, data sync) but UI is hidden", "Suspended: app is in memory but execution is halted; OS may terminate it at any moment to reclaim RAM"], ["State preservation", "Background task limits"]],
  ["Offline-First Architecture", "Data Architecture", "Intermediate", "technical", "How do you design an offline-first mobile app that synchronizes data with a cloud backend when connection restores?", ["Offline-First", "Architecture"], ["Local database (SQLite, Realm, Room, Core Data) acts as the single source of truth for the UI", "Mutations are written to local DB first and appended to an outgoing sync queue", "Background worker syncs queued changes to backend on network reconnection, resolving conflicts (Last-Write-Wins or server timestamps)"], ["Conflict resolution", "Sync queue"]],
  ["Push Notifications: APNs and FCM", "Push Notifications", "Intermediate", "technical", "How do Apple Push Notification service (APNs) and Firebase Cloud Messaging (FCM) deliver push notifications to mobile devices?", ["APNs", "FCM"], ["Device registers with OS push service and receives a unique device registration token", "Client app sends device token to app backend server", "Backend sends payload to APNs/FCM API; push servers maintain persistent low-power connection to device, displaying notification or waking app in background"], ["Silent push notifications", "Notification payloads"]],
  ["Deep Linking vs Universal Links", "Deep Linking", "Intermediate", "technical", "Compare standard URI schemes (myapp://) vs Universal Links (iOS) / App Links (Android).", ["Deep Linking"], ["Custom URL schemes (myapp://path) trigger browser security warnings and can be hijacked by other apps with same scheme", "Universal Links / App Links use standard HTTPS URLs (https://myapp.com/item/123) verified cryptographically via domain association files (apple-app-site-association / assetlinks.json)", "Falls back gracefully to web page if app is not installed"], ["AASA file", "assetlinks.json"]],
  ["Mobile Memory Management & Leaks", "Performance", "Intermediate", "technical", "How does memory management work in iOS (ARC) and Android (Garbage Collection)? What causes mobile memory leaks?", ["Memory Management"], ["iOS uses Automatic Reference Counting (ARC) at compile time; strong reference cycles (retain cycles) cause memory leaks -> solved with weak/unowned references", "Android uses runtime Garbage Collection (Generational GC); holding references to Activity context in static variables or long-running background threads causes memory leaks", "Tools: Xcode Instruments (Leaks), Android Studio Memory Profiler, LeakCanary"], ["Retain cycles", "LeakCanary"]],
  ["Secure Storage in Mobile Apps", "Security", "Easy", "technical", "Where and how should sensitive user data (JWT tokens, API keys, credentials) be stored on iOS and Android?", ["Mobile Security", "Storage"], ["Never store secrets in SharedPreferences, UserDefaults, or unencrypted local SQLite databases", "iOS: use iOS Keychain Services (hardware-backed Secure Enclave encryption)", "Android: use Android Keystore system and EncryptedSharedPreferences (Jetpack Security)"], ["iOS Keychain", "Android Keystore"]],
  ["SSL Pinning in Mobile Apps", "Security", "Intermediate", "technical", "What is SSL/TLS Certificate Pinning and why is it implemented in high-security mobile applications?", ["Security", "Networking"], ["Standard TLS trusts any certificate signed by an OS-installed Certificate Authority (vulnerable to rogue CAs, corporate proxies, and MitM attacks like Charles Proxy)", "SSL Pinning embeds the specific server public key or certificate hash directly inside the client app binary", "Connection is aborted immediately if server certificate does not match the pinned public key"], ["Public key pinning", "Certificate rotation risk"]],
  ["Biometric Authentication Integration", "Security", "Easy", "practical", "How do you implement biometric authentication (Face ID, Touch ID, Fingerprint) in mobile apps?", ["Biometrics", "Security"], ["iOS: LocalAuthentication framework (LAContext evaluatePolicy:deviceOwnerAuthenticationWithBiometrics)", "Android: BiometricPrompt API (Jetpack Biometric library)", "Store sensitive auth tokens inside Keychain/Keystore configured to require biometric user unlock before decryption"], ["BiometricPrompt", "LocalAuthentication"]],
  ["Handling Screen Rotation & State Preservation", "State Management", "Easy", "technical", "What happens during device orientation changes and how do you prevent losing user input?", ["State Management"], ["On Android, configuration change destroys and recreates the Activity by default; save UI state in ViewModel or onSaveInstanceState bundle", "On iOS, view controllers are not destroyed on rotation; views resize via Auto Layout and size classes", "Maintain business state in persistent architectural state stores (Redux, BLoC, ViewModels) independent of UI lifecycle"], ["ViewModel persistence", "onSaveInstanceState"]],
  ["Image Caching & Memory Optimization", "Performance", "Intermediate", "technical", "How do libraries like Glide, Picasso, and SDWebImage optimize image loading and scrolling performance?", ["Image Loading", "Performance"], ["Multi-tier caching: Memory cache (LruCache) for instant retrieval + Disk cache for offline access", "Automatic downsampling: decodes image to the exact target ImageView dimensions instead of loading full resolution into RAM", "Cancels ongoing network image requests when list item scrolls off-screen to save bandwidth"], ["LruCache", "Bitmap downsampling"]],
  ["In-App Purchases & Subscriptions", "Monetization", "Intermediate", "technical", "Explain the server-side receipt validation flow for Apple In-App Purchases (StoreKit 2) and Google Play Billing.", ["IAP", "Monetization"], ["User initiates purchase -> App Store / Google Play processes payment -> Client receives signed transaction receipt", "Client sends receipt to app backend server", "App backend verifies signed transaction cryptographically with Apple/Google server API (or uses RevenueCat) before unlocking premium entitlements"], ["StoreKit 2", "Server-to-server notifications"]],
  ["Mobile CI/CD Pipelines (Fastlane)", "DevOps", "Intermediate", "technical", "How does Fastlane automate mobile build, code signing, and app store deployments?", ["Fastlane", "CI/CD"], ["Automates provisioning profiles and certificates management using 'fastlane match' backed by encrypted Git repo", "Compiles binary (.ipa for iOS, .aab for Android) and runs automated unit/UI tests", "Uploads binaries to TestFlight / Google Play Internal Track and deploys release metadata to App Store Connect / Play Console"], ["Match / Code signing", "TestFlight automation"]],
  ["App Size Optimization (App Bundles)", "Optimization", "Easy", "technical", "How do Android App Bundles (.aab) and iOS App Thinning reduce download sizes for users?", ["Optimization"], ["Android App Bundle (.aab): Google Play generates optimized split APKs tailored to specific user device (CPU architecture, screen density, language)", "iOS App Thinning: Slicing creates variants containing only architecture/assets needed for target device", "ProGuard/R8 in Android strips unused code, obfuscates classes, and inlines methods"], ["R8 / ProGuard", "Asset slicing"]],
  ["Battery Consumption Optimization", "Performance", "Intermediate", "technical", "What common mobile programming patterns drain device battery rapidly and how do you optimize them?", ["Battery Optimization", "Performance"], ["Continuous GPS tracking at high accuracy -> use geofencing, significant location changes, or lower accuracy intervals", "Aggressive network polling -> use Push Notifications or WebSockets instead of repetitive HTTP polling", "Wakelocks preventing device sleep -> use OS-managed job schedulers (WorkManager / BackgroundTasks)"], ["WorkManager", "Significant location updates"]],
  ["Reactive State Management Patterns", "State Management", "Intermediate", "technical", "Compare state management approaches in mobile apps: Redux, BLoC (Flutter), and MVVM with Reactive Streams.", ["State Management"], ["Redux: unidirectional data flow with single centralized state store, actions, and pure reducers", "BLoC (Business Logic Component): uses reactive Streams (Sink for events, Stream for states) separating presentation from logic in Flutter", "MVVM: ViewModel exposes Observable/StateFlow properties that the View observes and binds to declaratively"], ["StateFlow vs SharedFlow", "BLoC pattern"]],
  ["Accessibility on Mobile Devices", "Accessibility", "Easy", "technical", "How do you optimize mobile apps for screen readers (VoiceOver on iOS, TalkBack on Android)?", ["Accessibility", "Mobile"], ["Set descriptive accessibilityLabel / contentDescription on all icon buttons and interactive views", "Group related elements into single accessible containers to avoid cluttered navigation", "Support Dynamic Type (system font scaling) so text scales smoothly without clipping or overlapping"], ["VoiceOver", "TalkBack"]],
  ["Cross-Platform Native Modules & JSI", "Cross-Platform", "Advanced", "technical", "How does React Native's JavaScript Interface (JSI) eliminate the legacy asynchronous JSON bridge?", ["React Native", "Architecture"], ["Legacy bridge serialized data into JSON strings across asynchronous asynchronous queue (performance bottleneck)", "JSI allows JavaScript runtime to hold direct C++ host object references and call native methods synchronously", "Enables high-performance direct interactions (60fps animations with Reanimated, direct camera buffer access)"], ["TurboModules", "Fabric renderer"]],
  ["Mobile Database Selection", "Database", "Easy", "technical", "Compare SQLite, Realm, and Key-Value stores (MMKV, SharedPreferences) for mobile apps.", ["Mobile Database"], ["SQLite (Room / Core Data): robust relational database with SQL query support, migrations, and ACID transactions", "Realm: object-oriented mobile database with direct object mapping and reactive live queries without SQL overhead", "MMKV: high-performance memory-mapped (mmap) key-value store 100x faster than SharedPreferences"], ["Room ORM", "MMKV"]],
  ["App Permissions Architecture", "Security", "Easy", "technical", "How do runtime permission requests work on iOS and modern Android (API 23+)?", ["Security", "Permissions"], ["Install-time permissions granted automatically (Internet access)", "Runtime permissions require explicit user prompt at time of feature use (Camera, Location, Microphone, Contacts)", "Must provide clear in-context explanation (permission rationale) before prompting, and handle 'Don't ask again' / Denied states gracefully"], ["Permission rationale", "One-time permissions"]],
  ["Automated Mobile UI Testing", "Testing", "Intermediate", "technical", "Compare Appium, XCUITest (iOS), and Espresso (Android) for automated mobile testing.", ["Mobile Testing"], ["Appium is cross-platform, black-box, supports multiple languages, but runs slower out-of-process over HTTP", "Espresso (Android) and XCUITest (iOS) run in-process with direct access to app code, providing ultra-fast execution and automatic synchronization with UI thread"], ["Espresso", "XCUITest"]],
  ["Handling Network Failures Gracefully", "Networking", "Easy", "practical", "How do you implement retry policies with exponential backoff and network reachability listeners in mobile apps?", ["Networking", "Resilience"], ["Listen to network connectivity changes (ConnectivityManager in Android / NWPathMonitor in iOS)", "When API call fails due to network error, retry with exponential backoff and jitter (e.g. retry after 1s, 2s, 4s + random jitter)", "Show non-intrusive offline banners and queue write actions locally"], ["Exponential backoff with jitter", "NWPathMonitor"]],
  ["Mobile App Security: Reverse Engineering Defenses", "Security", "Advanced", "technical", "How do you protect a production mobile application against tampering, reverse engineering, and jailbreak/root?", ["Mobile Security"], ["Code obfuscation using ProGuard/R8 (Android) or DexGuard to make decompiled source unreadable", "Root / Jailbreak detection checks inspecting file system for binaries (su, Cydia, substrate)", "Integrity checks (Google Play Integrity API / Apple DeviceCheck) verifying app binary was not modified and was downloaded from official app store"], ["Play Integrity API", "Root detection"]],
  ["GraphQL in Mobile Applications", "APIs", "Intermediate", "technical", "What are the advantages of using GraphQL (Apollo Client) over REST for mobile networking?", ["GraphQL", "Networking"], ["Eliminates over-fetching (mobile only downloads exact fields requested, saving bandwidth and battery)", "Eliminates under-fetching (single GraphQL query fetches user, orders, and products, avoiding multiple round-trips over high-latency cellular networks)", "Apollo Client provides normalized client-side caching out of the box"], ["Apollo Client", "Query batching"]],
  ["Background Fetch & Background Processing", "Background Processing", "Intermediate", "technical", "How do you schedule periodic background data synchronization without getting terminated by the OS?", ["Background Processing"], ["Android: WorkManager schedules deferrable guaranteed background tasks respecting Doze mode and battery constraints", "iOS: BGTaskScheduler (BGAppRefreshTask / BGProcessingTask) allows OS to determine optimal execution window based on user habits and battery status", "Background execution duration is strictly limited (typically 30 seconds)"], ["WorkManager", "BGTaskScheduler"]],
  ["Smooth Scrolling & 60/120fps UI Performance", "Performance", "Intermediate", "practical", "How do you eliminate dropped frames (jank) in long scrolling lists (RecyclerView, FlatList)?", ["UI Performance"], ["Keep view hierarchy shallow and avoid complex layout nesting", "Recycle list items efficiently; do not perform heavy calculations or object allocations inside onBindViewHolder / renderItem", "Offload image decoding and JSON parsing to background threads; keep main UI thread free"], ["Systrace / CPU Profiler", "FlatList optimization"]],
  ["Feature Flags & Remote Config", "Deployment", "Easy", "technical", "How do you use Remote Config (Firebase) and Feature Flags in mobile release management?", ["Feature Flags", "Remote Config"], ["Dynamically toggle features on/off or change parameters without publishing a new app update to app stores", "Gradual percentage rollouts to monitor crash rates before 100% rollout", "Instant kill-switch to disable buggy features immediately in production"], ["Kill-switch", "A/B testing"]],
  ["Crash Reporting & Symbolication", "Observability", "Easy", "technical", "How does crash reporting work in mobile apps (Firebase Crashlytics) and what is dSYM / mapping.txt symbolication?", ["Crashlytics", "Observability"], ["Crashlytics intercepts unhandled exceptions and native signal crashes, saving stack trace to disk before app dies", "Production binaries are compiled with obfuscation and stripped symbols; stack traces show cryptic memory addresses or obfuscated names", "dSYM files (iOS) and ProGuard mapping.txt (Android) de-obfuscate stack traces into human-readable class names and file line numbers"], ["dSYM files", "ProGuard mapping.txt"]],
  ["WebSocket Real-Time Features in Mobile", "Real-Time", "Intermediate", "technical", "How do you maintain a persistent WebSocket connection in a mobile app when the app transitions between foreground and background?", ["WebSockets", "Mobile"], ["Close WebSocket connection or send disconnect frame when app moves to background to save battery", "On app returning to foreground, check network reachability and automatically re-establish connection", "Use Push Notifications for background alerts instead of keeping alive a permanent WebSocket connection in background"], ["Reconnect logic", "Heartbeat ping/pong"]],
  ["Mobile App Internationalization & RTL", "Localization", "Easy", "practical", "How do you support Right-to-Left (RTL) languages (Arabic, Hebrew) in mobile layouts?", ["Localization", "RTL"], ["Use directional layout constraints: start and end instead of left and right (e.g. paddingStart, MarginEnd)", "Ensure icons indicating direction (back arrows, progress indicators) mirror automatically in RTL mode", "Test UI layout mirroring using pseudolocales or switching device language"], ["Start/End constraints", "Mirroring icons"]],
  ["Handling Deep Link Routing with Complex Navigation", "Navigation", "Intermediate", "scenario", "A user taps a deep link to an order detail screen when the app is completely closed. How do you construct the back-stack?", ["Navigation", "Deep Linking"], ["Do not open the target detail screen in isolation without navigation history (pressing back shouldn't exit the app)", "Use Android Navigation Component / Jetpack Navigation or iOS Coordinator pattern to synthesize the back stack (Home -> Orders List -> Order Details)", "Allows user to navigate back up the application hierarchy naturally"], ["Synthetic back stack", "Coordinator pattern"]],
  ["Mobile App Submission & Review Process", "App Store", "Easy", "technical", "What common rejection reasons do apps encounter during Apple App Store and Google Play reviews?", ["App Store Guidelines"], ["Crashes or bugs during reviewer testing on latest OS versions / iPads", "Missing Privacy Policy, incomplete Data Safety / Privacy Nutrition labels, or requesting unnecessary permissions", "Violating in-app purchase guidelines by offering external payment links for digital goods", "Placeholder content, broken links, or non-functional login credentials provided in review notes"], ["App Store Review Guidelines", "Data Safety labels"]],
  ["End-to-End Mobile App Experience", "Project Experience", "Intermediate", "behavioral", "Describe a mobile app you architected and deployed to Google Play and Apple App Store.", ["Project Experience", "Communication"], ["App domain, architectural pattern (MVVM, Clean Architecture, BLoC), and tech stack rationale", "Key technical challenges solved (offline sync, complex animations, camera/sensors integration)", "Performance optimization results, crash-free user rate (>99.5%), and app store ratings"], ["Crash-free rate", "App store release"]],
  ["Debugging Production Mobile Crashes", "Troubleshooting", "Intermediate", "behavioral", "Describe a critical production crash reported in Firebase Crashlytics that you diagnosed and fixed.", ["Troubleshooting", "Crashlytics"], ["Analyzing crash stack traces and identifying affected device models, OS versions, and user reproduction steps", "Isolating root cause (null pointer, threading race condition, out-of-memory)", "Releasing expedited hotfix and adding automated unit/UI tests to prevent regression"], ["Hotfix release", "Root cause analysis"]],
  ["Future of Mobile Development", "Modern Trends", "Easy", "technical", "How are declarative UI frameworks (Jetpack Compose and SwiftUI) replacing legacy imperative UI paradigms?", ["Jetpack Compose", "SwiftUI"], ["Declarative UI: developers describe WHAT the UI should look like for a given state; framework automatically updates UI when state changes", "Eliminates imperative DOM-like manipulation (findViewById, setText, setVisibility, XML layouts, Storyboards)", "Recomposition / reactive view updates provide cleaner code, fewer state bugs, and instant live previews"], ["Declarative UI", "Recomposition"]]
];

const mobileQuestions = mobileTopics.map((t, idx) => ({
  id: `mob-${String(idx + 1).padStart(3, '0')}`,
  role: "Mobile App Developer",
  category: t[1],
  difficulty: t[2],
  format: t[3],
  question: t[4],
  expectedSkills: t[5],
  evaluationPoints: t[6],
  followUpTopics: t[7]
}));
save('mobileAppDeveloper.ts', 'MOBILE_APP_DEVELOPER_QUESTIONS', mobileQuestions);
