const fs = require('fs');
const path = require('path');
const targetDir = 'C:/sih/src/data/interviewQuestions/banks';

function save(filename, exportName, questions) {
  const code = `import { RoleQuestion } from '../types';\n\nexport const ${exportName}: RoleQuestion[] = ${JSON.stringify(questions, null, 2)};\n`;
  fs.writeFileSync(path.join(targetDir, filename), code, 'utf-8');
  console.log(`✓ ${filename} written (${questions.length} questions)`);
}

const dbTopics = [
  ["Database Normalization 1NF to BCNF", "Database Design", "Easy", "technical", "Explain 1NF, 2NF, 3NF, and BCNF with concrete database table examples.", ["Database Design", "Normalization"], ["1NF: atomic values, no repeating groups, unique primary key", "2NF: in 1NF and no partial dependencies on composite primary key", "3NF: in 2NF and no transitive dependencies", "BCNF: in 3NF and for every functional dependency X -> Y, X must be a superkey"], ["Denormalization trade-offs", "Data redundancy"]],
  ["Clustered vs Non-Clustered Indexes", "Indexing", "Easy", "technical", "What is the physical storage difference between a clustered index and a non-clustered index?", ["Indexing", "Storage"], ["Clustered index defines the physical order of data rows on disk (only 1 per table, usually PK)", "Non-clustered index is a separate B-tree structure holding index keys and pointers to the physical data rows", "Covering index includes all columns needed by query to avoid table lookups"], ["B-Tree structure", "Index seek vs index scan"]],
  ["ACID Properties & Crash Recovery", "Transactions", "Intermediate", "technical", "Explain ACID transaction properties and how Write-Ahead Logging (WAL) ensures Durability and Atomicity.", ["ACID", "Transactions"], ["Atomicity: all changes commit or all rollback", "Consistency: valid database constraints maintained", "Isolation: concurrent transactions do not interfere", "Durability: committed transactions survive server crashes via WAL logging to disk before writing to data pages"], ["WAL (Write-Ahead Log)", "Two-Phase Commit"]],
  ["Transaction Isolation Levels", "Transactions", "Advanced", "technical", "Compare Read Uncommitted, Read Committed, Repeatable Read, and Serializable isolation levels.", ["Transactions", "Concurrency"], ["Read Uncommitted allows Dirty Reads (reading uncommitted data)", "Read Committed prevents Dirty Reads but allows Non-Repeatable Reads", "Repeatable Read prevents Non-Repeatable Reads but may allow Phantom Reads", "Serializable prevents Phantom Reads using range locks or MVCC serializable snapshot isolation"], ["MVCC", "Dirty reads vs Phantom reads"]],
  ["Multi-Version Concurrency Control (MVCC)", "Concurrency", "Advanced", "technical", "How does MVCC allow PostgreSQL to achieve high concurrency without readers blocking writers?", ["PostgreSQL", "MVCC"], ["Each transaction sees a snapshot of data at a specific point in time", "Updates create new row versions (tuples) with xmin and xmax transaction IDs instead of overwriting existing rows", "Readers never block writers and writers never block readers"], ["VACUUM in PostgreSQL", "Transaction ID wraparound"]],
  ["Stored Procedures vs Functions", "Programmability", "Easy", "technical", "What is the functional and operational difference between a Stored Procedure and a User-Defined Function (UDF)?", ["SQL", "Stored Procedures"], ["Functions must return a value, cannot commit/rollback transactions, and can be used in SELECT statements", "Stored Procedures do not require a return value, can execute transactions (COMMIT/ROLLBACK), and are executed using CALL/EXEC", "Procedures are used for business workflow; functions for computations"], ["Deterministic functions", "Table-valued functions"]],
  ["Database Triggers & Trade-Offs", "Programmability", "Intermediate", "technical", "What are database triggers (BEFORE, AFTER, INSTEAD OF) and what are their architectural drawbacks?", ["Triggers", "Architecture"], ["Execute automatically in response to DML operations (INSERT, UPDATE, DELETE)", "BEFORE triggers validate/modify data before commit; INSTEAD OF triggers update complex views", "Drawbacks: hidden side-effects, difficult debugging, performance overhead during bulk operations"], ["Audit logging triggers", "Recursive triggers"]],
  ["Materialized Views vs Views", "Database Design", "Intermediate", "technical", "Compare standard Views vs Materialized Views. When do you use a Materialized View?", ["Views", "Performance"], ["Standard View is a stored virtual query executed dynamically on every call", "Materialized View physically computes and persists query results to disk, acting like a table with its own indexes", "Use Materialized Views for expensive aggregate analytics, refreshing periodically"], ["REFRESH MATERIALIZED VIEW CONCURRENTLY", "Query rewrite"]],
  ["Composite Index Column Order", "Indexing", "Intermediate", "technical", "Why does column ordering matter in a composite index (columnA, columnB) and what is the Leftmost Prefix rule?", ["Indexing", "Query Optimization"], ["Index can satisfy queries filtering on (columnA) or (columnA, columnB)", "Index cannot be used for queries filtering only on (columnB) without columnA (leftmost prefix rule)", "Put high-cardinality equality columns first, followed by range/sort columns"], ["Leftmost prefix", "Covering index"]],
  ["Query Execution Plans (EXPLAIN)", "Performance Tuning", "Intermediate", "practical", "How do you read and interpret an EXPLAIN ANALYZE output in PostgreSQL or MySQL?", ["Query Optimization", "EXPLAIN"], ["Check scan type: Sequential/Table Scan vs Index Scan vs Index Only Scan", "Compare estimated cost vs actual execution time and rows returned", "Identify expensive operations: Nested Loop, Hash Join, Sort, and HashAggregate"], ["Buffers hit ratio", "Query planner statistics"]],
  ["Deadlocks: Detection & Prevention", "Concurrency", "Advanced", "scenario", "Two concurrent transactions produce a deadlock in your database. How do you identify, resolve, and prevent it?", ["Concurrency", "Deadlocks"], ["Database engine detects circular lock dependencies and aborts one transaction (deadlock victim)", "Analyze deadlock logs to see queries and locked rows involved", "Prevention: always access tables and rows in the exact same deterministic order across transactions; keep transactions short"], ["Lock escalation", "SELECT FOR UPDATE"]],
  ["Database Sharding vs Partitioning", "Scalability", "Advanced", "technical", "Compare table partitioning (vertical/horizontal) on a single database vs horizontal database sharding.", ["Scalability", "Architecture"], ["Table partitioning divides a huge table into smaller physical partitions on the same DB instance (e.g. partition by month/range)", "Sharding distributes partitions across multiple independent database nodes/servers based on a shard key", "Sharding scales writes and storage horizontally across machines but complicates cross-shard queries and joins"], ["Range vs Hash partitioning", "Shard key selection"]],
  ["B-Tree vs Hash vs GIN Indexes", "Indexing", "Intermediate", "technical", "Compare B-Tree, Hash, and GIN (Generalized Inverted) indexes in PostgreSQL.", ["Indexing", "PostgreSQL"], ["B-Tree: balanced tree supporting equality and range queries (<, <=, =, >=, >) and sorting (default)", "Hash: supports exact equality lookup only (=)", "GIN: inverted index mapping elements inside composite items (JSONB, array columns, full-text search) to matching rows"], ["GiST indexes", "JSONB indexing"]],
  ["Primary Keys vs Natural Keys vs UUIDs", "Database Design", "Intermediate", "technical", "Compare auto-incrementing integer surrogate keys vs natural keys vs UUIDs as primary keys.", ["Database Design"], ["Auto-increment int: compact, fast sequential inserts in B-tree, but exposes record count and conflicts in distributed databases", "Natural key: avoids extra column, but changes in real-world data break foreign key relationships", "UUIDv4: globally unique, distributed friendly, but random order causes B-tree page splits and index fragmentation; UUIDv7 provides time-ordered clustering"], ["UUIDv7", "B-tree page splits"]],
  ["Foreign Keys & Referential Actions", "Data Integrity", "Easy", "technical", "Explain ON DELETE CASCADE, SET NULL, RESTRICT, and NO ACTION referential actions in foreign keys.", ["Foreign Keys", "Data Integrity"], ["CASCADE: deleting parent row automatically deletes all related child rows", "SET NULL: deleting parent sets child foreign key to NULL (requires nullable column)", "RESTRICT: immediately prevents deletion of parent if child rows exist", "NO ACTION: defers constraint check to end of transaction"], ["Deferred constraints", "Cascading updates"]],
  ["Connection Pooling & pgBouncer", "Architecture", "Intermediate", "technical", "Why is an external connection pooler like pgBouncer necessary for PostgreSQL at scale?", ["PostgreSQL", "pgBouncer"], ["PostgreSQL uses process-per-connection model; high connection counts consume substantial RAM and cause context switching", "pgBouncer pools connections using Transaction or Session pooling, handling thousands of client connections with small backend pool", "Eliminates connection setup overhead and protects database from connection exhaustion"], ["Transaction pooling mode", "Max connections limit"]],
  ["Query Optimization: Eliminating Subqueries", "Optimization", "Intermediate", "practical", "How do you refactor an inefficient correlated subquery with an EXISTS or JOIN clause?", ["SQL Optimization"], ["Correlated subqueries evaluate for every row of outer table (O(N*M))", "Refactor using INNER/LEFT JOIN with GROUP BY or an EXISTS clause", "Allows query optimizer to use hash joins or merge joins instead of nested loops"], ["EXISTS vs IN", "Window function refactoring"]],
  ["Optimistic vs Pessimistic Locking", "Concurrency", "Intermediate", "technical", "When should you implement Optimistic Locking using a version column vs Pessimistic Locking (SELECT FOR UPDATE)?", ["Concurrency", "Locking"], ["Optimistic locking checks version column before commit; fails on collision (ideal for read-heavy low contention)", "Pessimistic locking takes exclusive row lock in database (SELECT FOR UPDATE) preventing concurrent access (ideal for high-contention financial transactions)", "Optimistic avoids database locks; pessimistic avoids rollbacks and retries"], ["SELECT FOR UPDATE NOWAIT", "Retry logic"]],
  ["Database Migrations in Production", "DevOps", "Intermediate", "technical", "How do you execute zero-downtime database schema migrations for tables with 50 million rows?", ["Migrations", "High Availability"], ["Avoid blocking DDL locks (e.g. adding column with default in older engines locks table)", "Use Expand-and-Contract (Parallel Run) pattern: add new nullable column, backfill asynchronously in batches, switch application, drop old column", "Create indexes concurrently (CREATE INDEX CONCURRENTLY in Postgres)"], ["Expand and contract", "pt-online-schema-change"]],
  ["High Availability & Replication", "High Availability", "Intermediate", "technical", "Compare synchronous vs asynchronous database replication. What is split-brain in failover?", ["Replication", "High Availability"], ["Synchronous guarantees zero data loss (commits wait for replica ack) at the cost of write latency", "Asynchronous returns immediately after local commit, replicating in background (low latency, but replica lag means risk of data loss on sudden primary crash)", "Split-brain occurs when network partition causes two nodes to both believe they are primary writer"], ["RPO / RTO", "Quorum consensus"]],
  ["VACUUM & Table Bloat in PostgreSQL", "PostgreSQL", "Advanced", "technical", "What is table bloat in PostgreSQL and how does Auto-VACUUM reclaim disk space from dead tuples?", ["PostgreSQL", "Storage"], ["MVCC updates/deletes leave dead tuples on disk pages until cleaned up", "VACUUM marks dead tuple space as reusable for future inserts without shrinking file size", "VACUUM FULL rewrites entire table to reclaim disk space to OS, but takes an exclusive lock blocking reads and writes"], ["Auto-vacuum tuning", "pg_repack"]],
  ["Database Backup & Point-in-Time Recovery", "Disaster Recovery", "Intermediate", "technical", "How does Point-in-Time Recovery (PITR) work using base backups and WAL archives?", ["Backup", "Disaster Recovery"], ["Restore consistent physical base backup taken at earlier date", "Replay WAL (Write-Ahead Log) segments forward continuously up to exact target timestamp", "Allows recovery to precise minute before an accidental DROP TABLE command"], ["pg_dump vs physical backup", "WAL archiving"]],
  ["Temporal Tables & Historical Tracking", "Data Modeling", "Intermediate", "technical", "How do you design an audit history table using SQL temporal tables or SCD Type 2?", ["Data Modeling", "Audit"], ["SCD Type 2 tracks historical states using effective_start_date, effective_end_date, and is_current boolean flag", "System-versioned temporal tables in SQL Server/Postgres automatically record row history on updates and deletes", "Enables point-in-time historical queries: AS OF SYSTEM TIME"], ["SCD Type 2", "Audit triggers"]],
  ["Denormalization Strategies", "Performance Tuning", "Intermediate", "technical", "When is intentional database denormalization justified, and how do you maintain data consistency?", ["Database Design", "Performance"], ["Justified for read-heavy reporting where multi-table joins create severe latency bottlenecks", "Pre-aggregate summary counts and totals into parent tables", "Maintain consistency using application transactions, event listeners, or database triggers"], ["Star schema", "Pre-computed aggregates"]],
  ["Database Security & SQL Injection", "Security", "Easy", "technical", "How do prepared statements and parameterized queries prevent SQL injection at the database protocol level?", ["Security", "SQL Injection"], ["Prepared statement separates SQL code structure from user parameter data", "Database engine compiles and optimizes the query template AST before binding parameters", "User input is treated strictly as literal scalar values, never executed as SQL code"], ["Principle of least privilege", "Row-level security"]],
  ["Row-Level Security (RLS)", "Security", "Intermediate", "technical", "What is Row-Level Security (RLS) in PostgreSQL and how is it used in multi-tenant SaaS architectures?", ["PostgreSQL", "Security"], ["Enforces fine-grained row access policies directly inside the database engine", "Restricts SELECT, INSERT, UPDATE, DELETE rows based on current session user/tenant context", "Guarantees Tenant A cannot read Tenant B data even if application query forgets WHERE tenant_id clause"], ["Multi-tenant architecture", "Postgres current_setting"]],
  ["Full-Text Search in SQL", "Search", "Intermediate", "technical", "How do you implement full-text search in PostgreSQL using tsvector, tsquery, and GIN indexes?", ["PostgreSQL", "Full-Text Search"], ["to_tsvector tokenizes and stems text into lexemes with positions", "to_tsquery parses search query with boolean operators (&, |, !)", "GIN index on tsvector column provides lightning-fast sub-second search across millions of documents"], ["Stemming and stop words", "ts_rank for search relevance"]],
  ["JSONB in Relational Databases", "Modern SQL", "Intermediate", "technical", "When should you store data in a JSONB column in PostgreSQL vs creating structured relational tables?", ["JSONB", "PostgreSQL"], ["JSONB stores binary decomposed JSON with indexing support (GIN)", "Use for: semi-structured schema-less attributes, user custom fields, and third-party API payloads", "Use relational tables for: core domain entities, foreign key referential integrity, and frequently filtered/joined metrics"], ["GIN index on JSONB", "JSON operators (->, ->>)"]],
  ["Database Benchmarking with pgbench", "Performance", "Intermediate", "practical", "How do you benchmark database transaction throughput (TPS) and latency using pgbench or sysbench?", ["Performance", "Benchmarking"], ["Initialize test schema and scaling factor (pgbench -i -s 100)", "Run simulated concurrent client connections (pgbench -c 50 -j 4 -T 60)", "Measure Transactions Per Second (TPS), average latency, and connection scaling curves under read vs write workloads"], ["TPS measurement", "Scaling factor"]],
  ["Graph Databases vs Relational for Hierarchies", "NoSQL", "Intermediate", "technical", "Why are Graph Databases (Neo4j) superior to Relational SQL for deep hierarchical relationship traversals?", ["Graph Databases", "Architecture"], ["Relational databases require recursive CTEs or expensive multi-level self-joins (O(N^d) explosion)", "Graph databases use index-free adjacency: vertices hold direct physical pointers to adjacent vertices (O(1) pointer hop)", "Ideal for social networks, fraud rings, and dependency trees"], ["Neo4j", "Cypher query language"]],
  ["Database Profiling & Performance Audit", "Performance Tuning", "Intermediate", "scenario", "Your primary database CPU is pegged at 100%. Walk me through your immediate triage process.", ["Troubleshooting", "PostgreSQL"], ["Query pg_stat_activity to find currently running long queries and lock waits", "Terminate or cancel runaway long-running queries (pg_cancel_backend)", "Inspect slow query log / pg_stat_statements to identify top queries by total execution time and missing indexes"], ["pg_stat_statements", "Canceling runaway queries"]],
  ["Replication Lag Troubleshooting", "Replication", "Intermediate", "scenario", "An asynchronous read replica is lagging by 30 minutes. What causes replication lag and how do you fix it?", ["Replication", "Troubleshooting"], ["Causes: massive batch write operations on primary, slow disk I/O on replica, network bandwidth saturation, long-running read query blocking WAL replay on replica", "Fix: break bulk writes into small chunks, increase replica hardware resources, tune max_standby_streaming_delay"], ["WAL streaming", "Standby conflict delay"]],
  ["Complex Schema Design Experience", "Project Experience", "Intermediate", "behavioral", "Describe a complex database schema you designed. How did you normalize and index it for performance?", ["Database Design", "Communication"], ["Business domain and relationship modeling (1-to-many, many-to-many)", "Normalization decisions and intentional denormalization points", "Indexing strategy, constraint design, and scalability results"], ["Foreign key modeling", "Lessons learned"]],
  ["Working with Application Developers", "Behavioral", "Easy", "behavioral", "How do you educate software developers to write clean, performant SQL and avoid N+1 queries?", ["Collaboration", "Mentorship"], ["Conduct SQL code reviews and share EXPLAIN query execution plan insights", "Provide reusable DTO projection patterns and repository guidelines", "Set up slow query alerts and automated PR query linting in CI"], ["Code reviews", "SQL best practices"]],
  ["Future of Databases (HTAP & NewSQL)", "Modern Trends", "Advanced", "technical", "What is NewSQL (e.g. CockroachDB, Google Spanner) and how does it combine ACID with horizontal scale?", ["NewSQL", "Distributed Databases"], ["Combines strict ACID transactional consistency of traditional RDBMS with horizontal scaling of NoSQL", "Uses distributed consensus algorithms (Raft, Paxos) and atomic synchronized clocks (TrueTime)", "Allows seamless sharding and multi-region active-active deployment without manual sharding logic"], ["Raft consensus", "Google Spanner TrueTime"]]
];

const dbQuestions = dbTopics.map((t, idx) => ({
  id: `dbdev-${String(idx + 1).padStart(3, '0')}`,
  role: "Database Developer",
  category: t[1],
  difficulty: t[2],
  format: t[3],
  question: t[4],
  expectedSkills: t[5],
  evaluationPoints: t[6],
  followUpTopics: t[7]
}));
save('databaseDeveloper.ts', 'DATABASE_DEVELOPER_QUESTIONS', dbQuestions);
