const fs = require('fs');
const path = require('path');
const targetDir = 'C:/sih/src/data/interviewQuestions/banks';

function save(filename, exportName, questions) {
  const code = `import { RoleQuestion } from '../types';\n\nexport const ${exportName}: RoleQuestion[] = ${JSON.stringify(questions, null, 2)};\n`;
  fs.writeFileSync(path.join(targetDir, filename), code, 'utf-8');
  console.log(`✓ ${filename} written (${questions.length} questions)`);
}

const autoTopics = [
  ["Page Object Model (POM)", "Automation Architecture", "Easy", "technical", "Explain the Page Object Model (POM) design pattern and its advantages in UI automation.", ["POM", "Design Patterns"], ["Each web page is represented by a class containing elements and user action methods", "Tests interact with methods, not raw locators, reducing code duplication", "Changes to UI require updating locator in one single class rather than hundreds of tests"], ["PageFactory vs By locators", "Fluent Page Object Model"]],
  ["Implicit vs Explicit vs Fluent Wait", "Selenium WebDriver", "Intermediate", "technical", "Compare Implicit Wait, Explicit Wait, and Fluent Wait in Selenium WebDriver.", ["Selenium", "Synchronization"], ["Implicit Wait sets global timeout for all element lookups in WebDriver instance", "Explicit Wait halts execution until specific ExpectedCondition is met for a single element (e.g. elementToBeClickable)", "Fluent Wait defines polling frequency and exceptions to ignore (NoSuchElementException) while waiting"], ["WebDriverWait", "Thread.sleep anti-pattern"]],
  ["Selenium Locators Priority", "Selenium WebDriver", "Easy", "technical", "Rank Selenium locators by reliability and speed: ID, Name, CSS Selector, XPath, Class.", ["Selenium Locators"], ["ID is fastest and most reliable when unique", "Name and CSS Selectors are fast and readable", "XPath is versatile (traversing parent, ancestor, following-sibling) but slower", "Class Name is prone to brittle changes in responsive CSS"], ["Relative XPath vs Absolute XPath", "Dynamic locators"]],
  ["Handling StaleElementReferenceException", "Selenium WebDriver", "Intermediate", "technical", "What causes StaleElementReferenceException in Selenium and how do you resolve it?", ["Selenium", "Troubleshooting"], ["Element was found in DOM earlier, but page refreshed or DOM was updated by JavaScript, detaching element", "Resolutions: re-locating the element right before interaction, or using retry loops with try-catch", "Explicit wait with ExpectedConditions.stalenessOf or refetching via By locator"], ["DOM detachment", "Dynamic single page apps"]],
  ["Selenium vs Playwright vs Cypress", "Tooling", "Intermediate", "technical", "Compare Selenium, Cypress, and Playwright for modern web test automation.", ["Playwright", "Cypress", "Selenium"], ["Selenium: mature standard using W3C WebDriver protocol, multi-language, supports all browsers", "Cypress: runs directly inside browser event loop, excellent dev experience, but limited multi-tab/iframe support", "Playwright: uses Chrome DevTools Protocol / WebSockets, ultra-fast, multi-tab, multi-browser, native auto-waiting"], ["Headless execution", "DevTools Protocol"]],
  ["TestNG vs JUnit Framework", "Test Frameworks", "Easy", "technical", "Compare TestNG and JUnit 5 for test execution management and reporting.", ["TestNG", "JUnit 5"], ["TestNG provides powerful XML suite configuration, group dependencies, and parallel execution by default", "JUnit 5 provides modern architecture, extensions, dynamic tests, and nested tests", "Both support annotations (@Test, @BeforeMethod, @DataProvider)"], ["TestNG DataProvider", "Parallel test execution"]],
  ["Data-Driven Testing Framework", "Framework Architecture", "Intermediate", "technical", "How do you design a Data-Driven test automation framework reading from Excel or JSON?", ["Data-Driven Testing", "Frameworks"], ["Separate test logic from test data sets", "Use Apache POI to read Excel or Jackson to parse JSON into Java POJOs", "Feed data into tests using TestNG @DataProvider or JUnit @ParameterizedTest"], ["Apache POI", "DataProvider"]],
  ["Automating API Tests with RestAssured", "API Automation", "Intermediate", "practical", "Write a RestAssured test in Java that sends a POST request with JSON and validates HTTP 201 and response field.", ["RestAssured", "API Testing"], ["given().contentType(ContentType.JSON).body(payload)", "when().post('/api/v1/users')", "then().statusCode(201).body('name', equalTo('John'))"], ["Hamcrest matchers", "Schema validation"]],
  ["Handling Shadow DOM and iFrames", "Selenium WebDriver", "Intermediate", "technical", "How do you locate and interact with elements inside iFrames and Shadow DOM in Selenium?", ["Selenium", "Advanced Locators"], ["iFrames: driver.switchTo().frame(frameElement); must switch back with defaultContent()", "Shadow DOM: driver.findElement(By.cssSelector('host')).getShadowRoot() in Selenium 4", "Playwright Pierces shadow DOM automatically without special syntax"], ["getShadowRoot", "Nested iframes"]],
  ["Headless Browser Testing in CI", "CI/CD", "Easy", "technical", "What is Headless browser testing and why is it standard in CI/CD build agents?", ["Headless Browsers", "CI/CD"], ["Runs browser without graphical display UI, saving significant CPU and RAM", "Runs seamlessly on headless Linux container agents (Docker, GitHub Actions)", "Much faster execution for large regression suites"], ["ChromeOptions --headless=new", "Xvfb virtual display"]],
  ["Cross-Browser Testing with Selenium Grid", "Selenium Grid", "Intermediate", "technical", "How does Selenium Grid 4 distribute test execution across multiple nodes and browsers?", ["Selenium Grid"], ["Hub (Router, Distributor, Session Queue) routes incoming sessions to available Node instances", "Nodes run target browsers on specific OS platforms (Chrome on Linux, Safari on Mac)", "Supports standalone, hub-and-node, and fully distributed microservice deployment modes"], ["Docker Selenium Grid", "Cloud test grids"]],
  ["Handling File Uploads in Automation", "Selenium WebDriver", "Easy", "practical", "How do you automate file uploads when the browser file picker dialog opens?", ["Selenium"], ["Send the absolute file path directly to the input element: driver.findElement(By.xpath('//input[@type=\"file\"]')).sendKeys('/path/to/file')", "Avoid OS-level file dialogs which Selenium cannot interact with natively", "Use Robot class or AutoIT only if input type=file is strictly not available in DOM"], ["Input type=file", "Robot class"]],
  ["Handling JavaScript Alerts & Popups", "Selenium WebDriver", "Easy", "technical", "How do you handle browser JavaScript alerts, prompts, and confirmation dialogs in Selenium?", ["Selenium"], ["driver.switchTo().alert() switches context to active JS modal", "alert.accept() clicks OK; alert.dismiss() clicks Cancel", "alert.sendKeys('text') enters input into prompt dialog; alert.getText() reads alert message"], ["Modal dialogs vs JS alerts", "Unclosed alert exceptions"]],
  ["Automating Window Handles / Multiple Tabs", "Selenium WebDriver", "Easy", "practical", "How do you switch between multiple browser tabs or popup windows in Selenium?", ["Selenium"], ["driver.getWindowHandle() gets current window ID; driver.getWindowHandles() returns Set of all open window IDs", "Loop through Set and call driver.switchTo().window(handle) to switch focus", "driver.close() closes active tab; driver.switchTo().window(parentHandle) returns to original tab"], ["Window handles", "Popup windows"]],
  ["Action Class & Complex Mouse Interactions", "Selenium WebDriver", "Intermediate", "practical", "How do you automate drag-and-drop, mouse hover, and double-click using Selenium Actions class?", ["Selenium Actions"], ["Actions actions = new Actions(driver)", "actions.moveToElement(element).perform() for hover", "actions.dragAndDrop(source, target).perform() or clickAndHold + moveToElement + release", "Always invoke .build().perform() to execute composite action chains"], ["Keyboard shortcuts", "Context click (right-click)"]],
  ["Executing JavaScript with JavascriptExecutor", "Selenium WebDriver", "Intermediate", "practical", "When must you use JavascriptExecutor in Selenium and give examples of scrolling and clicking.", ["JavascriptExecutor"], ["When native click fails due to ElementClickInterceptedException or element is hidden", "JavascriptExecutor js = (JavascriptExecutor) driver; js.executeScript('arguments[0].click();', element);", "Scrolling into view: js.executeScript('arguments[0].scrollIntoView(true);', element);"], ["Scrolling to bottom", "Overcoming click intercepts"]],
  ["BDD Framework with Cucumber and Java", "BDD", "Intermediate", "technical", "Explain Feature files, Step Definitions, and TestRunner in a Cucumber BDD framework.", ["Cucumber", "BDD"], ["Feature file contains Gherkin scenarios (Given, When, Then)", "Step Definition class implements Java methods annotated with regex matching Gherkin steps", "TestRunner class (using @RunWith(Cucumber.class) or AbstractTestNGCucumberTests) orchestrates suite execution and reporting"], ["Cucumber Hooks (@Before, @After)", "Scenario Outline and Examples"]],
  ["Visual Regression Testing", "Visual Testing", "Intermediate", "technical", "How does automated Visual Regression Testing work (e.g. Percy, Applitools Eyes)?", ["Visual Testing"], ["Captures DOM and visual pixel screenshots across screen sizes and browsers", "Compares screenshot against approved baseline snapshot using computer vision algorithms", "Flags unexpected pixel shifts, color changes, and layout overflow before production deploy"], ["Baseline comparison", "Applitools AI vision"]],
  ["Reporting with Allure Reports", "Reporting", "Easy", "technical", "How do you generate comprehensive execution reports with screenshots on failure using Allure?", ["Reporting", "Allure"], ["Integrate Allure TestNG/JUnit listener into build file (pom.xml)", "Implement TestListener (onTestFailure) to capture screenshot as byte array and attach with @Attachment", "Generates interactive HTML dashboard with test trends, logs, severity, and failure categorization"], ["ExtentReports", "CI report publishing"]],
  ["API Schema Validation in RestAssured", "API Automation", "Intermediate", "practical", "How do you validate JSON Schema compliance in RestAssured to catch API contract breaking changes?", ["RestAssured", "JSON Schema"], ["given().get('/api/users').then().assertThat().body(matchesJsonSchemaInClasspath('user-schema.json'))", "Validates that all required fields, data types, and enum values conform to published API contract", "Catches missing fields or type drift without writing dozens of individual field assertions"], ["JSON Schema Draft 7", "Contract testing"]],
  ["Parallel Test Execution & Thread Safety", "Framework Architecture", "Advanced", "technical", "How do you ensure ThreadSafety in an automation framework running tests in parallel?", ["Concurrency", "ThreadSafety"], ["Use ThreadLocal<WebDriver> to ensure each concurrent test thread gets its own isolated browser instance", "Never declare WebDriver as static without ThreadLocal wrapping", "Configure thread count in testng.xml or surefire maven plugin (parallel='methods' thread-count='4')"], ["ThreadLocal WebDriver", "Maven Surefire parallel"]],
  ["Testing Shadow DOM in Modern Web Apps", "Advanced Locators", "Intermediate", "technical", "Why can't standard XPath find elements inside a closed or open Shadow DOM?", ["Shadow DOM", "Web Standards"], ["Shadow DOM encapsulates internal DOM tree from outer document; standard XPath engine cannot cross shadow boundary", "Open shadow DOM can be traversed using JavaScript or CSS selectors with shadowRoot.querySelector()", "Closed shadow DOM blocks external programmatic access entirely"], ["Open vs Closed Shadow DOM", "CSS ::part selector"]],
  ["Automating Mobile Apps with Appium", "Mobile Automation", "Intermediate", "technical", "How does Appium automate native iOS and Android apps using the WebDriver protocol?", ["Appium", "Mobile Automation"], ["Appium server receives standard W3C WebDriver commands and translates them to vendor automation frameworks", "Uses UiAutomator2 for Android and XCUITest for iOS", "Same test scripts can run cross-platform on real devices and emulators"], ["Appium Inspector", "DesiredCapabilities"]],
  ["Hybrid Framework Architecture", "Framework Design", "Intermediate", "technical", "What components make up a scalable, enterprise-grade Hybrid Test Automation Framework?", ["Framework Design"], ["Base Test setup/teardown with ThreadLocal WebDriver", "Page Object Model layer encapsulating application pages", "Utilities: Excel/JSON data readers, dynamic wait helpers, and config managers", "Reporting: Allure/Extent reports with failure screenshots, integrated into CI/CD"], ["Config.properties reader", "Maven dependency management"]],
  ["Handling CAPTCHA and OTP in Automation", "Testing Strategy", "Intermediate", "technical", "How do you handle CAPTCHA, 2FA, and OTP challenges during automated test runs?", ["Test Strategy", "Security"], ["CAPTCHAs are designed to block automation; disable CAPTCHA in staging/test environments", "Use static test accounts with fixed bypass OTP codes (e.g. 123456) in non-production", "Or generate TOTP tokens programmatically using an authenticator library with secret key"], ["Bypass headers", "TOTP generation"]],
  ["Mocking Backend APIs for UI Testing", "UI Testing", "Intermediate", "technical", "Why is network mocking useful during frontend UI automation and how does Playwright support it?", ["Playwright", "Mocking"], ["Isolates UI tests from backend instability, rate limits, and missing test data", "Playwright's page.route() intercepts network requests and returns mock JSON responses instantly", "Allows testing rare error states (500 errors, timeout handling) on the UI deterministically"], ["page.route()", "WireMock"]],
  ["Automating OAuth & Social Login", "Authentication", "Intermediate", "technical", "How do you test OAuth2 login flows (Google/GitHub login) without writing fragile automated UI scripts?", ["Authentication", "OAuth"], ["UI testing third-party login pages triggers bot detection and rate limits", "Bypass UI by authenticating via API call and injecting auth cookies/tokens directly into browser context", "Test OAuth integration logic separately at the API layer with test credentials"], ["Browser context injection", "Bypassing bot detection"]],
  ["Automating Canvas and SVG Elements", "Advanced Locators", "Intermediate", "technical", "How do you interact with SVG and HTML5 Canvas elements in Selenium?", ["Selenium", "SVG"], ["SVG elements cannot use standard xpath syntax //svg; must use //*[local-name()='svg'] or CSS selectors", "Canvas renders raw pixel bitmaps without distinct DOM nodes; interact using Actions class with x, y coordinate offsets or execute JavaScript"], ["local-name() function", "Canvas pixel testing"]],
  ["Performance Profiling in Web Automation", "Performance", "Intermediate", "technical", "How do you capture Core Web Vitals (LCP, CLS) programmatically during automated test execution?", ["Performance", "Core Web Vitals"], ["Using Chrome DevTools Protocol (CDP) through Selenium 4 or Playwright", "Execute JavaScript window.performance.getEntriesByType('navigation') to measure load timings", "Automate Lighthouse audits in CI pipelines using lighthouse-ci"], ["Selenium 4 CDP", "Lighthouse CI"]],
  ["Self-Healing Test Automation", "Modern Trends", "Intermediate", "technical", "What is Self-Healing automation and how does it prevent broken test scripts from breaking builds?", ["Modern Trends", "Self-Healing"], ["When a primary locator fails, AI/heuristics evaluate multiple attributes (text, relative position, parent ID, tag)", "Finds matching element with highest confidence score and continues test execution without failing", "Logs recommended locator updates to framework for engineer approval"], ["Heuristic locators", "Test maintenance reduction"]],
  ["Database Teardown & Test Isolation", "Data Management", "Intermediate", "technical", "How do you guarantee test data isolation when multiple automated tests run in parallel?", ["Test Isolation"], ["Each test creates unique entities prefixed with random UUIDs (e.g. test_user_a9f8b@test.com)", "Run tests inside temporary database transactions and rollback after test completes", "Use containerized disposable databases (Testcontainers) per test worker"], ["Testcontainers", "Transactional rollbacks"]],
  ["Flaky Test Quarantine Strategy", "Quality Engineering", "Intermediate", "behavioral", "How do you manage and eliminate flaky tests in a team with a large automation suite?", ["Flaky Tests", "Process"], ["Automatically detect and quarantine flaky tests out of blocking PR pipelines", "Assign flaky tests to triage backlog with failure logs and video recordings", "Require tests to pass 20 consecutive runs in quarantine before returning to production suite"], ["Quarantine suites", "Flakiness metrics"]],
  ["Transitioning Manual QA to Automation", "Leadership", "Easy", "behavioral", "How have you mentored manual QA team members to transition into writing test automation?", ["Mentorship", "Collaboration"], ["Start with modular Page Object Model and reusable helper methods to teach coding fundamentals", "Pair programming on real sprint test cases", "Establish code review guidelines focused on readability and maintainability"], ["Pair programming", "Automation training"]],
  ["Building an Automation Framework from Scratch", "Project Experience", "Intermediate", "behavioral", "Walk me through an automation framework you designed from the ground up. What trade-offs did you make?", ["Framework Design", "Communication"], ["Language and tool selection (Java/Selenium vs TypeScript/Playwright)", "Structure of POM, data management, and parallel execution", "CI/CD integration, reporting dashboard, and test execution time reduction results"], ["Scalability trade-offs", "CI integration"]],
  ["Future of Test Automation (AI & Autonomous Testing)", "Modern Trends", "Easy", "technical", "How are Large Language Models impacting the development and maintenance of test automation suites?", ["AI in Testing", "LLMs"], ["Auto-generating Page Object classes and test scripts from DOM snapshots or Figma designs", "Natural language test creation where plain English instructions translate into executable code", "Automated bug analysis correlating failure logs with recent code commits"], ["Playwright Codegen", "Autonomous testing"]]
];

const autoQuestions = autoTopics.map((t, idx) => ({
  id: `ate-${String(idx + 1).padStart(3, '0')}`,
  role: "Automation Test Engineer",
  category: t[1],
  difficulty: t[2],
  format: t[3],
  question: t[4],
  expectedSkills: t[5],
  evaluationPoints: t[6],
  followUpTopics: t[7]
}));
save('automationTestEngineer.ts', 'AUTOMATION_TEST_ENGINEER_QUESTIONS', autoQuestions);
