const fs = require('fs');
const path = require('path');
const targetDir = 'C:/sih/src/data/interviewQuestions/banks';

function save(filename, exportName, questions) {
  const code = `import { RoleQuestion } from '../types';\n\nexport const ${exportName}: RoleQuestion[] = ${JSON.stringify(questions, null, 2)};\n`;
  fs.writeFileSync(path.join(targetDir, filename), code, 'utf-8');
  console.log(`✓ ${filename} written (${questions.length} questions)`);
}

const cyberTopics = [
  ["CIA Triad in Information Security", "Security Fundamentals", "Easy", "technical", "Explain the CIA Triad (Confidentiality, Integrity, Availability) with practical cybersecurity controls for each.", ["Security Fundamentals"], ["Confidentiality: preventing unauthorized access to data (Encryption at rest/in transit, Access Control Lists, MFA)", "Integrity: ensuring data has not been altered or tampered with (Cryptographic hashes, Digital signatures, HMACs)", "Availability: ensuring authorized users have timely access to data (DDoS mitigation, Load balancers, Redundant backups, Disaster recovery)"], ["Non-repudiation", "Authentication vs Authorization"]],
  ["OSI Model & Attack Vectors", "Networking", "Easy", "technical", "Map common cybersecurity attacks across the 7 layers of the OSI model.", ["Networking", "OSI Model"], ["Layer 7 (Application): SQL Injection, XSS, CSRF, HTTP flood", "Layer 4 (Transport): SYN Flood DDoS, Port scanning", "Layer 3 (Network): IP Spoofing, ICMP Ping of Death", "Layer 2 (Data Link): ARP Poisoning, MAC flooding"], ["TCP handshake", "Wireshark packet analysis"]],
  ["Symmetric vs Asymmetric Encryption", "Cryptography", "Easy", "technical", "Compare Symmetric (AES) vs Asymmetric (RSA, ECC) encryption. How does TLS combine both?", ["Cryptography"], ["Symmetric uses single shared secret key for encryption and decryption (very fast, bulk data like AES-256)", "Asymmetric uses key pair: public key encrypts, private key decrypts (slower, key exchange and digital signatures)", "TLS handshake uses asymmetric cryptography (RSA/ECDHE) to securely exchange symmetric session key, then uses AES-GCM for fast data transmission"], ["AES-256", "Public Key Infrastructure (PKI)"]],
  ["SOC Operations & SIEM Systems", "SOC", "Intermediate", "technical", "What is the role of a Security Information and Event Management (SIEM) system in a Security Operations Center (SOC)?", ["SIEM", "SOC Operations"], ["Aggregates and centralizes logs from firewalls, servers, endpoints, and domain controllers in real time", "Correlation rules correlate disparate events to detect multi-stage attack patterns", "Generates alerts for SOC analysts, assigning severity and feeding into SOAR automation playbooks"], ["Splunk / Microsoft Sentinel", "SOAR automation"]],
  ["Incident Response Lifecycle (NIST SP 800-61)", "Incident Response", "Intermediate", "technical", "Explain the 6 phases of the Incident Response process according to NIST SP 800-61.", ["Incident Response", "NIST"], ["Preparation: hardening systems, training team, deploying tools, establishing communication channels", "Detection & Analysis: identifying indicators of compromise (IoCs), validating alert, determining scope", "Containment: isolating compromised systems from network to prevent lateral movement", "Eradication: removing malware, closing vulnerabilities, revoking compromised credentials", "Recovery: restoring systems from clean backups and monitoring", "Lessons Learned: post-incident review and updating playbooks"], ["Indicators of Compromise (IoCs)", "Containment strategies"]],
  ["Phishing Analysis & Email Security", "Email Security", "Easy", "technical", "How do SPF, DKIM, and DMARC DNS records authenticate emails and protect against domain spoofing?", ["Email Security", "DNS"], ["SPF (Sender Policy Framework): lists authorized IP addresses allowed to send email on behalf of domain", "DKIM (DomainKeys Identified Mail): adds digital cryptographic signature to email headers matching public key in DNS", "DMARC: tells recipient servers what policy to enforce (none, quarantine, reject) if SPF or DKIM fails"], ["DMARC alignment", "Business Email Compromise (BEC)"]],
  ["Firewalls: Packet Filtering vs Next-Gen (NGFW)", "Network Security", "Easy", "technical", "Compare traditional stateful packet-filtering firewalls vs Next-Generation Firewalls (NGFW).", ["Firewalls", "Network Security"], ["Stateful firewalls inspect packets at Layer 3/4 based strictly on IP addresses, ports, and connection state tables", "NGFW operates at Layer 7: performs Deep Packet Inspection (DPI), identifies application traffic regardless of port used", "NGFW integrates Intrusion Prevention (IPS), antivirus scanning, threat intelligence, and TLS decryption"], ["Deep Packet Inspection (DPI)", "Palo Alto / Fortinet"]],
  ["IDS vs IPS (Snort / Suricata)", "Network Security", "Intermediate", "technical", "What is the difference between an Intrusion Detection System (IDS) and an Intrusion Prevention System (IPS)?", ["IDS", "IPS"], ["IDS sits out-of-band (via network TAP or span port); passively monitors traffic and sends alerts on suspicious signatures", "IPS sits in-line with network traffic; can actively block malicious packets, drop connections, and reset TCP sessions in real time", "Signature-based detection vs anomaly/heuristic-based detection"], ["Signature vs Anomaly detection", "False positives in IPS"]],
  ["MITRE ATT&CK Framework", "Threat Intelligence", "Intermediate", "technical", "How do security analysts use the MITRE ATT&CK framework to map adversary Tactics, Techniques, and Procedures (TTPs)?", ["MITRE ATT&CK", "Threat Intelligence"], ["Globally accessible knowledge base of real-world adversary tactics and techniques", "Tactics represent the 'why' (e.g. Initial Access, Persistence, Privilege Escalation, Lateral Movement, Exfiltration)", "Techniques represent the 'how' (e.g. T1059 Command and Scripting Interpreter)", "Used to assess defensive coverage, identify blind spots, and emulate realistic adversary attacks"], ["Threat hunting", "TTPs (Tactics, Techniques, Procedures)"]],
  ["Multi-Factor Authentication (MFA) & Bypasses", "Identity & Access", "Easy", "technical", "What are the three factors of authentication, and how do attackers bypass MFA via MFA fatigue or Adversary-in-the-Middle (AiTM)?", ["MFA", "Identity"], ["Factors: Something you know (password), Something you have (phone, security key), Something you are (biometrics)", "MFA Fatigue (Push Spamming): attacker floods user with hundreds of push notifications until user taps 'Approve' to stop alerts", "AiTM phishing proxies (Evilginx) steal authenticated session cookies after user completes legit MFA prompt"], ["FIDO2 / WebAuthn", "Phishing-resistant MFA"]],
  ["Vulnerability Scanning vs Penetration Testing", "Vulnerability Management", "Easy", "technical", "What is the difference between a Vulnerability Assessment (Nessus, Qualys) and a Penetration Test?", ["Vulnerability Management"], ["Vulnerability assessment is automated, broad scan identifying known missing patches and misconfigurations without exploiting them", "Penetration testing is human-led, goal-oriented ethical hacking that actively exploits vulnerabilities to demonstrate real-world impact and business risk", "Assessments run frequently; pentests run periodically (annually or after major release)"], ["Nessus / Qualys", "CVE / CVSS scores"]],
  ["Zero Trust Architecture Principles", "Architecture", "Intermediate", "technical", "Explain the core tenets of Zero Trust Architecture: 'Never trust, always verify'.", ["Zero Trust", "Security Architecture"], ["Eliminates implicit trust based on network location (inside corporate intranet is treated the same as public internet)", "Enforces least privilege access per request based on user identity, device health posture, and contextual risk signals", "Continuous monitoring and microsegmentation preventing lateral movement"], ["Microsegmentation", "BeyondCorp"]],
  ["Ransomware Kill Chain & Defense", "Malware", "Intermediate", "technical", "Describe the stages of a modern double-extortion ransomware attack and the defense-in-depth controls to stop it.", ["Ransomware", "Malware Defense"], ["Initial access (phishing, RDP exposure) -> Credential dumping (Mimikatz) -> Lateral movement -> Data exfiltration (extortion tier 1) -> Volume shadow copy deletion and mass encryption (extortion tier 2)", "Defenses: immutable offline/air-gapped backups, EDR agent blocking encryption behavior, MFA on all remote access, network segmentation"], ["Air-gapped backups", "EDR behavioral blocking"]],
  ["Endpoint Detection and Response (EDR)", "Endpoint Security", "Intermediate", "technical", "How does an EDR agent (CrowdStrike, SentinelOne) differ from traditional signature-based antivirus?", ["EDR", "Endpoint Security"], ["Traditional AV matches known static file hashes/signatures against virus database (blind to novel zero-days and fileless malware)", "EDR continuously monitors and logs endpoint telemetry (process execution trees, registry modifications, memory injection, network connections)", "Uses machine learning and behavioral heuristics to detect and automatically isolate compromised endpoints in real time"], ["Fileless malware", "Live response"]],
  ["Cross-Site Request Forgery (CSRF) Deep Dive", "Web Security", "Intermediate", "technical", "How does an attacker execute a CSRF attack against a banking transfer endpoint, and why does SameSite cookie attribute mitigate it?", ["Web Security", "CSRF"], ["Attacker lures authenticated user to visit malicious site with hidden image/form auto-submitting POST to bank.com/transfer", "Browser automatically attaches victim's valid session cookies to cross-site request", "SameSite=Strict cookie attribute instructs browser to never attach cookies on cross-site requests, completely blocking CSRF"], ["Anti-CSRF tokens", "SameSite=Lax vs Strict"]],
  ["SQL Injection Types & Remediation", "Web Security", "Easy", "technical", "Compare In-band (Classic), Inferential (Blind), and Out-of-Band SQL Injection. How do you remediate them?", ["SQL Injection", "OWASP"], ["In-band: attacker views SQL query results directly on screen (UNION-based, error-based)", "Blind/Inferential: no data displayed on screen; attacker infers database structure via boolean True/False response differences or time delays (WAITFOR DELAY)", "Remediation: Prepared Statements / Parameterized queries across all database drivers, input validation, least privilege database accounts"], ["Blind SQLi", "Parameterized queries"]],
  ["DDoS Attacks & Mitigation Strategies", "Network Security", "Easy", "technical", "Compare volumetric, protocol, and application-layer DDoS attacks. How do CDNs/Cloudflare mitigate them?", ["DDoS", "Network Security"], ["Volumetric: floods network pipe with massive bandwidth (UDP flood, NTP amplification)", "Protocol: exhausts server/firewall state tables (TCP SYN Flood)", "Application layer: floods web server with resource-heavy HTTP requests (HTTP GET/POST flood)", "Mitigation: Anycast network routing, CDN edge caching, WAF rate-limiting, SYN cookies"], ["Anycast routing", "SYN cookies"]],
  ["Public Key Infrastructure (PKI) & Digital Certificates", "Cryptography", "Intermediate", "technical", "Explain how a Certificate Authority (CA) signs an X.509 SSL certificate and how a browser validates the trust chain.", ["PKI", "Cryptography"], ["Website generates private key and sends Certificate Signing Request (CSR) with public key to CA", "CA verifies domain ownership and signs certificate using CA private key", "Browser has pre-installed trusted root CA certificates in OS trust store; validates CA cryptographic signature down the intermediate chain to server certificate"], ["Certificate Revocation Lists (CRL)", "OCSP Stapling"]],
  ["Active Directory Security: Kerberos & Pass-the-Hash", "Active Directory", "Advanced", "technical", "How does Kerberos authentication work in Windows Active Directory, and what is a Golden Ticket attack?", ["Active Directory", "Kerberos"], ["Ticket Granting Service (TGS) issues Ticket Granting Tickets (TGT) encrypted with KRBTGT account hash", "Golden Ticket attack: adversary extracts KRBTGT password hash and forges arbitrary TGT tickets with domain admin privileges lasting 10 years", "Pass-the-Hash allows attacker with NTLM hash to authenticate without cracking the plaintext password"], ["KRBTGT account", "Mimikatz"]],
  ["Threat Hunting Methodologies", "Threat Intelligence", "Intermediate", "technical", "What is Threat Hunting and how does it differ from reactive alert triage in a SOC?", ["Threat Hunting", "SOC Operations"], ["Proactive, iterative search through network and endpoint telemetry to detect stealthy adversaries that bypassed automated security alerts", "Begins with a hypothesis based on newly published threat intelligence or MITRE ATT&CK technique", "Analyzes event logs for subtle behavioral anomalies (e.g. unusual PowerShell executions, rundll32 network connections)"], ["Hypothesis-driven hunting", "Behavioral baselines"]],
  ["Log Analysis with Syslog & Windows Event IDs", "Log Analysis", "Easy", "practical", "What are the most critical Windows Security Event IDs every security analyst must know?", ["Log Analysis", "Windows Security"], ["Event ID 4624: Successful logon; Event ID 4625: Failed logon (brute force detection)", "Event ID 4688: New process created (detects suspicious command line executions)", "Event ID 4720: User account created; Event ID 4728: Member added to security group", "Event ID 1102: The audit log was cleared (indicator of tampering)"], ["Logon types (Type 2, 3, 10)", "Sysmon telemetry"]],
  ["Cloud Security Posture Management (CSPM)", "Cloud Security", "Intermediate", "technical", "What does a CSPM tool do to identify misconfigurations across multi-cloud environments?", ["Cloud Security", "CSPM"], ["Continuously monitors AWS, Azure, and GCP resources against security benchmarks (CIS Benchmarks, NIST)", "Detects high-risk misconfigurations (public S3 buckets, open security group 0.0.0.0/0 on port 22/3389, unencrypted EBS volumes)", "Provides automated compliance reporting and auto-remediation playbooks"], ["CIS Benchmarks", "Cloud misconfigurations"]],
  ["Man-in-the-Middle (MitM) & ARP Spoofing", "Network Security", "Easy", "technical", "How does ARP Spoofing allow an attacker on a local network to intercept unencrypted traffic?", ["Networking", "MitM"], ["ARP maps Layer 3 IP addresses to Layer 2 physical MAC addresses without authentication", "Attacker sends gratuitous ARP replies associating the gateway's IP address with the attacker's MAC address", "Victim sends all outbound internet traffic to attacker instead of legit router", "Defense: Dynamic ARP Inspection (DAI) on managed network switches, static ARP tables, end-to-end TLS"], ["Dynamic ARP Inspection (DAI)", "Ettercap / Bettercap"]],
  ["Security Operations: False Positives & Alert Fatigue", "SOC Operations", "Easy", "behavioral", "How do you tune SIEM correlation rules to reduce alert fatigue without missing true positive attacks?", ["SOC Operations", "SIEM"], ["Review high-volume noisy alerts and identify benign business patterns causing false alarms", "Add exclusion filters and whitelist authorized administrative IP ranges and service accounts", "Combine multiple low-fidelity signals into a single high-fidelity composite alert before waking an on-call analyst"], ["Alert tuning", "Noise reduction"]],
  ["Hash Algorithms & Salted Password Storage", "Cryptography", "Easy", "technical", "Why is a cryptographic salt essential when storing hashed passwords in a database?", ["Cryptography", "Security"], ["Salt is a unique cryptographically random string appended to password before hashing", "Guarantees that two users with identical passwords have completely different password hashes", "Completely defeats precomputed Rainbow Table attacks; requires attacker to compute dictionary attack per salt individually"], ["Rainbow tables", "bcrypt / Argon2"]],
  ["Privilege Escalation Techniques (Linux & Windows)", "Offensive Security", "Intermediate", "technical", "Explain common privilege escalation techniques on Linux and Windows systems.", ["Privilege Escalation"], ["Linux: misconfigured SUID binaries (find with chmod 4000), writable /etc/passwd or shadow, vulnerable kernel exploits, insecure sudoers configurations (sudo without password)", "Windows: unquoted service paths, insecure service permissions, always install elevated policies, token impersonation (SeImpersonatePrivilege with RottenPotato)"], ["SUID binaries", "Token impersonation"]],
  ["Security Hardening: Bastion Hosts & Jump Boxes", "Infrastructure Security", "Easy", "technical", "What is a Bastion Host (Jump Box) and how does it secure administrative access to private servers?", ["Network Security"], ["Specialized, hardened server placed in a public subnet or DMZ as the sole entry point for administrative SSH/RDP access", "Backend database and application servers strictly block all direct public internet access, accepting connections ONLY from the bastion host IP", "Hardened: MFA required, session recording enabled, all non-essential ports and software removed"], ["DMZ architecture", "Session recording"]],
  ["Data Loss Prevention (DLP) Architecture", "Data Security", "Intermediate", "technical", "How do Data Loss Prevention (DLP) tools detect and block unauthorized exfiltration of sensitive data?", ["DLP", "Data Protection"], ["Inspects data in motion (network traffic, email), data at rest (servers, cloud storage), and data in use (USB drives, clipboard)", "Uses pattern matching (regex for credit cards, SSN), keyword dictionaries, and exact data matching (EDM) file fingerprints", "Automatically blocks upload, encrypts file, or alerts security team upon policy violation"], ["Exact Data Matching", "Endpoint DLP"]],
  ["Indicators of Compromise (IoCs) vs Indicators of Attack (IoAs)", "Threat Intelligence", "Intermediate", "technical", "Compare Indicators of Compromise (IoCs) and Indicators of Attack (IoAs).", ["Threat Intelligence"], ["IoC is static forensic artifact left behind AFTER a breach has occurred (file MD5 hash, malicious IP address, C2 domain name, registry key)", "IoA focuses on behavioral intent and tactics DURING the attack in real time (process injection into lsass.exe, suspicious PowerShell downloading script, lateral movement)", "IoCs change easily; IoAs catch novel attacks based on behavior"], ["Pyramid of Pain", "C2 infrastructure"]],
  ["Digital Forensics: Preserving Chain of Custody", "Digital Forensics", "Intermediate", "technical", "How do you preserve evidence and maintain Chain of Custody during a digital forensics investigation?", ["Digital Forensics"], ["Document chronological history of who collected, handled, transferred, and analyzed evidence", "Create bit-stream physical image copies (dd, FTK Imager) of hard drives before analyzing; NEVER analyze live original drive directly", "Calculate cryptographic hashes (SHA-256) of evidence before and after imaging to prove data was not altered"], ["FTK Imager", "Volatile memory capture (Volatility)"]],
  ["DNS Tunneling & C2 Communications", "Network Security", "Advanced", "technical", "How do threat actors use DNS Tunneling for data exfiltration and Command and Control (C2)?", ["DNS Security", "C2"], ["Adversary encodes binary data into subdomains of a malicious domain they control (e.g. a8f9b1c.attacker.com)", "Local recursive DNS server resolves query up to attacker's authoritative nameserver, transmitting data through firewall", "Defenses: inspect DNS query length, high entropy of subdomains, abnormal query volume, and response TXT record payloads"], ["DNS sinkholing", "Domain entropy"]],
  ["Security Awareness & Social Engineering", "Security Culture", "Easy", "behavioral", "How do you design an effective enterprise anti-phishing training campaign without shaming employees?", ["Security Culture", "Phishing"], ["Run simulated phishing campaigns mimicking realistic current threat scenarios", "Provide immediate, positive, educational feedback at moment of click without public shaming or punishment", "Recognize and reward employees who report suspicious phishing emails using one-click reporting plugins"], ["Phishing simulations", "Security culture"]],
  ["Investigating a Compromised Server Scenario", "Incident Response", "Intermediate", "scenario", "You receive an EDR alert that PowerShell executed a Base64-encoded command connecting to an unknown foreign IP. What do you do?", ["Incident Response", "Investigation"], ["Isolate the endpoint from network via EDR console immediately to prevent lateral movement", "Decode Base64 payload to determine intent (malware download, credential dumping, persistence installation)", "Identify parent process tree, check logged-on user account, and search SIEM for other endpoints connecting to the same C2 IP"], ["Base64 decoding", "Lateral movement triage"]],
  ["High-Pressure Security Incident Experience", "Project Experience", "Intermediate", "behavioral", "Describe a real security vulnerability or incident you investigated. What was your containment and remediation approach?", ["Incident Response", "Communication"], ["Incident context, initial alert trigger, and scope identification", "Containment actions taken (network isolation, account disable, credential rotation)", "Root cause discovery, remediation patching, and preventative controls implemented to eliminate recurring risk"], ["Containment metrics", "Lessons learned"]],
  ["Future of Cybersecurity (AI-Driven Attacks & Quantum Safe)", "Modern Trends", "Easy", "technical", "How are AI-driven cyber attacks evolving, and what is Post-Quantum Cryptography (PQC)?", ["Modern Security", "PQC"], ["AI enables hyper-realistic personalized spear phishing at scale, automated vulnerability discovery, and polymorphic malware that evades EDR signatures", "Quantum computers threaten to break RSA and ECC asymmetric encryption via Shor's algorithm", "NIST has standardized Post-Quantum Cryptographic algorithms (CRYSTALS-Kyber, Dilithium) based on lattice mathematics"], ["Post-Quantum Cryptography", "Adversarial AI"]]
];

const cyberQuestions = cyberTopics.map((t, idx) => ({
  id: `csa-${String(idx + 1).padStart(3, '0')}`,
  role: "Cybersecurity Analyst",
  category: t[1],
  difficulty: t[2],
  format: t[3],
  question: t[4],
  expectedSkills: t[5],
  evaluationPoints: t[6],
  followUpTopics: t[7]
}));
save('cybersecurityAnalyst.ts', 'CYBERSECURITY_ANALYST_QUESTIONS', cyberQuestions);
