const fs = require('fs');
const path = require('path');
const targetDir = 'C:/sih/src/data/interviewQuestions/banks';

function save(filename, exportName, questions) {
  const code = `import { RoleQuestion } from '../types';\n\nexport const ${exportName}: RoleQuestion[] = ${JSON.stringify(questions, null, 2)};\n`;
  fs.writeFileSync(path.join(targetDir, filename), code, 'utf-8');
  console.log(`✓ ${filename} written (${questions.length} questions)`);
}

const cloudSupportTopics = [
  ["Troubleshooting EC2 SSH Connection Timeouts", "Compute & Linux", "Easy", "scenario", "A customer reports: 'ssh -i key.pem ec2-user@<IP>' hangs and times out. Walk me through your step-by-step diagnostic checklist.", ["AWS EC2", "Troubleshooting"], ["Check Security Group inbound rules: is Port 22 open from customer's public IP?", "Check Route Table of the subnet: is there an active route (0.0.0.0/0) pointing to an Internet Gateway (IGW)?", "Verify EC2 has a public IPv4 address assigned and is not in a private subnet", "Check Network ACLs (NACLs) inbound and outbound rules; check instance state in console"], ["NACL stateless rules", "System Log in EC2"]],
  ["Troubleshooting 'Connection Refused' vs 'Connection Timed Out'", "Networking", "Easy", "technical", "What is the architectural and network difference between 'Connection Timed Out' and 'Connection Refused'?", ["Networking", "Troubleshooting"], ["Connection Timed Out: packet was dropped along network path without response (firewall, Security Group, or routing failure)", "Connection Refused: packet reached target host, but no service is listening on that port or host firewall (iptables/ufw) rejected TCP RST", "Refused means network routing and security groups are working; issue is on the operating system/daemon level"], ["TCP RST packet", "iptables vs Security Groups"]],
  ["EC2 Status Checks: System vs Instance Failure", "Compute", "Easy", "technical", "What is the difference between an EC2 System Status Check failure and an Instance Status Check failure?", ["AWS EC2", "Monitoring"], ["System Status Check (0/2): underlying AWS hardware, physical host, or network infrastructure issue -> Resolved by stopping and starting instance to migrate to a new physical host", "Instance Status Check (1/2): operating system level failure inside VM (kernel panic, corrupt boot volume, exhausted memory, misconfigured network config) -> Inspected via System Log / Instance Screenshot"], ["Stop and start migration", "EC2 System Log"]],
  ["HTTP 502 Bad Gateway vs 504 Gateway Timeout on ALB", "Networking", "Intermediate", "technical", "What causes HTTP 502 Bad Gateway vs HTTP 504 Gateway Timeout on an Application Load Balancer?", ["AWS ALB", "HTTP Status Codes"], ["HTTP 502 Bad Gateway: ALB reached target backend EC2/container, but backend returned an invalid HTTP response, malformed header, or suddenly closed TCP connection (RST)", "HTTP 504 Gateway Timeout: ALB forwarded request to target, but backend application failed to respond within the configured ALB Idle Timeout window (long query, deadlock)"], ["ALB access logs", "Target response time metric"]],
  ["Troubleshooting Unhealthy Targets in ALB Target Group", "Networking", "Intermediate", "scenario", "All targets in an ALB Target Group are marked 'Unhealthy'. How do you troubleshoot and restore traffic?", ["AWS ALB", "High Availability"], ["Check Target Group Health Check settings: path (e.g. /health), port, and expected HTTP status code (e.g. 200)", "Verify web server on EC2 is listening on target port and responding locally: curl -Iv http://localhost:<port>/health", "Check Security Group on EC2 instances: does it allow inbound traffic on target port from the ALB's security group?"], ["Health check path", "Security Group chaining"]],
  ["Diagnosing Linux Disk Full (100% Utilized)", "Linux Administration", "Easy", "practical", "A Linux server reports 'No space left on device'. How do you identify what consumed the disk, and what if df shows 100% but du shows space free?", ["Linux", "Storage"], ["Run 'df -h' to see filesystem usage; run 'du -sh /* | sort -h' to find largest consuming directory (usually /var/log)", "If du shows free space but df shows 100%: running processes are holding open deleted file handles; find with 'lsof +L1' or 'lsof | grep deleted'", "Restart offending process to release locked disk blocks"], ["lsof +L1", "Inode exhaustion (df -i)"]],
  ["Linux Inode Exhaustion (df -h vs df -i)", "Linux Administration", "Intermediate", "technical", "A customer cannot create files on a Linux volume even though 'df -h' shows 50GB free space. What is the cause?", ["Linux", "Storage"], ["Inode exhaustion: filesystem has created maximum allowable number of files, exhausting the inode table ('df -i' shows 100% inode usage)", "Caused by millions of tiny files (e.g. PHP session files, uncleaned spool or cache directories)", "Identify directory with highest file count: find / -xdev -printf '%h\n' | sort | uniq -c | sort -k 1 -n"], ["df -i", "Inode table"]],
  ["Troubleshooting High CPU Utilization on EC2", "Compute", "Easy", "practical", "An EC2 instance is at 100% CPU utilization. What commands do you run via SSH to pinpoint the offending process?", ["Linux", "Troubleshooting"], ["top or htop to identify top CPU-consuming process IDs and user accounts", "ps aux --sort=-%cpu | head -10 to list top 10 CPU-consuming processes with command arguments", "strace -p <PID> to inspect system calls of runaway process, or gstack/jstack for thread dumps"], ["Load average vs CPU %", "strace command"]],
  ["Amazon S3 Access Denied Troubleshooting", "Storage & IAM", "Intermediate", "scenario", "A customer receives 'Access Denied (403 Forbidden)' when accessing an S3 object. What are the 5 layers of S3 permission evaluation?", ["AWS S3", "IAM"], ["IAM User/Role permissions policy: does it allow s3:GetObject on specific bucket/object ARN?", "S3 Bucket Policy: is there an explicit Deny policy overriding permissions?", "S3 Block Public Access settings: are public requests blocked at account or bucket level?", "KMS Key Policy: if object is encrypted with SSE-KMS, does user have kms:Decrypt permissions on the key?", "Object Access Control List (ACL) ownership (Bucket Owner Enforced setting)"], ["KMS key permissions", "Explicit Deny precedence"]],
  ["VPC Peering vs Transit Gateway Troubleshooting", "Networking", "Intermediate", "technical", "A customer configured VPC Peering between VPC A and VPC B, but instances cannot communicate. What is missing?", ["VPC Peering", "Networking"], ["Check Route Tables: both VPC A and VPC B route tables must have explicit routes pointing target CIDR to the peering connection ID (pcx-xxxx)", "Check Security Groups: inbound rules on instances in VPC B must allow traffic from VPC A CIDR or security group", "Ensure IPv4 CIDR blocks of VPC A and VPC B do not overlap (overlapping CIDRs block peering)"], ["Overlapping CIDRs", "Route table propagation"]],
  ["AWS Direct Connect vs VPN Failover", "Networking", "Intermediate", "technical", "How does automated failover work between an AWS Direct Connect dedicated link and an IPsec Site-to-Site VPN?", ["Networking", "Hybrid Cloud"], ["BGP (Border Gateway Protocol) dynamically exchanges routing information between on-premises and AWS Virtual Private Gateway / Transit Gateway", "Advertise identical on-premises prefixes over both Direct Connect and VPN connections", "Direct Connect has higher routing preference by default; traffic automatically switches to IPsec VPN on Direct Connect link failure"], ["BGP AS Path prepending", "Direct Connect Virtual Interfaces"]],
  ["Troubleshooting DNS Resolution Failures (Route 53)", "DNS & Networking", "Easy", "practical", "A website hosted in AWS is unreachable by domain name. What command-line utilities do you use to trace DNS resolution?", ["DNS", "Route 53"], ["dig +trace mydomain.com to trace full hierarchical DNS delegation from root nameservers to authoritative nameservers", "nslookup mydomain.com to check local resolver response", "host or dig @8.8.8.8 mydomain.com to verify authoritative nameserver returns correct A or CNAME record", "Check domain registration status (WHOIS) for registrar hold or expired domain"], ["dig +trace", "TTL caching"]],
  ["Recovering an EC2 Instance with Lost SSH Key", "Compute", "Intermediate", "practical", "A customer lost their SSH private key (.pem) for an EBS-backed EC2 instance. How do you recover access without losing data?", ["AWS EC2", "Storage"], ["Stop the compromised instance", "Detach the root EBS volume (/dev/xvda)", "Attach the volume to a healthy temporary rescue instance in the same AZ", "Mount the volume, append new public key into /home/ec2-user/.ssh/authorized_keys, unmount", "Re-attach volume back to original instance as /dev/xvda and start instance"], ["EC2 Serial Console", "AWS Systems Manager Session Manager"]],
  ["AWS Systems Manager (SSM) Session Manager", "Management & Security", "Easy", "technical", "Why is AWS SSM Session Manager the modern best practice for server access instead of opening SSH Port 22?", ["AWS SSM", "Security"], ["Provides secure one-click browser or CLI shell access without opening inbound Port 22 or managing bastion hosts", "Eliminates managing and rotating SSH key pairs (.pem files); access controlled strictly via IAM policies", "Logs every executed command and session transcript to Amazon S3 and CloudWatch Logs for audit compliance"], ["SSM Agent", "Zero inbound ports"]],
  ["Troubleshooting High RDS Memory & IOPS Spikes", "Database", "Intermediate", "scenario", "An Amazon RDS PostgreSQL instance is experiencing high CPU, low Freeable Memory, and ReadIOPS spikes. How do you investigate?", ["AWS RDS", "Performance"], ["Enable and inspect Performance Insights to identify top SQL queries contributing to Database Load (DBLoad vs vCPU line)", "Check CloudWatch metrics: ReadIOPS, WriteIOPS, DiskQueueDepth, FreeableMemory, and SwapUsage", "Inspect slow query logs to find unindexed full table scans causing buffer cache evictions and heavy disk reads"], ["RDS Performance Insights", "DiskQueueDepth"]],
  ["RDS Storage Full Emergency (Storage Auto-Scaling)", "Database", "Intermediate", "scenario", "An RDS instance reaches 100% storage capacity and enters 'storage-full' status, dropping all writes. How do you recover it?", ["AWS RDS", "Troubleshooting"], ["Modify DB instance immediately to allocate additional storage capacity (storage volume will expand in-place)", "Enable RDS Storage Auto-Scaling to prevent future recurrence (scales up to max threshold automatically)", "If modification is blocked, delete old manual snapshots or archive non-essential data if read-only access is available"], ["Storage auto-scaling", "EBS volume expansion"]],
  ["Troubleshooting Lambda Function Timeouts", "Serverless", "Easy", "technical", "A Lambda function with a 30-second timeout consistently times out. What are the common root causes?", ["AWS Lambda", "Serverless"], ["Function is attempting to connect to resources in a private VPC (RDS, ElastiCache) without proper Security Group or VPC routing (missing NAT Gateway for internet)", "Downstream external API is hanging or taking longer than 30s to respond", "Database connection pool exhaustion or unindexed slow query blocking execution thread"], ["Lambda VPC networking", "CloudWatch Logs Insights"]],
  ["Lambda 'Task Timed Out After X Seconds' Investigation", "Serverless", "Easy", "practical", "How do you use CloudWatch Logs Insights to analyze Lambda execution durations and memory utilization?", ["AWS Lambda", "CloudWatch"], ["Run CloudWatch Logs Insights query filtering on 'REPORT' lines: fields @timestamp, @duration, @billedDuration, @memorySize, @maxMemoryUsed", "Identify whether function is hitting configured memory limit (out of memory triggers slow execution or crash)", "Check initDuration to see impact of cold starts on timeout limits"], ["Billed duration", "Max memory used"]],
  ["AWS CloudWatch Synthetics Canaries", "Monitoring", "Easy", "technical", "What is an Amazon CloudWatch Synthetics Canary and how does it monitor website uptime proactively?", ["Monitoring", "CloudWatch"], ["Configurable Node.js/Python scripts running on a schedule (using Puppeteer/Selenium) to simulate customer interactions", "Tests endpoints, checkout flows, and API responses 24/7 from multiple AWS regions", "Triggers CloudWatch alarms and captures screenshots, HAR files, and execution traces on step failure before real users complain"], ["Canary scripts", "Synthetic monitoring vs Real user monitoring"]],
  ["Customer Escalation Management & Severity SLAs", "Customer Service", "Easy", "behavioral", "How do you manage an angry customer experiencing a production-down emergency whose issue is taking longer than expected?", ["Communication", "Incident Management"], ["Acknowledge severity immediately with empathy; avoid robotic defensive language", "Establish regular communication cadence (e.g. status update every 30 minutes even if no breakthrough yet)", "Explain clearly what has been tested, what is ruled out, and what active diagnostic steps are underway"], ["De-escalation", "Support SLAs"]],
  ["Troubleshooting Auto Scaling Termination Issues", "Compute", "Intermediate", "technical", "Why might an Auto Scaling Group fail to launch instances, repeatedly creating and terminating them in a loop?", ["Auto Scaling", "Troubleshooting"], ["Instance fails EC2 or ELB health check immediately upon launch due to failing initialization script (User Data error)", "AMI ID in Launch Template is deleted, invalid, or belongs to a different architecture", "VPC subnet has exhausted available private IP addresses, blocking new ENI allocation"], ["EC2 User Data logs", "Subnet IP exhaustion"]],
  ["Debugging EC2 User Data Scripts", "Compute & Linux", "Easy", "practical", "Where do you find logs on an EC2 instance to see why a User Data bootstrap script failed to run?", ["Linux", "AWS EC2"], ["Inspect /var/log/cloud-init-output.log to see stdout and stderr of the user data script execution", "Inspect /var/log/cloud-init.log for cloud-init process details", "User data scripts run as root user only once on initial instance boot"], ["cloud-init-output.log", "Cloud-init"]],
  ["Troubleshooting Network Connectivity with Traceroute & MTR", "Networking", "Intermediate", "practical", "How do you use traceroute and mtr (My Traceroute) to determine where network packet loss is occurring?", ["Networking", "Diagnostics"], ["mtr combines traceroute and ping; sends continuous packets to every router hop along the path", "Examine Loss% and Latency columns across each intermediate hop", "If packet loss appears on hop 4 and continues through all subsequent hops to destination, loss is genuine at hop 4; if loss appears on only one hop and not downstream, router is rate-limiting ICMP"], ["MTR report", "ICMP rate limiting"]],
  ["Packet Capture with TCPDump and Wireshark", "Networking", "Intermediate", "practical", "How do you capture network traffic on a Linux server using tcpdump to investigate missing HTTP responses?", ["Linux", "Networking"], ["sudo tcpdump -i eth0 -nn 'port 80 or port 443' -w capture.pcap", "-i specifies network interface; -nn disables DNS and port name resolution for speed; -w writes raw packet capture to file", "Transfer .pcap file to workstation and analyze in Wireshark to inspect TCP 3-way handshake, retransmissions, and HTTP payloads"], ["tcpdump syntax", "Wireshark stream analysis"]],
  ["AWS Support Case Triage & Severity Levels", "Cloud Support", "Easy", "technical", "Explain AWS Support case severity levels (General guidance, System impaired, Production system down, Production system impaired, Business-critical system down).", ["AWS Support", "SLAs"], ["General Guidance: <24 hours response time", "System Impaired: <12 hours response time", "Production System Impaired: <4 hours response time", "Production System Down: <1 hour response time (24/7)", "Business-Critical System Down: <15 minutes response time (available on Enterprise Support plan)"], ["Enterprise Support", "Severity response times"]],
  ["Cross-Account IAM Role AssumeRole Troubleshooting", "IAM", "Intermediate", "technical", "A developer in Account A fails to assume a role in Account B with 'Access Denied'. What two policies must be verified?", ["IAM", "Security"], ["Trust Policy on Role in Account B: must explicitly list Account A's root or user ARN under 'Principal': {'AWS': 'arn:aws:iam::AccountA:root'}", "Identity Policy on User/Role in Account A: must grant permission 'Action': 'sts:AssumeRole' on the specific Role ARN in Account B", "Both must be present; if either side is missing, sts:AssumeRole fails with 403 Access Denied"], ["AssumeRole", "External ID in trust policy"]],
  ["Troubleshooting KMS Key Policy Access", "Security & KMS", "Intermediate", "technical", "Why does an IAM Administrator with AdministratorAccess policy fail to decrypt an S3 object encrypted with a custom KMS key?", ["AWS KMS", "Security"], ["KMS keys do NOT follow standard IAM delegation unless the Key Policy explicitly delegates access to the account root", "The KMS Key Policy itself is the primary access control; if the Key Policy does not grant permissions to the user or account, IAM policies have zero effect", "Fix: add the user/role or the account root to the KMS Key Policy's 'Principal' block with kms:Decrypt permissions"], ["KMS Key Policy", "IAM delegation"]],
  ["Troubleshooting SQS Queue Depth & Consumer Lag", "Messaging", "Intermediate", "scenario", "An Amazon SQS queue's ApproximateNumberOfMessagesVisible metric is climbing to 100,000. How do you triage the bottleneck?", ["AWS SQS", "Troubleshooting"], ["Check consumer service health: are worker EC2 instances, containers, or Lambda consumers crashing or deadlocked?", "Compare SQS ApproximateNumberOfMessagesVisible against NumberOfMessagesReceived and NumberOfMessagesDeleted to measure processing rate vs arrival rate", "Scale up consumer worker count or check for slow database writes / downstream API bottlenecks blocking workers"], ["Visibility timeout", "Dead Letter Queue (DLQ)"]],
  ["Dead Letter Queues (DLQ) in Cloud Architecture", "Messaging", "Easy", "technical", "What is a Dead Letter Queue (DLQ) and what is the maxReceiveCount attribute in SQS?", ["AWS SQS", "Architecture"], ["DLQ is a secondary queue holding messages that failed processing after multiple attempts", "maxReceiveCount defines how many times a message can be received and returned to the queue before being routed to the DLQ", "Prevents poison pill messages from looping infinitely and blocking queue consumers"], ["Poison pill messages", "Redrive policy"]],
  ["Troubleshooting CloudFront 403 / 502 Errors", "CDN", "Intermediate", "technical", "A website behind CloudFront returns 'CloudFront 403 Forbidden' vs 'CloudFront 502 Bad Gateway'. How do you isolate the source?", ["CloudFront", "CDN"], ["CloudFront 403: blocked by AWS WAF rule attached to distribution, or Origin S3 bucket policy denies CloudFront Origin Access Control (OAC)", "CloudFront 502: CloudFront cannot negotiate SSL/TLS with custom origin (expired certificate, mismatched domain name, or unsupported cipher suite), or origin server timed out"], ["Origin Access Control (OAC)", "SSL negotiation with origin"]],
  ["Troubleshooting Elastic Beanstalk Deployment Failures", "Deployment", "Intermediate", "practical", "An AWS Elastic Beanstalk deployment fails with 'Environment update failed'. Where do you find the exact error logs?", ["Elastic Beanstalk", "Troubleshooting"], ["Request 'Last 100 Lines' or 'Full Logs' from Elastic Beanstalk console -> eb-engine.log and cfn-init.log", "eb-engine.log records execution of platform hooks and application container startup", "cfn-init.log records CloudFormation resource provisioning and .ebextensions configuration script failures"], ["eb-engine.log", ".ebextensions"]],
  ["Technical Documentation & Knowledge Base Writing", "Documentation", "Easy", "behavioral", "Why is contributing to internal Knowledge Base (KB) articles and customer-facing playbooks critical in cloud support engineering?", ["Documentation", "Knowledge Sharing"], ["Empowers tier 1 support and on-call engineers to resolve recurring complex issues rapidly using verified standard procedures", "Eliminates tribal knowledge and reduces Mean Time to Resolution (MTTR)", "Improves customer self-service, reducing incoming support case volume"], ["Runbooks", "MTTR reduction"]],
  ["Complex Multi-Service Cloud Issue Experience", "Project Experience", "Intermediate", "behavioral", "Describe a complex cloud support issue involving multiple interconnected services (e.g. ALB -> ECS -> RDS) that you resolved.", ["Troubleshooting", "Communication"], ["Incident description and systematic end-to-end trace through the request path", "Isolating the failure layer using metrics, logs, and connection testing", "Resolution applied, customer communication, and preventative monitoring recommendations"], ["End-to-end tracing", "Lessons learned"]],
  ["Communicating Technical Solutions to Frustrated Customers", "Communication", "Easy", "behavioral", "How do you explain a complex technical limitation or root cause to a non-technical customer who is frustrated?", ["Communication", "Empathy"], ["Avoid deep jargon, acronyms, and defensive excuses", "Use clear analogies and focus on business impact and what actions have been taken", "Provide clear, step-by-step instructions with screenshots and offer a screen-share session if needed"], ["Customer empathy", "Plain language"]],
  ["Future of Cloud Support & AI Ops", "Modern Trends", "Easy", "technical", "How are AI-powered diagnostics (Amazon DevOps Guru, GenAI support assistants) transforming Cloud Support Engineering?", ["AIOps", "Modern Support"], ["Automatically correlates anomalies across CloudWatch metrics and logs to identify root cause recommendations before tickets are filed", "GenAI assistants synthesize customer logs, cloud architecture diagrams, and historical knowledge base articles to suggest instant diagnostic steps", "Shifts support engineers from manual log parsing to higher-level proactive reliability architecture"], ["Amazon DevOps Guru", "AIOps"]]
];

const cloudSupportQuestions = cloudSupportTopics.map((t, idx) => ({
  id: `cse-${String(idx + 1).padStart(3, '0')}`,
  role: "Cloud Support Engineer",
  category: t[1],
  difficulty: t[2],
  format: t[3],
  question: t[4],
  expectedSkills: t[5],
  evaluationPoints: t[6],
  followUpTopics: t[7]
}));
save('cloudSupportEngineer.ts', 'CLOUD_SUPPORT_ENGINEER_QUESTIONS', cloudSupportQuestions);
