const fs = require('fs');
const path = require('path');
const targetDir = 'C:/sih/src/data/interviewQuestions/banks';

function save(filename, exportName, questions) {
  const code = `import { RoleQuestion } from '../types';\n\nexport const ${exportName}: RoleQuestion[] = ${JSON.stringify(questions, null, 2)};\n`;
  fs.writeFileSync(path.join(targetDir, filename), code, 'utf-8');
  console.log(`✓ ${filename} written (${questions.length} questions)`);
}

// 1. DATA ANALYST (35 questions)
const daTopics = [
  ["WHERE vs HAVING", "SQL", "Easy", "technical", "What is the difference between WHERE and HAVING in SQL?", ["SQL"], ["WHERE filters rows before aggregation", "HAVING filters grouped records after GROUP BY", "WHERE cannot evaluate aggregate functions directly"], ["GROUP BY", "SQL execution order"]],
  ["Rolling Average with Window Functions", "SQL", "Intermediate", "practical", "Write a SQL query using window functions to calculate a 7-day rolling average of revenue.", ["SQL", "Window Functions"], ["AVG(revenue) OVER (ORDER BY date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW)", "Explain difference between ROWS and RANGE", "PARTITION BY for multi-product rolling metrics"], ["Cumulative totals", "LEAD and LAG"]],
  ["ROW_NUMBER vs RANK vs DENSE_RANK", "SQL", "Intermediate", "technical", "Compare ROW_NUMBER(), RANK(), and DENSE_RANK() in SQL with tie-breaking examples.", ["SQL", "Window Functions"], ["ROW_NUMBER assigns distinct sequential integers", "RANK leaves gaps after ties (1, 2, 2, 4)", "DENSE_RANK leaves no gaps after ties (1, 2, 2, 3)"], ["Top N queries", "Finding Nth highest salary"]],
  ["Handling Missing Values in Pandas", "Pandas", "Easy", "technical", "How do you handle NaNs in Pandas? What criteria guide dropping vs imputing?", ["Pandas", "Data Cleaning"], ["dropna() vs fillna() with mean/median/mode", "Understanding MCAR vs MNAR missingness", "Evaluating percentage of missing records"], ["IterativeImputer", "Forward/backward fill"]],
  ["Pandas groupby and pivot_table", "Pandas", "Intermediate", "technical", "Explain groupby, merge, and pivot_table operations in Pandas for data analysis.", ["Pandas"], ["groupby aggregates along dimensions", "merge performs relational SQL-like joins", "pivot_table reshapes into multi-dimensional summaries"], ["melt function", "MultiIndex DataFrames"]],
  ["XLOOKUP vs VLOOKUP", "Excel", "Easy", "technical", "Why is XLOOKUP superior to VLOOKUP in modern Microsoft Excel?", ["Excel"], ["XLOOKUP searches left and right without column index constraints", "Does not break when columns are inserted or deleted", "Built-in if_not_found error handling"], ["INDEX-MATCH", "Dynamic array formulas"]],
  ["Mean vs Median", "Statistics", "Easy", "technical", "When should you report the Median instead of the Mean for business KPIs?", ["Statistics"], ["Mean is distorted by extreme outliers and skewed distributions", "Median represents true 50th percentile central tendency", "Use for salaries, property prices, and transaction amounts"], ["Interquartile Range", "Standard deviation"]],
  ["Correlation vs Causation", "Statistics", "Intermediate", "technical", "Explain correlation vs causation and give an example of a confounding variable in business analytics.", ["Statistics", "Critical Thinking"], ["Correlation measures linear association; causation proves one causes the other", "Confounders create spurious correlations (e.g. ice cream sales and drowning)", "Randomized A/B testing is required to establish causality"], ["Pearson vs Spearman", "Confounding bias"]],
  ["Selecting Visualization Charts", "Visualization", "Easy", "technical", "How do you choose between line charts, bar charts, scatter plots, and heatmaps?", ["Visualization"], ["Line charts for trends over continuous time", "Bar charts for discrete categorical comparisons", "Scatter plots for correlation between two continuous variables", "Heatmaps for 2D matrix densities"], ["Color accessibility", "Chart junk"]],
  ["Power BI Measures vs Calculated Columns", "BI Tools", "Intermediate", "technical", "In Power BI, what is the architectural difference between calculated columns and DAX measures?", ["Power BI", "DAX"], ["Calculated columns are precomputed and stored in RAM during data refresh", "Measures are calculated dynamically on-the-fly based on visual filter context", "Measures should be used for KPI aggregates and ratios"], ["CALCULATE function", "Star schema modeling"]],
  ["Core Business Metrics", "Business Metrics", "Intermediate", "technical", "Define Customer Acquisition Cost (CAC), Lifetime Value (LTV), and Churn Rate.", ["Business Analysis", "KPIs"], ["CAC is total marketing spend divided by new customers acquired", "LTV is average revenue per customer times customer lifespan", "Churn is percentage of customers lost in a period", "Healthy LTV:CAC target is 3:1"], ["Cohort retention", "Net Revenue Retention"]],
  ["Cleaning Dirty Data", "Data Cleaning", "Intermediate", "scenario", "You receive an e-commerce dataset with duplicate rows, negative prices, and bad dates. How do you clean it?", ["Data Cleaning", "Data Quality"], ["Audit and profile data distributions", "Deduplicate based on composite keys", "Filter/investigate negative prices (refunds vs error)", "Standardize date strings to ISO YYYY-MM-DD"], ["Outlier detection", "Data validation rules"]],
  ["Common Table Expressions (CTEs)", "SQL", "Intermediate", "technical", "What is a CTE (WITH clause) in SQL and why is it preferred over nested subqueries?", ["SQL"], ["Improves query readability and modular design", "Can be referenced multiple times within main query", "Supports recursive queries for hierarchical data"], ["Recursive CTEs", "Temporary tables"]],
  ["Root Cause Analysis for KPI Drop", "Scenario Analysis", "Advanced", "scenario", "Overall checkout conversion dropped by 15% last week. Walk me through your troubleshooting steps.", ["Problem Solving", "Root Cause Analysis"], ["Verify tracking instrumentation and data integrity first", "Segment by device, browser, geo, and traffic channel", "Analyze step-by-step funnel drop-offs to pinpoint payment or page failures"], ["A/B testing", "Stakeholder reporting"]],
  ["A/B Testing Fundamentals", "A/B Testing", "Intermediate", "technical", "Explain hypothesis formulation, control vs variant, sample size, and p-value in A/B testing.", ["A/B Testing", "Statistics"], ["Null hypothesis H0 vs alternative H1", "Sample size calculation based on statistical power and MDE", "p-value < 0.05 indicates observed lift unlikely due to random variance"], ["Type I and II errors", "Novelty effect"]],
  ["Star vs Snowflake Schema", "Data Modeling", "Intermediate", "technical", "Explain Star Schema vs Snowflake Schema in data warehousing.", ["Data Warehousing", "Modeling"], ["Star schema has denormalized dimension tables for faster joins", "Snowflake normalizes dimensions, saving storage at the expense of query complexity", "Fact tables store numerical metrics and foreign keys"], ["Fact vs Dimension", "dbt data modeling"]],
  ["UNION vs UNION ALL", "SQL", "Easy", "technical", "What is the operational difference between UNION and UNION ALL in SQL?", ["SQL"], ["UNION removes duplicate rows via an expensive sorting step", "UNION ALL retains all rows including duplicates and is significantly faster", "Use UNION ALL unless deduplication is strictly needed"], ["INTERSECT", "Column compatibility"]],
  ["Outlier Detection via IQR", "Pandas", "Intermediate", "practical", "How do you detect and handle outliers in Python using the IQR (Interquartile Range) method?", ["Pandas", "Statistics"], ["Compute Q1 (25th) and Q3 (75th) percentiles; IQR = Q3 - Q1", "Outliers are values < Q1 - 1.5*IQR or > Q3 + 1.5*IQR", "Decide to cap (winsorize), drop, or investigate based on domain"], ["Box plots", "Z-score"]],
  ["Executive Data Storytelling", "Communication", "Easy", "behavioral", "How do you present analytical findings to non-technical business executives?", ["Communication", "Data Storytelling"], ["Lead with the key business recommendation, not technical math", "Use clean visual charts with descriptive headlines", "Provide backup technical appendix for methodology"], ["Dashboard design", "Tailoring message"]],
  ["Cohort Retention Analysis", "Cohort Analysis", "Advanced", "technical", "What is cohort analysis and how do you build a customer retention heatmap?", ["Cohort Analysis", "Retention"], ["Group customers by acquisition month (cohorts)", "Track percentage of each cohort returning in months 1, 2, 3...", "Visualized as triangle heatmap showing retention decay over time"], ["Churn curves", "Product stickiness"]],
  ["Top N per Category in SQL", "SQL", "Intermediate", "practical", "Write a query to find the top 3 highest revenue products in each department.", ["SQL", "Window Functions"], ["Compute revenue per product", "Apply DENSE_RANK() OVER (PARTITION BY department ORDER BY revenue DESC)", "Filter rank <= 3 in outer query or CTE"], ["Ties handling", "Partitioning"]],
  ["Excel Conditional Formatting", "Excel", "Easy", "technical", "How do you use Excel conditional formatting to create visual heatmaps and highlight exceptions?", ["Excel"], ["Color scales for continuous numerical gradients", "Formula-based rules to highlight cells matching business criteria", "Data bars for in-cell comparative magnitude"], ["Pivot tables", "Excel dashboards"]],
  ["Data Quality Sanity Checks", "Data Quality", "Intermediate", "technical", "What sanity checks do you run on newly ingested data before building reports?", ["Data Quality", "ETL"], ["Row count reconciliation with source systems", "Null rate checks on primary keys and foreign keys", "Range and format validation on numeric and date columns", "Duplicate detection"], ["Great Expectations", "Schema drift"]],
  ["Central Limit Theorem", "Statistics", "Intermediate", "technical", "Explain the Central Limit Theorem and why it is essential for sample inference.", ["Statistics"], ["Distribution of sample means approaches normal as sample size increases, regardless of population shape", "Allows confidence intervals and hypothesis tests on real-world skewed data", "Requires independent observations, typically n >= 30"], ["Standard error", "Confidence intervals"]],
  ["Funnel Drop-Off Calculation", "Business Metrics", "Easy", "technical", "How do you calculate stage-by-stage drop-off and conversion rates in an analytics funnel?", ["Funnel Analysis", "CRO"], ["Track unique users completing each sequential step", "Conversion rate = Step N+1 users / Step N users", "Drop-off rate = 1 - Conversion rate", "Identifies highest leverage improvement areas"], ["Micro-conversions", "Drop-off visualization"]],
  ["CASE WHEN Statements", "SQL", "Intermediate", "technical", "How do you use CASE WHEN in SQL to bucket values and calculate conditional sums?", ["SQL"], ["CASE WHEN condition THEN result ELSE default END", "Bucketing continuous values into discrete tiers", "Conditional aggregation: SUM(CASE WHEN status='PAID' THEN amount ELSE 0 END)"], ["COALESCE", "NULLIF"]],
  ["Matplotlib vs Seaborn", "Python", "Easy", "technical", "Compare Matplotlib and Seaborn for exploratory data visualization in Python.", ["Visualization", "Python"], ["Matplotlib provides granular low-level control of canvas elements", "Seaborn provides high-level statistical plots with built-in styling", "Seaborn natively accepts Pandas DataFrames with hue parameters"], ["Plotly", "Pair plots"]],
  ["DAU/MAU Ratio", "Business Metrics", "Intermediate", "technical", "What is the DAU/MAU stickiness ratio and what does it indicate about product engagement?", ["Product Analytics", "KPIs"], ["Daily Active Users divided by Monthly Active Users", "Measures how frequently users return to the product within a month", "High ratio indicates strong user habit and product stickiness"], ["Defining active users", "Session length"]],
  ["Data Dictionaries & Governance", "Data Governance", "Easy", "technical", "Why is maintaining a data dictionary and clear metadata essential for analytics teams?", ["Data Governance", "Documentation"], ["Ensures single source of truth across conflicting department metrics", "Documents exact business logic and field definitions", "Prevents incorrect interpretations by business users"], ["dbt docs", "Data catalogs"]],
  ["Resolving Data Discrepancies", "Scenario Analysis", "Intermediate", "scenario", "Marketing says they generated 5,000 leads, but Sales says they only received 3,500. How do you investigate?", ["Problem Solving", "Investigation"], ["Audit metric definitions (MQL vs SQL)", "Check integration pipeline between Marketing software and CRM", "Inspect filter criteria, spam detection, and lead deduplication rules"], ["Pipeline reconciliation", "Stakeholder communication"]],
  ["Subqueries vs Joins", "SQL", "Easy", "technical", "Compare SQL subqueries vs JOINs in terms of readability and query execution performance.", ["SQL", "Optimization"], ["JOIN combines tables directly and is easily parallelized by optimizers", "Correlated subqueries execute row-by-row and can be very slow", "Modern optimizers rewrite many subqueries as joins automatically"], ["EXISTS vs IN", "Optimization plans"]],
  ["Simpson's Paradox", "Statistics", "Advanced", "technical", "Explain Simpson's Paradox with an example of how aggregated data can mislead analysts.", ["Statistics", "Paradoxes"], ["A trend apparent in subgroups reverses when data is aggregated together", "Caused by unequal group sizes and confounding variables", "Requires segmented analysis before drawing business conclusions"], ["Stratified sampling", "Confounders"]],
  ["Impactful Analytics Project", "Project Experience", "Intermediate", "behavioral", "Describe an analytical project you delivered that directly influenced business decisions.", ["Project Experience", "Communication"], ["Problem context and initial stakeholder question", "Analysis methodology, tools, and data sources used", "Concrete business outcome (cost reduction, conversion boost)"], ["Post-launch tracking", "Stakeholder feedback"]],
  ["Prioritizing Ad-Hoc Requests", "Behavioral", "Easy", "behavioral", "How do you manage a flood of ad-hoc analytics requests while delivering strategic projects?", ["Prioritization", "Stakeholder Management"], ["Evaluate business impact vs effort (ICE framework)", "Create self-service dashboards for repetitive requests", "Maintain transparent shared backlog reviewed with leadership"], ["SLA management", "Setting boundaries"]],
  ["Revenue Forecasting Methods", "Forecasting", "Intermediate", "technical", "What basic statistical approaches can you use to forecast next quarter's revenue?", ["Forecasting", "Time Series"], ["Moving averages and exponential smoothing", "Linear regression with seasonal decomposition", "Accounting for growth rate, seasonality, and holidays"], ["Prophet", "ARIMA basics"]]
];

const daQuestions = daTopics.map((t, idx) => ({
  id: `da-${String(idx + 1).padStart(3, '0')}`,
  role: "Data Analyst",
  category: t[1],
  difficulty: t[2],
  format: t[3],
  question: t[4],
  expectedSkills: t[5],
  evaluationPoints: t[6],
  followUpTopics: t[7]
}));
save('dataAnalyst.ts', 'DATA_ANALYST_QUESTIONS', daQuestions);

// 2. DATA SCIENTIST (35 questions)
const dsTopics = [
  ["Bias-Variance Tradeoff", "ML Fundamentals", "Easy", "technical", "Explain the Bias-Variance tradeoff in supervised machine learning.", ["ML Fundamentals"], ["High bias causes underfitting (model too simplistic)", "High variance causes overfitting (model learns noise)", "Goal is to minimize total generalization error"], ["Regularization", "Learning curves"]],
  ["ROC-AUC vs PR-AUC", "Evaluation Metrics", "Intermediate", "technical", "When should you prefer PR-AUC over ROC-AUC for evaluating classification models?", ["Model Evaluation"], ["ROC-AUC evaluates True Positive Rate vs False Positive Rate", "PR-AUC evaluates Precision vs Recall", "For highly imbalanced datasets, PR-AUC avoids false optimism"], ["F1-score", "Threshold tuning"]],
  ["Linear Regression Assumptions", "Linear Models", "Easy", "technical", "What are the core assumptions of Ordinary Least Squares (OLS) Linear Regression?", ["Statistics", "Regression"], ["Linear relationship between features and target", "Homoscedasticity (constant residual variance)", "Normality and independence of residuals", "No multicollinearity"], ["Residual plots", "VIF"]],
  ["L1 (Lasso) vs L2 (Ridge)", "Regularization", "Intermediate", "technical", "Compare L1 and L2 regularization. Why does L1 drive weights to exact zero?", ["Regularization"], ["L1 adds absolute penalty, L2 adds squared penalty", "L1 diamond constraint boundary intersects axes, performing feature selection", "L2 shrinks weights continuously without setting them to zero"], ["ElasticNet", "Weight decay"]],
  ["Random Forest vs Gradient Boosting", "Tree-Based Models", "Intermediate", "technical", "Compare Random Forest and Gradient Boosting (XGBoost/LightGBM).", ["Ensemble Learning"], ["Random Forest uses parallel Bagging to reduce variance", "Gradient Boosting trains sequential trees fitting residuals to reduce bias and variance", "Boosting is generally more accurate but sensitive to tuning"], ["Feature importance", "Early stopping"]],
  ["Feature Scaling Criteria", "Preprocessing", "Easy", "technical", "When is feature scaling (StandardScaler vs MinMaxScaler) necessary vs irrelevant in ML?", ["Feature Engineering"], ["Required for distance-based models (KNN, SVM, K-Means) and gradient descent models", "Irrelevant for tree-based models (Decision Trees, Random Forest, XGBoost)", "MinMax bounds to [0,1], Standard centers to mean=0, std=1"], ["Data leakage", "RobustScaler"]],
  ["K-Means Clustering", "Unsupervised", "Intermediate", "technical", "How does K-Means clustering work and how do you choose optimal K?", ["Clustering"], ["Iterative centroid assignment and re-computation until convergence", "Elbow method using WCSS (Inertia)", "Silhouette score evaluating cluster separation"], ["K-Means++", "DBSCAN"]],
  ["Principal Component Analysis", "Dimensionality Reduction", "Intermediate", "technical", "Explain PCA. What role do eigenvectors and eigenvalues play?", ["PCA"], ["Finds orthogonal axes maximizing feature variance", "Eigenvectors define direction of principal components; eigenvalues define variance magnitude", "Requires pre-scaled data"], ["Scree plot", "t-SNE vs PCA"]],
  ["Stratified K-Fold CV", "Validation", "Easy", "technical", "Why is Stratified K-Fold cross-validation essential for imbalanced classification?", ["Model Validation"], ["Maintains original class distribution across every training and validation fold", "Prevents folds with zero minority class instances", "Provides stable performance estimates"], ["TimeSeriesSplit", "Nested CV"]],
  ["Statistical Power & A/B Testing", "Statistics", "Intermediate", "technical", "Explain Type I error, Type II error, and statistical power in A/B testing.", ["A/B Testing", "Statistics"], ["Type I (alpha): False Positive (rejecting true null)", "Type II (beta): False Negative (failing to detect real effect)", "Power (1-beta): probability of finding a true effect (target 80%)"], ["p-values", "Sample size calculation"]],
  ["Imbalanced Classification Strategy", "Scenario Analysis", "Intermediate", "scenario", "You have a fraud detection dataset with 0.2% positive fraud cases. How do you approach it?", ["Imbalanced Learning"], ["Do not use accuracy; use PR-AUC or Recall at fixed Precision", "Techniques: SMOTE, class weighting (scale_pos_weight), threshold tuning", "Anomaly detection alternatives (Isolation Forest)"], ["Focal Loss", "Cost matrix"]],
  ["High-Cardinality Categoricals", "Feature Engineering", "Intermediate", "technical", "How do you encode categorical features with thousands of unique categories (e.g. ZIP code)?", ["Feature Engineering"], ["Target (Mean) encoding with smoothing to prevent leakage", "Frequency / Count encoding", "Entity embeddings via neural networks", "Avoid one-hot encoding"], ["CatBoost encoding", "Weight of Evidence"]],
  ["Model Explainability with SHAP", "Explainability", "Advanced", "technical", "Explain how SHAP (Shapley values) explains individual model predictions.", ["XAI", "SHAP"], ["Based on cooperative game theory calculating fair marginal feature contributions", "Provides local explanations and global feature importance with direction", "Model-agnostic KernelSHAP and optimized TreeSHAP"], ["LIME", "Feature attribution"]],
  ["Gradient Descent Variants", "Optimization", "Intermediate", "technical", "Compare Batch Gradient Descent, Stochastic (SGD), and Mini-batch Gradient Descent.", ["Optimization"], ["Batch uses entire dataset per step (slow, stable)", "SGD uses 1 random sample (fast, noisy, escapes local minima)", "Mini-batch uses small batches (32-256) balancing vectorization and stability"], ["Adam optimizer", "Learning rate schedule"]],
  ["Vanishing Gradient Problem", "Deep Learning", "Intermediate", "technical", "What causes vanishing gradients in deep neural networks and how is it solved?", ["Deep Learning"], ["Repeated multiplication of small gradients through sigmoid/tanh saturates layers", "Solved by ReLU/GELU activations, Batch Normalization, and Residual connections", "Proper weight initialization (He/Xavier)"], ["Exploding gradients", "Skip connections"]],
  ["TF-IDF vs Word Embeddings", "NLP", "Intermediate", "technical", "Compare TF-IDF and dense word embeddings (Word2Vec) for text feature extraction.", ["NLP"], ["TF-IDF reflects word frequency vs corpus rarity (sparse, no semantic relations)", "Word2Vec generates dense continuous vectors capturing semantic analogy", "Embeddings support vector math (king - man + woman = queen)"], ["BERT embeddings", "Cosine similarity"]],
  ["Time Series Stationarity", "Time Series", "Advanced", "technical", "Why is stationarity required for time series forecasting and how do you test it?", ["Time Series"], ["Stationarity means constant mean, variance, and autocorrelation over time", "Tested using Augmented Dickey-Fuller (ADF) test", "Achieved via differencing, log transformation, and seasonal adjustments"], ["ARIMA", "Lookahead bias"]],
  ["Recommendation Systems", "Recommenders", "Intermediate", "technical", "Compare Collaborative Filtering vs Content-Based Filtering for recommendations.", ["Recommenders"], ["Collaborative filtering uses user-item interaction matrix (Matrix Factorization/SVD)", "Content-based matches item attributes to user profile preferences", "Hybrid approaches overcome Cold Start problem"], ["Cold start problem", "Implicit feedback"]],
  ["Data Drift vs Concept Drift", "MLOps", "Intermediate", "technical", "What is the difference between Data (Covariate) Drift and Concept Drift in production?", ["MLOps"], ["Data Drift: distribution of inputs P(X) changes", "Concept Drift: relationship between inputs and target P(Y|X) changes", "Detected via Population Stability Index (PSI) and Kolmogorov-Smirnov test"], ["Model retraining", "Feature stores"]],
  ["Hyperparameter Tuning Techniques", "Hyperparameters", "Easy", "technical", "Compare Grid Search, Random Search, and Bayesian Optimization (Optuna).", ["Hyperparameters"], ["Grid Search evaluates exhaustive combinations (exponentially slow)", "Random Search samples randomly (more efficient coverage)", "Bayesian optimization uses probabilistic surrogate model to guide search"], ["Optuna pruning", "Early stopping"]],
  ["Parametric vs Non-Parametric Tests", "Statistics", "Intermediate", "technical", "When do you use parametric tests (t-test) vs non-parametric tests (Mann-Whitney)?", ["Statistics"], ["Parametric assumes underlying normal distribution (t-test, ANOVA)", "Non-parametric makes no distribution assumptions (Mann-Whitney, Wilcoxon)", "Use non-parametric when data is skewed or sample size is small"], ["Chi-Square test", "Bootstrapping"]],
  ["Support Vector Machines & Kernel Trick", "Machine Learning", "Intermediate", "technical", "How do SVMs work and what is the Kernel Trick?", ["SVM"], ["Finds maximum margin hyperplane separating classes", "Kernel trick projects data into higher dimensional space without explicit coordinate computation", "Common kernels: RBF, polynomial"], ["Slack variable C", "Support vectors"]],
  ["Data Leakage Diagnosis", "Troubleshooting", "Intermediate", "scenario", "Your model achieved 99.9% validation accuracy but fails miserably in production. What happened?", ["Data Leakage"], ["Target leakage: features contain future information not present at inference", "Preprocessing leakage: scaling or imputation fitted before train/test split", "Duplicates leaking across train and test sets"], ["Pipeline usage", "Leakage audits"]],
  ["Scikit-Learn Pipelines", "Clean Code", "Easy", "technical", "Why should you always encapsulate ML workflows in Scikit-Learn Pipelines?", ["Scikit-Learn"], ["Guarantees fit() is only executed on training data, eliminating leakage", "Simplifies model deployment into a single serializable artifact", "Enables seamless integration with GridSearchCV and cross-validation"], ["ColumnTransformer", "Custom transformers"]],
  ["Logistic Regression & Log-Odds", "Classification", "Easy", "technical", "How does Logistic Regression model probabilities and what is the logit function?", ["Logistic Regression"], ["Applies Sigmoid function: 1 / (1 + e^-z) mapping (-inf, inf) to (0, 1)", "Models log-odds: ln(p / (1-p)) = w*x + b", "Optimized using binary cross-entropy loss"], ["Odds ratios", "Softmax"]],
  ["Confusion Matrix Metrics", "Evaluation", "Easy", "technical", "Explain Precision, Recall, Specificity, and F1-Score in classification.", ["Evaluation"], ["Precision = TP / (TP + FP) — quality of positive predictions", "Recall = TP / (TP + FN) — quantity of actual positives captured", "F1 is harmonic mean of Precision and Recall", "Specificity = TN / (TN + FP)"], ["PR curve", "Macro vs Micro F1"]],
  ["Convolutional Neural Networks", "Deep Learning", "Intermediate", "technical", "Explain the role of Convolutional, Pooling, and Fully-Connected layers in CNNs.", ["CNN"], ["Convolutional layers apply learnable spatial filters to extract features", "Pooling layers downsample feature maps, providing translation invariance", "Fully-connected layers perform final classification"], ["Transfer learning", "Strides and padding"]],
  ["Transformer Self-Attention", "Deep Learning", "Advanced", "technical", "How does the Self-Attention mechanism work in Transformer models?", ["Transformers"], ["Calculates attention scores between all token pairs: Softmax(QK^T / sqrt(d_k)) * V", "Enables parallel sequence processing unlike recurrent unrolling in RNNs", "Captures long-range dependencies efficiently"], ["Multi-head attention", "Positional encoding"]],
  ["Framing Business Problems into ML", "Problem Formulation", "Intermediate", "scenario", "How do you translate a vague business objective ('improve sales') into an ML problem?", ["Problem Formulation"], ["Define measurable target variable (e.g. probability of lead closing)", "Identify historical training data and prediction cutoff point", "Establish offline evaluation metric directly linked to business revenue"], ["Uplift modeling", "Cost-benefit tradeoff"]],
  ["Maximum Likelihood Estimation", "Statistics", "Intermediate", "technical", "What is Maximum Likelihood Estimation (MLE) in statistical modeling?", ["Statistics"], ["Estimates model parameters that maximize probability of observing given data", "Maximizes log-likelihood for mathematical simplicity and numerical stability", "Foundation for linear regression and logistic regression parameters"], ["MAP estimation", "Bayesian inference"]],
  ["Auditing Model Bias and Fairness", "Ethics", "Intermediate", "technical", "How do you detect and mitigate algorithmic bias across demographic subgroups?", ["AI Ethics"], ["Audit model performance metrics across protected demographic slices", "Evaluate fairness metrics: Demographic Parity, Equalized Odds", "Mitigate via reweighting training samples or adversarial debiasing"], ["Fairlearn", "Proxy variables"]],
  ["Batch vs Real-Time Inference", "Deployment", "Intermediate", "technical", "Compare Batch inference vs Real-time online inference in production ML architecture.", ["Deployment", "MLOps"], ["Batch computes predictions offline on schedule, saving to DB (simple, high throughput)", "Real-time serves predictions via REST API in <100ms with fresh features", "Requires feature store and low-latency infrastructure"], ["Triton server", "Feature stores"]],
  ["End-to-End ML Deployment Experience", "Project Experience", "Intermediate", "behavioral", "Describe an end-to-end machine learning model you deployed to production.", ["Project Experience"], ["Problem definition and dataset collection", "Feature engineering, model selection, and offline validation", "Deployment method and monitored business impact"], ["Drift monitoring", "A/B test validation"]],
  ["Communicating Model Tradeoffs", "Communication", "Easy", "behavioral", "How do you explain the tradeoff between a complex black-box model and an interpretable model to executives?", ["Communication"], ["Frame in terms of business risk, regulatory needs, and financial uplift", "Demonstrate incremental gain of complex model vs explainability cost", "Showcase SHAP explanations as middle ground"], ["Stakeholder alignment", "Risk management"]],
  ["Singular Value Decomposition (SVD)", "Linear Algebra", "Advanced", "technical", "What is Singular Value Decomposition (SVD) and how is it used in dimensionality reduction?", ["Linear Algebra"], ["Decomposes matrix into U * Sigma * V^T", "Truncating to top k singular values yields optimal low-rank matrix approximation", "Applied in Latent Semantic Analysis and collaborative filtering"], ["Eigenvalue decomposition", "Low-rank approximation"]]
];

const dsQuestions = dsTopics.map((t, idx) => ({
  id: `ds-${String(idx + 1).padStart(3, '0')}`,
  role: "Data Scientist",
  category: t[1],
  difficulty: t[2],
  format: t[3],
  question: t[4],
  expectedSkills: t[5],
  evaluationPoints: t[6],
  followUpTopics: t[7]
}));
save('dataScientist.ts', 'DATA_SCIENTIST_QUESTIONS', dsQuestions);
