const fs = require('fs');
const path = require('path');
const targetDir = 'C:/sih/src/data/interviewQuestions/banks';

function save(filename, exportName, questions) {
  const code = `import { RoleQuestion } from '../types';\n\nexport const ${exportName}: RoleQuestion[] = ${JSON.stringify(questions, null, 2)};\n`;
  fs.writeFileSync(path.join(targetDir, filename), code, 'utf-8');
  console.log(`✓ ${filename} written (${questions.length} questions)`);
}

const androidTopics = [
  ["Activity Lifecycle & State Transitions", "Android Core", "Easy", "technical", "Explain the Android Activity Lifecycle callbacks: onCreate, onStart, onResume, onPause, onStop, onDestroy, onRestart.", ["Activity Lifecycle"], ["onCreate: one-time initialization, set layout; onStart: activity becomes visible; onResume: activity is in foreground receiving input", "onPause: partially obscured (dialog), commit unsaved data; onStop: fully hidden; onDestroy: final cleanup", "Configuration changes destroy and recreate Activity (triggering onDestroy followed by onCreate)"], ["onSaveInstanceState", "ViewModel"]],
  ["Jetpack Compose Declarative UI", "Jetpack Compose", "Intermediate", "technical", "How does Jetpack Compose declarative UI work and what is Recomposition?", ["Jetpack Compose"], ["UI is defined as functions annotated with @Composable that transform state into UI nodes", "Recomposition: Compose automatically re-executes composable functions whose observed state values have changed", "State hoisted using remember and mutableStateOf; skips recomposition for composables with unchanged inputs"], ["remember vs rememberSaveable", "State hoisting"]],
  ["Kotlin Coroutines & Flow in Android", "Kotlin Coroutines", "Intermediate", "technical", "How do Kotlin Coroutines and StateFlow handle asynchronous operations and UI state emission in Android?", ["Kotlin", "Coroutines"], ["Coroutines provide lightweight cooperative multitasking using suspend functions without blocking the main thread", "viewModelScope launches coroutines tied to ViewModel lifecycle, automatically cancelled on onCleared()", "StateFlow is a state-holder observable flow emitting the latest value to active UI collectors"], ["StateFlow vs SharedFlow", "Dispatchers.Main vs Dispatchers.IO"]],
  ["Android ViewModel & Surviving Rotations", "Architecture Components", "Easy", "technical", "Why does an Android Architecture Component ViewModel survive screen rotations while an Activity is destroyed?", ["ViewModel", "Lifecycle"], ["ViewModel is retained by the ViewModelStoreOwner across configuration changes", "Destroyed Activity releases its view hierarchy; newly created Activity reconnects to the existing retained ViewModel instance", "Cleared only when Activity finishes permanently (finish() called or user dismisses app) via onCleared()"], ["ViewModelProvider", "SavedStateHandle"]],
  ["Room Database & Migrations", "Room", "Intermediate", "technical", "Explain Room persistence library: @Entity, @Dao, @Database, and how to execute schema migrations.", ["Room", "Database"], ["@Entity maps data classes to SQLite tables; @Dao provides CRUD and query methods using compile-time checked SQL", "@Database declares entities and version number", "Room Migration: implement Migration(fromVersion, toVersion) with executeSQL statements, registered in database builder"], ["AutoMigration", "TypeConverters"]],
  ["Retrofit & OkHttp Networking", "Networking", "Easy", "technical", "How do Retrofit and OkHttp work together to consume REST APIs in Android?", ["Retrofit", "OkHttp"], ["Retrofit turns HTTP API into a Java/Kotlin interface using annotations (@GET, @POST, @Path, @Body)", "Uses converters (Moshi, Gson) to automatically deserialize JSON response into Kotlin data classes", "OkHttp acts as underlying HTTP client handling connection pooling, interceptors, timeouts, and caching"], ["OkHttp Interceptors", "Moshi vs Gson"]],
  ["OkHttp Interceptors (Auth & Logging)", "Networking", "Intermediate", "practical", "How do you implement an OkHttp Auth Interceptor to automatically attach JWT Bearer tokens to all outgoing requests?", ["OkHttp", "Security"], ["Implement Interceptor interface and override intercept(Chain chain)", "val request = chain.request().newBuilder().addHeader('Authorization', 'Bearer $token').build()", "Call chain.proceed(request); can also handle 401 Unauthorized by refreshing token and retrying original request"], ["HttpLoggingInterceptor", "Token refresh with Authenticator"]],
  ["WorkManager for Deferrable Tasks", "Background Processing", "Intermediate", "technical", "Why is WorkManager the recommended solution for persistent, guaranteed background tasks in Android?", ["WorkManager", "Background Processing"], ["Guarantees task execution even if app is killed, device restarts, or app is in background", "Respects Android Doze mode, battery saver, and network constraints (Constraints.Builder.setRequiredNetworkType)", "Uses JobScheduler on API 23+ and alarm/broadcast fallbacks on older versions"], ["PeriodicWorkRequest", "OneTimeWorkRequest with Chaining"]],
  ["Services: Foreground vs Background vs Bound", "Android Core", "Intermediate", "technical", "Compare Foreground Services, Background Services, and Bound Services in Android.", ["Services"], ["Foreground Service performs operations noticeable to user (music playback, active navigation); MUST display a persistent ongoing notification", "Background Service: heavily restricted in modern Android (API 26+); OS restricts background execution when app is not in foreground (use WorkManager instead)", "Bound Service: allows components (activities) to bind and interact via IPC (client-server interface) using Binder"], ["Foreground Service Notifications", "JobIntentService"]],
  ["Android BroadcastReceivers", "Android Core", "Easy", "technical", "What is a BroadcastReceiver and what is the difference between static and dynamic registration?", ["BroadcastReceiver"], ["Component that listens for system-wide broadcast announcements (Airplane mode, Battery low, Network change)", "Static registration: declared in AndroidManifest.xml (limited in modern Android to protect battery)", "Dynamic registration: registered in code via registerReceiver() during onStart/onResume and unregistered in onStop/onPause"], ["LocalBroadcastManager", "Implicit broadcast restrictions"]],
  ["ContentProviders & Data Sharing", "Android Core", "Intermediate", "technical", "What is a ContentProvider and how does ContentResolver allow cross-app data sharing in Android?", ["ContentProvider"], ["Standard interface for securely sharing structured data between different applications (Contacts, MediaStore)", "ContentResolver queries ContentProvider using content URIs (content://authority/path/id)", "Enforces read/write permissions at the URI level"], ["ContentResolver", "URI permissions"]],
  ["Fragments & Fragment Lifecycle", "Android Core", "Easy", "technical", "Explain the Fragment lifecycle and why a Fragment has two distinct lifecycles (Fragment vs View lifecycle).", ["Fragments"], ["Fragment lifecycle: onAttach, onCreate, onCreateView, onViewCreated, onViewStateRestored, onStart, onResume, onPause, onStop, onDestroyView, onDestroy, onDetach", "Fragment view can be destroyed (onDestroyView) while Fragment instance remains in memory (in backstack)", "Observe LiveData / StateFlow using viewLifecycleOwner rather than fragment this to avoid memory leaks"], ["viewLifecycleOwner", "FragmentTransaction"]],
  ["RecyclerView vs ListView: ViewHolder Pattern", "UI Components", "Easy", "technical", "Why is RecyclerView significantly more performant than legacy ListView? Explain the ViewHolder pattern.", ["RecyclerView", "UI Performance"], ["ListView repeatedly called findViewById() inside getView() on every scroll, causing severe jank", "RecyclerView enforces ViewHolder pattern, caching view references to avoid expensive findViewById lookups", "Recycles off-screen views for newly visible rows; decouples layout arrangement via LayoutManager and animations via ItemAnimator"], ["DiffUtil", "ListAdapter"]],
  ["DiffUtil & ListAdapter in RecyclerView", "UI Components", "Intermediate", "technical", "How does DiffUtil calculate list item differences and prevent full-list reloads in RecyclerView?", ["DiffUtil", "RecyclerView"], ["Uses Eugene Myers' difference algorithm to compute minimal number of updates between old and new lists", "Dispatches fine-grained update events (notifyItemInserted, notifyItemRemoved, notifyItemRangeChanged) instead of notifyDataSetChanged()", "ListAdapter automatically calculates diffs on a background thread using AsyncListDiffer"], ["AsyncListDiffer", "Myers algorithm"]],
  ["Dependency Injection with Hilt", "Dependency Injection", "Intermediate", "technical", "How does Hilt simplify Dagger dependency injection in Android applications?", ["Hilt", "Dagger"], ["Built on top of Dagger with standard Android-specific component containers (@HiltAndroidApp, @AndroidEntryPoint)", "Provides predefined scopes tied to Android lifecycle (@Singleton, @ActivityScoped, @ViewModelScoped)", "Generates boilerplate Dagger component code at compile time with zero reflection runtime overhead"], ["@Inject constructor", "@Module and @Provides"]],
  ["Android Jetpack Navigation Component", "Navigation", "Easy", "technical", "Explain Navigation Graph, NavHostFragment, and Safe Args in Jetpack Navigation.", ["Navigation Component"], ["NavGraph is an XML or Compose resource mapping all application destinations and actions", "NavHostFragment is an empty container displaying destinations from navigation graph", "Safe Args Gradle plugin generates type-safe directions classes preventing bundle key mismatch runtime crashes"], ["Deep linking with Navigation", "Back stack management"]],
  ["Android Permissions & Scoped Storage", "Storage & Security", "Intermediate", "technical", "What is Scoped Storage in Android (API 29+) and how does it protect user privacy?", ["Scoped Storage", "Android Security"], ["Eliminates broad READ_EXTERNAL_STORAGE permission giving apps access to entire file system", "Apps have unrestricted access only to their own private app-specific directories (context.getExternalFilesDir())", "Access to shared media files (Photos, Audio, Videos) must use MediaStore API; non-media files require Storage Access Framework (SAF) system picker"], ["MediaStore API", "Storage Access Framework"]],
  ["Clean Architecture & MVVM in Android", "Architecture", "Intermediate", "technical", "How do you structure an Android app using Clean Architecture (Data, Domain, Presentation layers)?", ["Clean Architecture", "MVVM"], ["Presentation: Activities, Composables, ViewModels, and UI state", "Domain: Use Cases (Interactors) and pure business logic entities, free from Android framework dependencies", "Data: Repositories, Room database, and Retrofit network datasources implementing Domain repository interfaces"], ["Use Cases", "Repository Pattern"]],
  ["Android Keystore & Cryptography", "Security", "Intermediate", "technical", "How does the Android Keystore system protect cryptographic keys against extraction even on rooted devices?", ["Android Keystore", "Security"], ["Generates and stores cryptographic keys inside a hardware-backed security module (TEE - Trusted Execution Environment or StrongBox)", "Key material never enters the application memory space; encryption/decryption operations occur inside secure hardware", "Can require biometric user authentication before key is unlocked"], ["EncryptedSharedPreferences", "Hardware-backed keys"]],
  ["Handling App Process Death & SavedStateHandle", "State Management", "Intermediate", "technical", "What is Android Process Death and how does SavedStateHandle restore state when ViewModel memory is wiped?", ["Process Death", "SavedStateHandle"], ["When app is in background, Android OS may kill the entire app process to free RAM for foreground apps", "When user returns, OS recreates Activity and ViewModel, but in-memory variables are reset to null", "SavedStateHandle persists key-values through process death via OS bundle, restoring initial state automatically"], ["onSaveInstanceState vs ViewModel", "Low-memory killer"]],
  ["LeakCanary & Android Memory Leaks", "Performance", "Intermediate", "practical", "How does LeakCanary detect memory leaks in Android and what is a GC Root path?", ["Memory Management", "LeakCanary"], ["Watches destroyed Activity and Fragment view objects; if not garbage collected after 5 seconds, triggers heap dump (.hprof)", "Analyzes heap dump using Shark library to find shortest path of strong references from a GC Root to the leaking object", "Common culprit: static variables, non-static inner classes, or lingering Coroutine jobs holding Activity context"], ["GC Roots", "Context leaks"]],
  ["Android App Startup Optimization", "Performance", "Intermediate", "technical", "How do you optimize Android App Cold Start time and leverage the Jetpack App Startup library?", ["App Startup", "Performance"], ["Cold start: OS creates new process, initializes Application class, inflates initial Activity layout", "App Startup library initializes multiple content-provider libraries within a single shared ContentProvider, reducing initialization overhead", "Defer non-critical SDK initializations to background coroutines after the first frame is rendered"], ["Baseline Profiles", "Cold vs Warm start"]],
  ["Baseline Profiles in Android", "Performance", "Advanced", "technical", "What are Android Baseline Profiles and how do they eliminate JIT compilation jank on first run?", ["Baseline Profiles", "AOT Compilation"], ["Specifies critical user journeys (app launch, scrolling home feed) pre-compiled into machine code (AOT) upon app installation", "Eliminates Just-In-Time (JIT) compilation interpretation during runtime", "Improves app startup speed by up to 40% and reduces frame drops on low-end devices"], ["AOT vs JIT", "Macrobenchmark"]],
  ["Android IPC: Binder & AIDL", "Android Internals", "Advanced", "technical", "How does Android Inter-Process Communication (IPC) work using the Linux Binder driver and AIDL?", ["Binder", "IPC"], ["Android isolates processes using Linux UID security; standard memory sharing is blocked", "Binder kernel driver maps shared memory buffers between client and server processes for ultra-fast IPC with single data copy", "AIDL (Android Interface Definition Language) generates Java/Kotlin client proxy and server stub implementing IPC communication"], ["Messenger vs AIDL", "Parcelable"]],
  ["Parcelable vs Serializable in Android", "Android Core", "Easy", "technical", "Why is Parcelable strongly preferred over Java Serializable for passing data in Android Intents/Bundles?", ["Parcelable", "Performance"], ["Serializable is standard Java interface using heavy reflection to serialize object graphs (slow, creates many temporary objects)", "Parcelable is Android-specific interface where developer or @Parcelize explicitly defines binary serialization code", "Parcelable is up to 10x faster and highly optimized for Android IPC Binder transactions"], ["@Parcelize annotation", "Intent extras"]],
  ["Battery Optimization & Doze Mode", "Performance", "Intermediate", "technical", "What is Android Doze Mode and how does it restrict background network access, wakelocks, and alarms?", ["Doze Mode", "Battery"], ["When device is unplugged, stationary, and screen is off, OS enters Doze mode", "Suspends network access, ignores partial wakelocks, and defers standard alarms and JobScheduler jobs to periodic maintenance windows", "High-priority FCM push messages wake device briefly for critical time-sensitive events"], ["Maintenance windows", "AlarmManager setExactAndAllowWhileIdle"]],
  ["ProGuard & R8 Code Shrinking", "Build & Optimization", "Easy", "technical", "What does R8 compiler do during release builds (Shrinking, Optimization, Obfuscation, Inlining)?", ["R8", "ProGuard"], ["Code shrinking: detects and removes unused classes, methods, and fields", "Resource shrinking: strips unused images, strings, and XML layouts", "Obfuscation: renames classes and fields to short meaningless names (a, b, c) to deter reverse engineering", "Inlining: merges short methods and flattens class hierarchies to improve execution efficiency"], ["keep rules (proguard-rules.pro)", "Mapping.txt"]],
  ["Custom Views & Custom Drawing in Android", "Custom Views", "Intermediate", "technical", "Explain onMeasure, onLayout, and onDraw callbacks when implementing a custom View in Android.", ["Custom Views"], ["onMeasure: computes desired width and height of view based on MeasureSpec constraints from parent", "onLayout: positions child views (used when subclassing ViewGroup)", "onDraw: renders visual elements using Canvas and Paint objects; avoid object allocations (new Paint()) inside onDraw to prevent GC jank during animations"], ["MeasureSpec", "Canvas and Paint"]],
  ["Android Dynamic Feature Modules", "Modularization", "Advanced", "technical", "How do Android Dynamic Feature Modules (Play Feature Delivery) download features on-demand?", ["Modularization", "App Bundles"], ["App is split into base module and dynamic feature modules (.dfm)", "Users download a minimal base APK; heavy optional features (e.g. AR camera, onboarding video) are downloaded on-demand via SplitInstallManager", "Significantly lowers initial download barrier and install friction"], ["SplitInstallManager", "On-demand modules"]],
  ["Testing in Android: Unit vs Instrumented Tests", "Testing", "Easy", "technical", "Compare Local Unit Tests (test/ directory) and Instrumented Tests (androidTest/ directory) in Android.", ["Testing", "Android"], ["Local Unit Tests run on host machine JVM with Mockito/MockK and Roboelectric (fast, no device required)", "Instrumented Tests run on real Android device or emulator with access to Android framework APIs, Context, and databases", "Use unit tests for ViewModels, Use Cases, and Repositories; instrumented tests for Room DAOs and UI flows with Espresso/Compose Test"], ["Robolectric", "ComposeTestRule"]],
  ["Accessibility in Jetpack Compose", "Accessibility", "Easy", "practical", "How do you add semantic accessibility properties to custom Composables using Modifier.semantics?", ["Jetpack Compose", "Accessibility"], ["Modifier.semantics { contentDescription = 'Profile picture'; role = Role.Button }", "Merges child semantics using mergeDescendants = true so TalkBack reads complex card layouts as a single accessible item", "Ensures touch targets meet minimum 48.dp requirements"], ["Semantics tree", "TalkBack"]],
  ["Troubleshooting Android ANR (Application Not Responding)", "Performance", "Intermediate", "scenario", "Users report frequent ANRs in production. What causes ANRs and how do you trace them?", ["ANR", "Troubleshooting"], ["ANR triggered when main thread is blocked for >5 seconds by input events or >200ms by broadcast receiver", "Causes: synchronous database queries, network calls, disk I/O, or thread deadlock on main thread", "Inspect /data/anr/traces.txt or Google Play Console Android Vitals to identify stack trace of main thread at time of ANR"], ["traces.txt", "Android Vitals"]],
  ["Architecting a Complex Android App", "Project Experience", "Intermediate", "behavioral", "Describe an enterprise Android application you architected from scratch. What Jetpack libraries did you choose?", ["Architecture", "Communication"], ["Multi-module architecture (feature-by-layer or feature-by-module)", "Tech stack: Jetpack Compose, Hilt, Coroutines/Flow, Room, Retrofit", "Achieving >99.7% crash-free sessions and high test coverage"], ["Modularization", "Lessons learned"]],
  ["Migrating Legacy Android App to Jetpack Compose", "Modernization", "Intermediate", "behavioral", "How do you incrementally migrate a large legacy XML-based Android application to Jetpack Compose?", ["Jetpack Compose", "Migration"], ["Do not rewrite entire app at once; migrate screen-by-screen starting with isolated bottom-leaf custom views or new features", "Use ComposeView inside existing XML layouts to host Compose components", "Use AndroidView inside Composable screens to host legacy XML views (e.g. MapView, WebView)"], ["ComposeView", "AndroidView interop"]],
  ["Future of Android Development", "Modern Trends", "Easy", "technical", "What is Kotlin Multiplatform (KMP) and how does it compare to Flutter and React Native for Android teams?", ["KMP", "Modern Android"], ["KMP allows sharing 100% of business logic, networking, database, and state management code across Android, iOS, Desktop, and Web in pure Kotlin", "Renders UI using 100% native platforms (Jetpack Compose on Android, SwiftUI on iOS) or Compose Multiplatform", "Unlike Flutter or React Native, it does not impose a foreign runtime engine or cross-platform UI bridge"], ["Compose Multiplatform", "KMP vs Flutter"]]
];

const androidQuestions = androidTopics.map((t, idx) => ({
  id: `andr-${String(idx + 1).padStart(3, '0')}`,
  role: "Android Developer",
  category: t[1],
  difficulty: t[2],
  format: t[3],
  question: t[4],
  expectedSkills: t[5],
  evaluationPoints: t[6],
  followUpTopics: t[7]
}));
save('androidDeveloper.ts', 'ANDROID_DEVELOPER_QUESTIONS', androidQuestions);
