const fs = require('fs');
const path = require('path');
const targetDir = 'C:/sih/src/data/interviewQuestions/banks';

function save(filename, exportName, questions) {
  const code = `import { RoleQuestion } from '../types';\n\nexport const ${exportName}: RoleQuestion[] = ${JSON.stringify(questions, null, 2)};\n`;
  fs.writeFileSync(path.join(targetDir, filename), code, 'utf-8');
  console.log(`✓ ${filename} written (${questions.length} questions)`);
}

const mlTopics = [
  ["MLOps Lifecycle", "MLOps", "Easy", "technical", "Explain the end-to-end MLOps lifecycle from data ingestion to continuous model retraining.", ["MLOps"], ["Data collection, validation, feature store", "Model training, hyperparameter tuning, experiment tracking", "CI/CD model registry, deployment, and drift monitoring"], ["MLflow", "Kubeflow"]],
  ["Feature Stores", "Architecture", "Intermediate", "technical", "What is a Feature Store (e.g. Feast) and why is it crucial for preventing training-serving skew?", ["Feature Store", "Architecture"], ["Central repository for curated ML features", "Guarantees exact same feature calculation online (low latency) and offline (batch training)", "Provides point-in-time joins to eliminate data leakage"], ["Feast", "Training-serving skew"]],
  ["Model Registry & Versioning", "MLOps", "Easy", "technical", "How does MLflow Model Registry manage model stage transitions (Staging -> Production)?", ["MLflow", "Versioning"], ["Tracks model artifacts, metrics, and parameters per run", "Semantic versioning and stage transitions (Staging, Production, Archived)", "Enables automated governance and rollback"], ["Weights & Biases", "Model lineage"]],
  ["Model Quantization & Pruning", "Optimization", "Advanced", "technical", "Explain model quantization (INT8 vs FP16) and weight pruning for reducing inference latency.", ["Model Optimization"], ["Quantization reduces parameter bit precision with minimal accuracy loss", "Pruning zeros out non-critical weights to produce sparse networks", "Accelerates inference on edge and cloud GPUs/TPUs"], ["ONNX Runtime", "TensorRT"]],
  ["Canary vs Blue-Green Deployments", "Deployment", "Intermediate", "technical", "Compare Canary vs Blue-Green deployment strategies for machine learning models.", ["Deployment", "DevOps"], ["Canary routes small % of live traffic to new model, monitoring error/drift before scaling", "Blue-Green maintains two identical environments, instantly switching traffic on validation", "Canary minimizes blast radius of poorly performing models"], ["Shadow deployments", "A/B testing"]],
  ["Monitoring Data & Model Drift", "Monitoring", "Intermediate", "technical", "How do you automate data drift and concept drift detection in production pipelines?", ["Monitoring", "Evidently AI"], ["Calculate statistical distance (PSI, Wasserstein, KS-test) between training baseline and inference traffic", "Alert on significant distribution shifts before model performance degrades", "Trigger automated retraining DAG in Airflow"], ["Evidently AI", "Great Expectations"]],
  ["Distributed Training with DataParallel", "Distributed ML", "Advanced", "technical", "Explain DataParallel vs DistributedDataParallel (DDP) in PyTorch for multi-GPU training.", ["PyTorch", "Distributed Training"], ["DataParallel uses single-process multi-threading with GIL overhead and GPU 0 bottleneck", "DDP launches separate process per GPU with ring-AllReduce gradient synchronization", "DDP scales efficiently across multiple nodes"], ["Ring AllReduce", "Model parallelism"]],
  ["ONNX Runtime Deployment", "Serving", "Intermediate", "technical", "What is Open Neural Network Exchange (ONNX) and why is it used in production inference?", ["ONNX", "Serving"], ["Open format representing machine learning models across frameworks (PyTorch, TensorFlow, Scikit-learn)", "ONNX Runtime optimizes graph execution and hardware acceleration (CUDA, TensorRT)", "Eliminates Python runtime dependency at inference"], ["TorchScript", "Triton Server"]],
  ["CI/CD for ML (CT - Continuous Training)", "CI/CD", "Intermediate", "technical", "What does Continuous Training (CT) mean in advanced MLOps architectures?", ["CI/CD", "Automation"], ["Automated pipeline that continuously retrains models when new data arrives or drift is detected", "Validates candidate model against production champion model before promotion", "Fully automated artifact push to registry without manual intervention"], ["GitHub Actions", "CML"]],
  ["Containerizing Models with Docker", "Docker", "Easy", "technical", "How do you package an ML model into a lightweight Docker image for production serving?", ["Docker", "Deployment"], ["Multi-stage build with minimal base image (python:3.11-slim)", "Pre-install dependencies and copy serialized model weights", "Serve using FastAPI or Triton with health check probes"], ["gunicorn/uvicorn", "Docker security"]],
  ["Triton Inference Server", "Serving", "Advanced", "technical", "What features make NVIDIA Triton Inference Server superior to a standard FastAPI wrapper?", ["Triton", "Inference"], ["Dynamic batching grouping concurrent requests for high GPU utilization", "Concurrent model execution across multi-GPU instances", "Supports multiple frameworks (TensorRT, ONNX, PyTorch, OpenVINO)"], ["Dynamic batching", "Model ensembles"]],
  ["Feature Leakage in Pipelines", "Data Engineering", "Intermediate", "scenario", "How do you ensure rolling window features (e.g. 30-day user spend) do not leak future information during training?", ["Data Leakage", "Feature Engineering"], ["Use point-in-time correctness: features computed strictly before timestamp of event", "Avoid computing aggregations across entire historical dataset at once", "Validate feature generation in unit tests with simulated time jumps"], ["Point-in-time joins", "Feast"]],
  ["Handling GPU Out of Memory (OOM)", "Deep Learning", "Intermediate", "scenario", "Your PyTorch neural network crashes with CUDA out of memory during training. How do you resolve it?", ["PyTorch", "Troubleshooting"], ["Reduce batch size and implement gradient accumulation to simulate effective batch size", "Use Mixed Precision training (torch.cuda.amp.autocast)", "Enable gradient checkpointing to recompute activations during backward pass"], ["Gradient accumulation", "torch.cuda.empty_cache()"]],
  ["Airflow DAGs for ML Workflows", "Orchestration", "Intermediate", "technical", "How do you design an Apache Airflow DAG for an automated daily model training pipeline?", ["Airflow", "Orchestration"], ["Tasks: data extraction, validation, feature engineering, model training, evaluation, registration", "Use Airflow operators or KubernetesPodOperator for isolated execution", "Set retries, SLA alerts, and conditional branching based on validation results"], ["KubernetesPodOperator", "Prefect vs Airflow"]],
  ["Shadow Deployments", "Deployment", "Intermediate", "technical", "What is a Shadow Deployment and what are its advantages for high-risk ML models?", ["Deployment"], ["New model receives copy of live production traffic in parallel without serving results to users", "Compare latency, throughput, and predictions against live champion model risk-free", "Ensures stability before cutting over user-facing traffic"], ["Dark launching", "Canary comparison"]],
  ["Model Interpretability at Scale", "Explainability", "Intermediate", "technical", "How do you generate model explanations (SHAP) efficiently for millions of predictions?", ["XAI", "Performance"], ["Use TreeSHAP (polynomial time for tree models) instead of KernelSHAP (exponential)", "Precompute background sample distributions", "Calculate global feature importances offline and log local SHAP only on flagged edge cases"], ["TreeSHAP", "Model cards"]],
  ["Kafka Streaming Features", "Streaming", "Advanced", "technical", "How do you build a real-time streaming feature pipeline using Kafka and Flink for ML models?", ["Kafka", "Streaming"], ["Ingest event streams into Kafka topics", "Apache Flink performs stateful tumbling/sliding window aggregations", "Sink aggregated features into low-latency cache (Redis/Feast) for online inference"], ["Apache Flink", "Event-time processing"]],
  ["Cost Optimization for GPU Clusters", "Cloud", "Intermediate", "technical", "How do you optimize cloud compute costs when training large ML models on AWS/GCP?", ["Cloud", "Cost Optimization"], ["Use Spot/Preemptible instances with checkpointing (saving model state every epoch)", "Right-size GPU instances according to VRAM requirements", "Auto-scale cluster to zero when training jobs complete"], ["Spot instances", "DeepSpeed"]],
  ["DVC (Data Version Control)", "Versioning", "Easy", "technical", "What problem does DVC solve in machine learning projects and how does it integrate with Git?", ["DVC", "Versioning"], ["Git tracks code, DVC tracks large datasets and model weights using pointers (.dvc files)", "Stores actual data artifacts in cloud storage (S3, GCS)", "Ensures full reproducibility of data + code + model checkpoints"], ["Git LFS", "DVC pipelines"]],
  ["Loss Function Selection", "ML Fundamentals", "Easy", "technical", "How do you choose between MSE, MAE, Huber Loss, and Cross-Entropy for different ML tasks?", ["ML Fundamentals"], ["MSE penalizes large outliers heavily (squared error)", "MAE is robust to outliers (linear error)", "Huber loss combines best of MSE for small errors and MAE for large errors", "Cross-entropy for probability distributions in classification"], ["Focal loss", "Quantile loss"]],
  ["Serving Models on Kubernetes", "Kubernetes", "Intermediate", "technical", "How do you configure KNative or Seldon Core for autoscaling ML model deployments on Kubernetes?", ["Kubernetes", "Serving"], ["Autoscale based on request concurrency or custom GPU metrics (HPA)", "Scale-to-zero when idle to save infrastructure costs", "Manage traffic splitting for canary rollouts"], ["KServe", "HPA custom metrics"]],
  ["Model Validation Gates in CI", "CI/CD", "Intermediate", "technical", "What automated quality gates must a trained model pass before being promoted to the Model Registry?", ["CI/CD", "Governance"], ["Offline metric threshold (e.g. F1 > 0.85 and must outperform current production model)", "Inference latency benchmark (<50ms under load)", "Bias and fairness checks across demographic groups", "Vulnerability scanning of container dependencies"], ["Model cards", "Automated benchmarking"]],
  ["Mixed Precision Training", "Optimization", "Intermediate", "technical", "How does Automatic Mixed Precision (AMP) accelerate training and reduce VRAM usage in PyTorch?", ["PyTorch", "Hardware"], ["Uses FP16 for computationally heavy matrix operations and FP32 for sensitive accumulations", "GradScaler prevents underflow of small gradients", "Doubles throughput on modern Tensor Core GPUs"], ["torch.cuda.amp", "Bfloat16"]],
  ["Data Quality with Great Expectations", "Data Engineering", "Easy", "technical", "How do you integrate Great Expectations into an ML pipeline to catch data anomalies?", ["Data Quality"], ["Define expectation suites (expect_column_values_to_not_be_null, expect_values_to_be_between)", "Validate raw data before feature engineering", "Fail pipeline early if validation suite fails, preventing corrupted model retraining"], ["Data profiling", "CI validation"]],
  ["Cold Start in Microservice Inference", "Serving", "Intermediate", "technical", "How do you mitigate cold start latency when deploying ML models in serverless containers?", ["Serverless", "Performance"], ["Pre-warm model weights into memory during container initialization", "Keep minimum number of warm container instances", "Use lightweight runtimes like ONNX rather than full PyTorch"], ["AWS Lambda snapstart", "Container warmers"]],
  ["Hyperparameter Tuning with Ray Tune", "Optimization", "Intermediate", "technical", "How does Ray Tune distribute hyperparameter search across multiple worker nodes?", ["Ray", "Distributed Computing"], ["Schedules trials asynchronously across cluster workers", "Implements early stopping algorithms (ASHA) to kill unpromising trials", "Integrates with Optuna, Hyperopt, and PyTorch"], ["ASHA scheduler", "Ray cluster"]],
  ["Database Selection for ML", "Architecture", "Easy", "technical", "How do you choose storage for ML: Data Lake (S3), Data Warehouse (Snowflake), and Vector DB (Pinecone)?", ["Architecture"], ["Data Lake for raw unstructured files, images, and big data dumps", "Data Warehouse for structured analytics and batch feature queries", "Vector DB for high-dimensional embedding similarity search (RAG)"], ["Delta Lake", "Iceberg"]],
  ["Feature Importance vs Permutation Importance", "Explainability", "Intermediate", "technical", "Why can Gini feature importance in Random Forests be misleading, and why is Permutation Importance better?", ["Explainability"], ["Gini importance is biased toward high-cardinality numerical features", "Permutation importance measures drop in validation metric when feature is randomly shuffled", "Reflects true generalization impact on unseen data"], ["SHAP", "Feature selection"]],
  ["A/B Testing Production ML Models", "Experimentation", "Intermediate", "technical", "How do you design an online A/B test between an existing model and a newly trained model?", ["Experimentation"], ["Hash user ID to consistently route traffic 50/50 between Model A and Model B", "Measure primary business metric (conversion rate, click-through rate) over statistical duration", "Monitor system health metrics (latency, error rate) concurrently"], ["Washout period", "Sample ratio mismatch"]],
  ["Embeddings Pipeline Architecture", "Feature Engineering", "Intermediate", "technical", "How do you build a batch and real-time embedding generation pipeline using sentence-transformers?", ["Embeddings", "Architecture"], ["Tokenize text and generate dense vector embeddings", "Store embeddings in Vector DB with metadata filtering", "Batch generate for existing catalog; real-time generate on user queries"], ["Cosine similarity", "HNSW indexing"]],
  ["ML System Failure Handling", "Reliability", "Intermediate", "scenario", "Your primary recommendation model crashes under peak holiday traffic. What fallback architecture triggers?", ["Resilience", "System Design"], ["Circuit breaker catches timeout and falls back to cached pre-computed popular items", "Graceful degradation without throwing 500 error to user", "Automatic scaling and alert notification to on-call engineer"], ["Fallback strategies", "Resilience4j"]],
  ["Model Pruning vs Distillation", "Optimization", "Advanced", "technical", "Compare Knowledge Distillation vs Weight Pruning for model compression.", ["Model Compression"], ["Distillation trains small student model to mimic logits of large teacher model", "Pruning removes redundant weights/neurons from existing model architecture", "Distillation often achieves better performance retention at high compression ratios"], ["Teacher-student networks", "Sparse models"]],
  ["Production MLOps Project Experience", "Project Experience", "Intermediate", "behavioral", "Describe an ML pipeline you engineered. How did you automate deployment and ensure zero downtime?", ["Project Experience", "Communication"], ["Architecture explanation from data to serving", "CI/CD and validation gates used", "Monitoring, rollback strategy, and business impact"], ["Lessons learned", "Scalability bottlenecks"]],
  ["Cross-Functional Collaboration", "Behavioral", "Easy", "behavioral", "How do you resolve disagreements between Data Scientists wanting complex models and Software Engineers wanting low latency?", ["Collaboration", "Stakeholder Management"], ["Establish clear SLA boundaries (latency budget, memory limit)", "Quantify business revenue lift vs cloud infrastructure cost", "Explore optimization (quantization, distillation) as common ground"], ["SLA agreements", "Latency budgets"]],
  ["Future of MLOps & LLMOps", "Modern Trends", "Easy", "technical", "How has LLMOps changed the traditional MLOps landscape?", ["LLMOps", "Modern AI"], ["Shift from training models from scratch to fine-tuning and prompt engineering", "Evaluation shifts from simple F1 to LLM-as-a-judge, hallucination detection, and RAG evaluation", "Vector DBs and prompt registries become core infrastructure"], ["RAG pipelines", "LangSmith"]]
];

const mlQuestions = mlTopics.map((t, idx) => ({
  id: `ml-${String(idx + 1).padStart(3, '0')}`,
  role: "Machine Learning Engineer",
  category: t[1],
  difficulty: t[2],
  format: t[3],
  question: t[4],
  expectedSkills: t[5],
  evaluationPoints: t[6],
  followUpTopics: t[7]
}));
save('mlEngineer.ts', 'ML_ENGINEER_QUESTIONS', mlQuestions);
