const fs = require('fs');
const path = require('path');
const targetDir = 'C:/sih/src/data/interviewQuestions/banks';

function save(filename, exportName, questions) {
  const code = `import { RoleQuestion } from '../types';\n\nexport const ${exportName}: RoleQuestion[] = ${JSON.stringify(questions, null, 2)};\n`;
  fs.writeFileSync(path.join(targetDir, filename), code, 'utf-8');
  console.log(`✓ ${filename} written (${questions.length} questions)`);
}

const devopsTopics = [
  ["Linux Permissions & Sticky Bit", "Linux", "Easy", "technical", "Explain Linux file permissions (chmod 755 vs 644) and what the Sticky Bit does on directories like /tmp.", ["Linux"], ["Read (4), Write (2), Execute (1) across User, Group, Others", "chmod 755 gives read/execute to group/others, write to owner", "Sticky bit (chmod +t) prevents users from deleting files owned by others in a shared directory"], ["chown", "umask"]],
  ["Linux Troubleshooting Commands", "Linux", "Intermediate", "practical", "A server is experiencing high CPU and memory thrashing. What commands do you use to diagnose it?", ["Linux", "Troubleshooting"], ["top / htop to inspect CPU and process hierarchy", "free -m and vmstat to check memory and swap usage", "iostat and iotop to identify disk I/O bottlenecks", "dmesg to check for OOM killer invocations"], ["lsof", "netstat / ss"]],
  ["Git Rebase vs Merge", "Git", "Easy", "technical", "Compare git merge vs git rebase. Why shouldn't you rebase commits already pushed to a shared branch?", ["Git"], ["git merge preserves full historical timeline with a merge commit", "git rebase rewrites commit history to produce a clean linear graph", "Rebasing shared branches rewrites commit hashes, breaking teammates' local repositories"], ["git cherry-pick", "Interactive rebase (rebase -i)"]],
  ["Docker Container vs Virtual Machine", "Docker", "Easy", "technical", "What is the architectural difference between a Docker container and a Virtual Machine (VM)?", ["Docker", "Virtualization"], ["VMs virtualize hardware including a guest OS kernel via a hypervisor (heavy, slow boot)", "Containers share host OS kernel using Linux namespaces and cgroups (lightweight, instant boot)", "Containers package only application and userspace dependencies"], ["cgroups and namespaces", "Docker daemon"]],
  ["Docker Multi-Stage Builds", "Docker", "Intermediate", "technical", "Why should you use Docker multi-stage builds in CI/CD pipelines?", ["Docker", "Optimization"], ["Separates build environment (compilers, SDKs) from runtime environment", "Dramatically reduces final image size (e.g. from 1GB to 50MB)", "Improves security by eliminating package managers and source code from production images"], ["Distroless images", ".dockerignore"]],
  ["Kubernetes Architecture Core Components", "Kubernetes", "Intermediate", "technical", "Explain the Kubernetes Control Plane components: API Server, etcd, Scheduler, and Controller Manager.", ["Kubernetes", "Architecture"], ["kube-apiserver is central gateway handling all REST operations", "etcd is distributed key-value store holding cluster state", "kube-scheduler assigns unscheduled pods to nodes based on resource constraints", "kube-controller-manager runs core loop reconciliations"], ["kubelet", "kube-proxy"]],
  ["Kubernetes Pod Lifecycle & Probes", "Kubernetes", "Intermediate", "technical", "Explain Liveness, Readiness, and Startup Probes in Kubernetes pod specifications.", ["Kubernetes"], ["Startup probe verifies application initialization before other probes run", "Liveness probe restarts container if unhealthy or deadlocked", "Readiness probe controls whether traffic is routed to pod by Service"], ["HTTP vs Exec probes", "InitialDelaySeconds"]],
  ["CI/CD Pipeline Security (DevSecOps)", "CI/CD", "Intermediate", "technical", "How do you integrate automated security scanning into a GitHub Actions or GitLab CI pipeline?", ["CI/CD", "DevSecOps"], ["Static Application Security Testing (SAST) with SonarQube or Semgrep", "Software Bill of Materials (SBOM) and dependency scanning with Snyk or Trivy", "Container vulnerability scanning before pushing to registry", "Secrets detection with Gitleaks"], ["DAST", "Trivy"]],
  ["Infrastructure as Code (Terraform)", "Terraform", "Intermediate", "technical", "Explain the Terraform workflow (init, plan, apply) and the role of the terraform.tfstate file.", ["Terraform", "IaC"], ["terraform init initializes providers and modules", "terraform plan computes diff between code and current state", "terraform apply provisions infrastructure", "tfstate maps declared resources to real-world cloud IDs"], ["Remote state in S3", "State locking with DynamoDB"]],
  ["Terraform State Management in Teams", "Terraform", "Advanced", "technical", "How do you safely manage Terraform state across distributed engineering teams?", ["Terraform", "DevOps"], ["Store tfstate in remote backend (AWS S3, Terraform Cloud) with encryption", "Enable state locking using DynamoDB to prevent concurrent modifications", "Isolate environments using Terraform workspaces or directory structures"], ["State drift", "terraform import"]],
  ["Kubernetes Services & Ingress", "Kubernetes", "Intermediate", "technical", "Compare ClusterIP, NodePort, LoadBalancer, and Ingress in Kubernetes.", ["Kubernetes", "Networking"], ["ClusterIP exposes service internally within cluster only (default)", "NodePort exposes service on static port on each worker node", "LoadBalancer provisions cloud provider external load balancer", "Ingress provides HTTP/HTTPS routing, SSL termination, and host-based path routing via single IP"], ["Ingress controller (Nginx)", "Cert-manager"]],
  ["Blue-Green vs Canary Deployments", "Deployment", "Intermediate", "technical", "How do you implement zero-downtime Canary deployments in Kubernetes using Argo Rollouts or Istio?", ["Kubernetes", "Continuous Deployment"], ["Argo Rollouts replaces Deployment with Rollout resource", "Gradually shifts traffic % to canary version (e.g. 10% -> 25% -> 100%)", "Automated rollback if error rate metrics from Prometheus spike"], ["Istio Service Mesh", "Flagger"]],
  ["Kubernetes ConfigMaps & Secrets", "Kubernetes", "Easy", "technical", "How do you inject configuration and sensitive credentials into Kubernetes pods securely?", ["Kubernetes"], ["ConfigMaps store non-sensitive key-values mounted as env vars or volume files", "Secrets store base64-encoded credentials (not encrypted at rest by default)", "Use external secret operators (HashiCorp Vault, AWS Secrets Manager) for true secret encryption"], ["External Secrets Operator", "Sealed Secrets"]],
  ["Prometheus & Grafana Monitoring", "Monitoring", "Intermediate", "technical", "Explain how Prometheus pulls metrics using pull-based scraping, PromQL, and Alertmanager.", ["Prometheus", "Monitoring"], ["Prometheus scrapes /metrics endpoints over HTTP at periodic intervals", "Time-series database optimized for metric queries using PromQL", "Alertmanager routes, silences, and sends alerts (Slack, PagerDuty) on threshold breaches"], ["Pushgateway", "Node exporter"]],
  ["ELK / EFK Logging Pipeline", "Logging", "Intermediate", "technical", "How does a centralized logging pipeline (Elasticsearch, Fluentd/Logstash, Kibana) collect Kubernetes logs?", ["Logging", "Observability"], ["Fluentd/Fluent Bit runs as DaemonSet on each node collecting container stdout/stderr logs", "Enriches logs with Kubernetes metadata (namespace, pod_name, labels)", "Indexes logs into Elasticsearch / OpenSearch for query and visualization in Kibana"], ["Loki vs Elasticsearch", "Log retention policies"]],
  ["DNS Resolution in Kubernetes (CoreDNS)", "Networking", "Advanced", "technical", "How does CoreDNS resolve service discovery queries like 'my-service.my-namespace.svc.cluster.local'?", ["Kubernetes", "Networking"], ["CoreDNS runs as cluster deployment watching Kubernetes API for service and endpoint changes", "Assigns internal DNS A-records pointing to Service ClusterIP", "Pods query CoreDNS via nameserver entry in /etc/resolv.conf"], ["ndots:5 latency issue", "kube-dns"]],
  ["Linux Systemd & Service Management", "Linux", "Easy", "practical", "How do you create, start, enable, and view logs for a custom systemd service in Linux?", ["Linux"], ["Create unit file in /etc/systemd/system/myapp.service with [Unit], [Service], [Install] sections", "systemctl daemon-reload", "systemctl start myapp and systemctl enable myapp (for boot startup)", "Inspect logs using journalctl -u myapp -f"], ["Restart=always", "StandardOutput configuration"]],
  ["Docker Networking Modes", "Docker", "Intermediate", "technical", "Compare Docker networking modes: bridge, host, none, and overlay.", ["Docker", "Networking"], ["bridge (default) creates isolated virtual network with NAT port forwarding", "host removes network isolation; container shares host network stack directly", "none disables networking entirely", "overlay enables multi-host container networking across Docker Swarm or Kubernetes"], ["Docker port binding (-p)", "veth pairs"]],
  ["Kubernetes DaemonSet vs StatefulSet", "Kubernetes", "Intermediate", "technical", "When do you use a DaemonSet and when do you use a StatefulSet in Kubernetes?", ["Kubernetes"], ["DaemonSet runs exactly one replica on every node in cluster (logging agents, monitoring daemons)", "StatefulSet manages stateful workloads requiring stable network IDs, persistent ordered storage, and graceful shutdown (Databases, Kafka)"], ["PersistentVolumeClaims", "Headless services"]],
  ["SSL/TLS Certificate Automation", "Security", "Easy", "technical", "How do you automate SSL certificate generation and renewal in Kubernetes using cert-manager?", ["Security", "Kubernetes"], ["cert-manager operator watches Certificate custom resources", "Interacts with Let's Encrypt using ACME protocol (HTTP-01 or DNS-01 challenge)", "Automatically provisions and rotates TLS Secret referenced by Ingress"], ["ACME challenges", "Wildcard certificates"]],
  ["CI/CD Artifact Caching", "CI/CD", "Easy", "practical", "How do you optimize CI/CD pipeline execution time by caching dependencies (npm, maven, pip, docker layers)?", ["CI/CD", "Optimization"], ["Use actions/cache in GitHub Actions keyed on lockfile hash (package-lock.json)", "Leverage Docker layer caching (BuildKit cache mounts)", "Run parallel jobs for linting, testing, and security scanning"], ["GitHub Actions cache", "BuildKit"]],
  ["Kubernetes Horizontal Pod Autoscaler (HPA)", "Kubernetes", "Intermediate", "technical", "How does the Kubernetes HPA scale pods based on CPU utilization and custom metrics?", ["Kubernetes", "Autoscaling"], ["HPA queries Metrics Server or Prometheus Adapter every 15 seconds", "Calculates desired replicas: ceil(currentReplicas * (currentMetric / targetMetric))", "Scales Deployment up or down subject to min/max replica boundaries and stabilization window"], ["Metrics Server", "KEDA (Kubernetes Event-driven Autoscaling)"]],
  ["Zero-Downtime Rolling Updates", "Deployment", "Intermediate", "technical", "How does a Kubernetes Deployment execute a zero-downtime rolling update with maxSurge and maxUnavailable?", ["Kubernetes"], ["Creates new ReplicaSet alongside old one", "maxSurge specifies maximum pods that can be created above desired count", "maxUnavailable specifies maximum pods that can be down during update", "Readiness probes ensure new pods are healthy before terminating old pods"], ["RollingUpdate strategy", "kubectl rollout undo"]],
  ["Ansible Configuration Management", "Ansible", "Intermediate", "technical", "What is idempotency in Ansible playbooks and how does Ansible differ from Terraform?", ["Ansible", "IaC"], ["Ansible is configuration management tool operating over SSH without agents", "Idempotency ensures executing playbook multiple times leaves system in exact same desired state without unintended side effects", "Terraform provisions infrastructure; Ansible configures OS and software"], ["Ansible roles", "Inventory files"]],
  ["Linux SSH Hardening", "Security", "Easy", "technical", "What are best practices for securing an SSH server on a production Linux host?", ["Linux", "Security"], ["Disable root login (PermitRootLogin no)", "Disable password authentication, enforce SSH keys (PasswordAuthentication no)", "Change default port 22, use Fail2ban to block brute force attempts", "Restrict allowed users and use SSH certificates or bastion hosts"], ["ssh-keygen", "Bastion hosts"]],
  ["Kubernetes Network Policies", "Kubernetes", "Advanced", "technical", "How do Kubernetes NetworkPolicies enforce microsegmentation and pod-to-pod firewall rules?", ["Kubernetes", "Security"], ["Requires CNI plugin supporting network policies (Calico, Cilium)", "Defines ingress and egress rules filtering traffic by podSelector, namespaceSelector, or ipBlock", "Default deny rule isolates all pods in namespace unless explicitly allowed"], ["Calico", "Cilium eBPF"]],
  ["Disaster Recovery & Backup (Velero)", "Disaster Recovery", "Intermediate", "technical", "How do you perform backup and disaster recovery for Kubernetes clusters using Velero?", ["Disaster Recovery", "Kubernetes"], ["Velero backs up cluster resource manifests to object storage (S3)", "Takes snapshots of persistent volumes (EBS, PersistentVolumes)", "Enables full cluster restoration or migration to a new region/cluster"], ["RTO and RPO", "Snapshot replication"]],
  ["GitOps with ArgoCD / Flux", "GitOps", "Intermediate", "technical", "What is GitOps and how does ArgoCD reconcile cluster state with a Git repository?", ["GitOps", "ArgoCD"], ["Git repository is single source of truth for all declared infrastructure and app manifests", "ArgoCD runs agent in cluster continuously comparing Git state to live cluster state", "Automatically syncs or alerts on configuration drift"], ["Automated sync", "Helm / Kustomize integration"]],
  ["Troubleshooting CrashLoopBackOff", "Kubernetes", "Intermediate", "scenario", "A pod in production is stuck in CrashLoopBackOff. What diagnostic sequence do you follow?", ["Troubleshooting", "Kubernetes"], ["kubectl describe pod <name> to check exit code and events (OOMKilled, failed probe)", "kubectl logs <name> --previous to inspect stdout/stderr before the container crashed", "Check entrypoint commands, missing ConfigMap/Secret environment variables, and file permissions"], ["OOMKilled exit 137", "ephemeral debug container"]],
  ["Load Balancers: Layer 4 vs Layer 7", "Networking", "Intermediate", "technical", "Compare Layer 4 (TCP/UDP) vs Layer 7 (HTTP/HTTPS) load balancing.", ["Networking"], ["Layer 4 routes packets based on IP and port without inspecting payload (faster, lower CPU)", "Layer 7 inspects application layer data (HTTP headers, cookies, URL paths) for intelligent routing", "Layer 7 performs SSL termination, path routing, and header rewrites"], ["AWS ALB vs NLB", "HAProxy"]],
  ["Kubernetes Resource Requests & Limits", "Kubernetes", "Easy", "technical", "Explain the difference between CPU/Memory requests and limits in Kubernetes.", ["Kubernetes"], ["Requests define guaranteed resources reserved for scheduling (scheduler assigns node with enough capacity)", "Limits set hard maximum boundaries; exceeding memory limit results in OOMKill", "Exceeding CPU limit results in CPU throttling rather than container kill"], ["Quality of Service (Guaranteed, Burstable, BestEffort)", "CPU throttling"]],
  ["Incident Post-Mortems & RCA", "Behavioral", "Intermediate", "behavioral", "Describe a blameless post-mortem you led after a major production outage.", ["Incident Response", "Communication"], ["Document timeline of events from detection to resolution", "Identify root cause without assigning personal blame (5 Whys methodology)", "Define actionable preventative tasks with owners and due dates"], ["Blameless culture", "Mean Time to Recovery (MTTR)"]],
  ["Production Outage Triage Experience", "Project Experience", "Intermediate", "behavioral", "Tell me about a high-severity production infrastructure outage you handled. How did you restore service?", ["Troubleshooting", "Communication"], ["Incident declaration and stakeholder communication", "Fastest path to mitigation (rollback, traffic reroute, scaling)", "Post-incident root cause analysis and permanent fix"], ["On-call management", "PagerDuty"]],
  ["Developer Platform Engineering", "Culture", "Easy", "behavioral", "How do you balance implementing strict security/infrastructure controls with developer productivity?", ["DevOps Culture", "Platform Engineering"], ["Create self-service internal developer platforms (IDP) and golden paths", "Automate security scanning inside CI/CD with clear actionable fix suggestions", "Avoid becoming a manual operational bottleneck"], ["Golden paths", "Internal Developer Platforms"]],
  ["Future of Cloud Native (eBPF & WebAssembly)", "Modern Trends", "Advanced", "technical", "What is eBPF and how is it transforming Kubernetes networking, security, and observability (Cilium)?", ["Modern DevOps", "eBPF"], ["Runs sandboxed bytecode inside Linux kernel without modifying kernel source code", "Enables ultra-fast packet routing, deep kernel observability, and real-time security enforcement", "Eliminates iptables/kube-proxy overhead at massive scale"], ["Cilium", "Falco security"]]
];

const devopsQuestions = devopsTopics.map((t, idx) => ({
  id: `dv-${String(idx + 1).padStart(3, '0')}`,
  role: "DevOps Engineer",
  category: t[1],
  difficulty: t[2],
  format: t[3],
  question: t[4],
  expectedSkills: t[5],
  evaluationPoints: t[6],
  followUpTopics: t[7]
}));
save('devopsEngineer.ts', 'DEVOPS_ENGINEER_QUESTIONS', devopsQuestions);
