const fs = require('fs');
const path = require('path');
const targetDir = 'C:/sih/src/data/interviewQuestions/banks';

function save(filename, exportName, questions) {
  const code = `import { RoleQuestion } from '../types';\n\nexport const ${exportName}: RoleQuestion[] = ${JSON.stringify(questions, null, 2)};\n`;
  fs.writeFileSync(path.join(targetDir, filename), code, 'utf-8');
  console.log(`✓ ${filename} written (${questions.length} questions)`);
}

const steTopics = [
  ["Verification vs Validation", "Testing Fundamentals", "Easy", "technical", "Explain the difference between Verification and Validation in software engineering (V-Model).", ["Testing Fundamentals", "V-Model"], ["Verification: 'Are we building the product right?' (Reviews, inspections, static testing of specs and code)", "Validation: 'Are we building the right product?' (Dynamic execution of software to verify customer needs)", "Verification is static; Validation is dynamic"], ["V-Model", "Static testing"]],
  ["Black Box vs White Box vs Grey Box", "Testing Methodologies", "Easy", "technical", "Compare Black Box, White Box, and Grey Box testing with examples of each.", ["Testing Methodologies"], ["Black Box: testing functionality without knowing internal code/structure (functional, UI)", "White Box: testing internal structure, code paths, and logic (unit tests, code coverage)", "Grey Box: partial knowledge of internal architecture (database testing, API integration testing)"], ["Code coverage", "Statement coverage"]],
  ["Boundary Value Analysis (BVA)", "Test Design", "Easy", "practical", "Design boundary value test cases for a password field requiring 8 to 16 characters.", ["Test Design", "BVA"], ["Boundary values to test: 7 (Invalid), 8 (Valid min), 9 (Valid min+1), 15 (Valid max-1), 16 (Valid max), 17 (Invalid max+1)", "Check exact character count behavior and error messages", "Test special characters and empty input"], ["Equivalence partitioning", "Negative testing"]],
  ["Functional vs Non-Functional Testing", "Testing Types", "Easy", "technical", "What is the core distinction between Functional and Non-Functional testing?", ["Testing Types"], ["Functional testing validates WHAT the system does (features, user actions, business rules)", "Non-functional testing validates HOW the system performs (speed, reliability, scalability, security, usability)", "Both are equally critical for product success"], ["System testing", "Usability testing"]],
  ["Defect Density & QA Metrics", "Metrics", "Intermediate", "technical", "What is Defect Density and how is it calculated across modules?", ["QA Metrics"], ["Defect Density = Total Defect Count / Module Size (KLOC or Function Points)", "Identifies high-risk modules with disproportionate failure rates", "Directs testing focus and code refactoring efforts"], ["Defect removal efficiency", "Test coverage metrics"]],
  ["State Transition Testing", "Test Design", "Intermediate", "technical", "How does State Transition Testing apply to testing an e-commerce order workflow?", ["Test Design", "State Transitions"], ["Map all valid system states: Order Placed -> Payment Pending -> Paid -> Shipped -> Delivered -> Returned", "Identify valid transitions and invalid transitions (e.g. attempting to Ship an Unpaid order)", "Verify system handles invalid state changes gracefully with error messages"], ["State transition diagrams", "Negative testing"]],
  ["Decision Table Testing", "Test Design", "Intermediate", "practical", "How do you build a Decision Table to test credit card approval based on credit score, income, and debt ratio?", ["Test Design", "Decision Tables"], ["List conditions (Credit Score > 700, Income > $50k, Debt Ratio < 30%)", "Create combination matrix of True/False condition values (2^N rules)", "Define expected action (Approve, Manual Review, Reject) for each combination"], ["Truth tables", "Combinatorial testing"]],
  ["Static vs Dynamic Testing", "Testing Fundamentals", "Easy", "technical", "What activities constitute Static Testing and why does it find bugs earlier than Dynamic Testing?", ["Static Testing"], ["Static testing reviews requirements, design documents, and performs code walk-throughs without executing software", "Catches ambiguities and architectural flaws before a single line of code is run", "Dynamic testing executes compiled code with test data inputs"], ["Peer reviews", "Inspection checklists"]],
  ["API Error Testing: 4xx vs 5xx", "API Testing", "Easy", "technical", "How do you test that an API correctly differentiates 4xx client errors from 5xx server errors?", ["API Testing", "HTTP"], ["Send invalid input, missing auth headers, bad types -> verify 400 Bad Request, 401 Unauthorized, 422 Unprocessable", "Simulate backend database downtime or null pointer -> verify 500 Internal Server Error without leaking internal stack traces", "Assert client receives actionable, structured error payloads"], ["HTTP status codes", "Security in error responses"]],
  ["Exploratory Testing Charters", "Exploratory Testing", "Easy", "technical", "What is a Test Charter in session-based exploratory testing?", ["Exploratory Testing"], ["A focused mission statement defining target area, goal, and time-box for an exploratory session", "Example: 'Explore shopping cart discount code inputs with expired and multi-use coupons to discover edge case vulnerabilities'", "Includes session debrief notes and bug logs"], ["Time-boxing", "Session-based testing"]],
  ["Acceptance Criteria & Definition of Done", "Agile", "Easy", "technical", "What is the difference between User Story Acceptance Criteria and Definition of Done (DoD)?", ["Agile", "Scrum"], ["Acceptance Criteria are unique business conditions specific to a single user story", "Definition of Done (DoD) is a universal quality checklist applied to ALL user stories across team (code reviewed, tested, documented, deployed to staging)", "A story cannot be closed unless both are fully satisfied"], ["User stories", "Sprint DoD"]],
  ["Database Validation in Web Testing", "Database Testing", "Intermediate", "practical", "Why is UI verification alone insufficient when testing account creation?", ["Database Testing"], ["UI might show 'Success' even if database failed to write secondary tables (profile, notifications)", "Verify primary database record exists with correct password hashing (not plain text)", "Verify default values, foreign keys, and audit log entries"], ["Data integrity", "SQL verification"]],
  ["Usability Testing Heuristics", "Usability", "Easy", "technical", "Explain Nielsen's Usability Heuristics: Error Prevention, Consistency, and Visibility of System Status.", ["Usability Testing"], ["Visibility of system status: system always provides clear feedback (loading spinners, progress bars)", "Consistency and standards: users shouldn't wonder whether different words or icons mean the same thing", "Error prevention: eliminate error-prone conditions or confirm before destructive actions (Delete confirmation modal)"], ["UX heuristics", "User accessibility"]],
  ["Testing Under Unstable Network Conditions", "Mobile & Web", "Intermediate", "practical", "How do you test web and mobile applications under slow, high-latency, or dropping network connections?", ["Network Testing"], ["Use network throttling in Chrome DevTools (Slow 3G, Offline)", "Verify loading states, skeleton screens, and sensible timeout error messages", "Test offline mode: verify local caching and graceful synchronization once connectivity is restored"], ["Network throttling", "Offline caching"]],
  ["Security: Testing Authentication & Sessions", "Security Testing", "Intermediate", "technical", "What security test cases do you execute against login and session management features?", ["Security Testing"], ["Test password brute-force lockouts after 5 failed attempts", "Verify session token is invalidated upon logout and password change", "Verify password reset tokens expire after time-box and are single-use", "Test session fixation by checking token changes before and after login"], ["Session fixation", "Brute force testing"]],
  ["Regression Suite Maintenance", "Test Management", "Intermediate", "technical", "How do you maintain a regression test suite to prevent it from becoming unmanageably bloated over time?", ["Regression Testing"], ["Periodically retire redundant or obsolete test cases for deprecated features", "Automate high-value, stable test cases into CI/CD regression suites", "Consolidate overlapping test scenarios into parameterized data-driven tests"], ["Test suite optimization", "Traceability"]],
  ["Risk-Based Testing (RBT)", "Testing Strategy", "Intermediate", "technical", "How do you perform Risk-Based Testing when project timelines are cut in half?", ["Risk-Based Testing"], ["Assess risk for each module: Risk = Likelihood of Failure * Impact of Failure", "Assign modules to High, Medium, and Low risk tiers", "Direct 80% of remaining testing effort to High risk modules (payment, auth, data loss risks), accepting residual risk in Low tiers"], ["Risk matrix", "Residual risk"]],
  ["End-to-End Testing Workflows", "Testing Types", "Easy", "practical", "Describe the end-to-end test workflow for a flight booking system.", ["E2E Testing", "Scenario Testing"], ["Search flights with dates and passengers -> Select flight and fare class", "Enter passenger details with passport validation -> Select seats", "Apply promo code -> Complete payment through gateway -> Verify booking confirmation email and database ticket generation"], ["Happy path vs edge cases", "System integration"]],
  ["Compatibility Testing Matrix", "Compatibility", "Easy", "technical", "How do you construct an effective hardware/software Compatibility Testing Matrix?", ["Compatibility Testing"], ["Analyze Google Analytics data to identify top OS, browser, and device resolutions used by real customers", "Create matrix mapping platforms (Windows, macOS, iOS, Android) to browsers and viewports", "Prioritize testing tier 1 combinations representing 80%+ of audience"], ["Browser matrix", "Responsive viewports"]],
  ["Accessibility Testing with Screen Readers", "Accessibility", "Easy", "technical", "How do you evaluate accessibility using screen readers like NVDA or VoiceOver?", ["Accessibility", "WCAG"], ["Navigate entire application using Tab, Shift-Tab, and arrow keys with eyes closed", "Verify screen reader announces meaningful labels for buttons, inputs, and error notices", "Ensure decorative images are ignored (aria-hidden) and informational images have alt text"], ["Screen readers", "ARIA attributes"]],
  ["Defect Reporting Best Practices", "Defect Management", "Easy", "practical", "What information separates an exceptional bug report from an unhelpful one?", ["Defect Management"], ["Actionable headline with component tag: [Checkout] Promo code discount calculates negative total", "Exact step-by-step reproduction steps with test credentials and payload", "Expected behavior vs Actual observed behavior with screenshots/video and network logs"], ["Reproducibility", "Log attachment"]],
  ["Load Testing vs Stress Testing vs Soak Testing", "Performance", "Intermediate", "technical", "Compare Load Testing, Stress Testing, and Soak (Endurance) Testing.", ["Performance Testing"], ["Load testing: verifies system behavior under expected normal and peak traffic", "Stress testing: pushes traffic beyond breaking point to evaluate graceful degradation and recovery", "Soak testing: runs moderate traffic continuously over extended duration (24-48 hours) to detect slow memory leaks and resource exhaustion"], ["Soak testing", "Breaking point"]],
  ["Testing Database Concurrency", "Database Testing", "Intermediate", "technical", "How do you test concurrent transactions in multi-user booking applications (e.g. two users booking the last seat)?", ["Concurrency", "Database Testing"], ["Simulate two simultaneous requests attempting to reserve the exact same inventory item", "Verify database locking prevents double-booking", "One user succeeds; second user receives graceful 'Item no longer available' notification"], ["Race conditions", "Double booking prevention"]],
  ["Agile Quality Culture", "Agile", "Easy", "behavioral", "How do you foster a 'Quality is a Team Responsibility' mindset across software developers?", ["Quality Culture", "Collaboration"], ["Involve developers in acceptance criteria design and edge case brainstorming", "Pair with developers on writing integration tests", "Share customer defect feedback transparently in sprint retrospectives"], ["Team responsibility", "Whole-team approach"]],
  ["Testing Responsive Web Design", "Web Testing", "Easy", "practical", "What visual and functional elements do you inspect when testing responsive layouts across breakpoints?", ["Responsive Testing"], ["Navigation menus collapsing into hamburger menus on mobile viewports", "Tables converting to cards or horizontal scrolling without breaking page width", "Tap target sizes on mobile touchscreens (minimum 48x48px) and no text overlap"], ["Breakpoints", "Viewport testing"]],
  ["Localization Testing Pitfalls", "Localization", "Intermediate", "technical", "What are common visual and functional bugs uncovered during Localization (l10n) testing?", ["Localization Testing"], ["Text expansion causing button text clipping and layout misalignment (e.g. German text)", "Incorrect number, currency, and date formatting (comma vs period decimal separators)", "Hardcoded English strings missed during translation extraction"], ["String externalization", "Date formatting"]],
  ["API Testing: Boundary & Malformed Payloads", "API Testing", "Intermediate", "practical", "What negative test payloads do you send to an API to test its error-handling resilience?", ["API Testing", "Negative Testing"], ["Send unexpected data types (string in numeric field, boolean in array)", "Send extremely large payloads (10MB string) to test buffer overflow and payload size limits", "Send malformed JSON (missing closing braces) to verify 400 Bad Request without server crash"], ["Malformed JSON", "Negative testing"]],
  ["Root Cause Analysis of Production Escapes", "Process Improvement", "Intermediate", "behavioral", "A critical bug escaped into production. How do you lead a post-incident review to improve test coverage?", ["Incident Review", "Continuous Improvement"], ["Analyze why the bug was missed: was it a missing test case, bad test environment, or unclear requirement?", "Create automated regression test reproducing the exact failure mode", "Update test checklists and test design templates to catch similar patterns across all features"], ["Escaped bugs", "Post-mortem analysis"]],
  ["Test Strategy Document Creation", "Test Management", "Intermediate", "technical", "What are the core components of a high-level Test Strategy Document for an enterprise project?", ["Test Strategy", "Documentation"], ["Scope of testing (In-Scope and Out-of-Scope modules)", "Testing types and levels (Unit, Integration, System, E2E, Performance, Security)", "Test environment and test data requirements", "Tools, defect management workflow, and release entry/exit criteria"], ["Test Plan vs Test Strategy", "Release criteria"]],
  ["Testing Complex Search Filters", "Test Design", "Easy", "practical", "How do you test a multi-facet e-commerce filter panel (Price, Category, Brand, Rating, In-Stock)?", ["Test Design", "Scenario Analysis"], ["Test single filter selection and verify result counts update accurately", "Test combined multi-filters (Price < $50 AND Brand = 'Sony' AND Rating >= 4)", "Test 'Clear All Filters' and verify browser URL query parameters update correctly for bookmarking"], ["Multi-faceted search", "Filter combinations"]],
  ["Testing Push Notifications", "Mobile Testing", "Easy", "technical", "What test scenarios must you verify when testing mobile push notifications?", ["Mobile Testing", "Push Notifications"], ["Verify notification delivery when app is in foreground, background, and completely killed", "Verify tapping notification deep-links directly to the correct internal screen", "Test notification behavior when user has disabled notifications in device settings"], ["Deep linking", "APNs / FCM"]],
  ["Handling Ambiguous Requirements", "Behavioral", "Easy", "behavioral", "What do you do when a user story description is vague and has missing acceptance criteria?", ["Communication", "Agile"], ["Do not guess implementation details; schedule a quick sync with the Product Manager / Business Analyst", "Ask clarifying questions focused on user goals and edge cases", "Document agreed acceptance criteria in the user story before development begins"], ["Clarifying requirements", "Agile communication"]],
  ["Managing Tight Release Deadlines", "Project Experience", "Intermediate", "behavioral", "Describe a project where testing time was severely compressed. How did you deliver high quality on time?", ["Project Experience", "Time Management"], ["Prioritized critical path end-to-end workflows using risk-based testing", "Executed automated regression suites overnight to maximize testing coverage", "Provided clear risk assessments and status reports to leadership for release decisions"], ["Prioritization", "Risk management"]],
  ["Testing Legacy Software with No Docs", "Troubleshooting", "Intermediate", "behavioral", "How do you approach testing a critical legacy system that has zero documentation and no existing test cases?", ["Exploratory Testing", "Legacy Systems"], ["Perform exploratory testing to map application workflows and system behavior", "Inspect database schemas and API network calls to understand data flow", "Interview senior developers and support teams to document known issues and critical workflows"], ["Reverse engineering", "Documenting legacy systems"]],
  ["Future of Software Testing", "Modern Trends", "Easy", "technical", "How is the role of the Software Testing Engineer evolving with Agile, DevOps, and automated pipelines?", ["Modern QA", "Career Growth"], ["Shift from pure manual execution to quality advocacy, test design, and exploratory testing", "Close collaboration with developers on testability, API contracts, and CI/CD quality gates", "Leveraging AI tools to accelerate test case generation, synthetic data, and exploratory testing"], ["Quality advocacy", "Continuous testing"]]
];

const steQuestions = steTopics.map((t, idx) => ({
  id: `ste-${String(idx + 1).padStart(3, '0')}`,
  role: "Software Testing Engineer",
  category: t[1],
  difficulty: t[2],
  format: t[3],
  question: t[4],
  expectedSkills: t[5],
  evaluationPoints: t[6],
  followUpTopics: t[7]
}));
save('softwareTestingEngineer.ts', 'SOFTWARE_TESTING_ENGINEER_QUESTIONS', steQuestions);
