const fs = require('fs');
const path = require('path');
const targetDir = 'C:/sih/src/data/interviewQuestions/banks';

function save(filename, exportName, questions) {
  const code = `import { RoleQuestion } from '../types';\n\nexport const ${exportName}: RoleQuestion[] = ${JSON.stringify(questions, null, 2)};\n`;
  fs.writeFileSync(path.join(targetDir, filename), code, 'utf-8');
  console.log(`✓ ${filename} written (${questions.length} questions)`);
}

// 1. Python Backend Developer
const pybTopics = [
  ["FastAPI vs Django", "Architecture", "Easy", "technical", "Compare FastAPI and Django for building backend REST APIs. When do you choose each?", ["FastAPI", "Django"], ["FastAPI is lightweight, asynchronous, high-performance", "Django is batteries-included with built-in ORM and admin", "FastAPI excels for microservices, Django for monolithic apps"], ["Flask", "Async benchmarks"]],
  ["Pydantic Validation", "FastAPI", "Intermediate", "technical", "How does Pydantic v2 handle request body validation and serialization in FastAPI?", ["Pydantic", "FastAPI"], ["BaseModel type annotations", "Automatic parsing with 422 errors", "Fast Rust core in v2"], ["Field validators", "model_dump()"]],
  ["FastAPI Dependencies", "FastAPI", "Intermediate", "technical", "Explain FastAPI's Depends system and how it handles database sessions and auth.", ["FastAPI", "Architecture"], ["Depends() injects dependencies", "yield syntax manages session cleanup", "Security scopes support"], ["Security dependencies", "Dependency overrides"]],
  ["Async ORM with SQLAlchemy", "Database", "Intermediate", "technical", "How do you configure asynchronous database sessions with SQLAlchemy 2.0 and asyncpg?", ["SQLAlchemy", "Async"], ["create_async_engine and async_sessionmaker", "async with session.begin() transactions", "select() syntax in 2.0"], ["Connection pooling", "Alembic async"]],
  ["Celery & Redis", "Background Tasks", "Intermediate", "technical", "How do you offload long-running tasks using Celery and Redis in a Python backend?", ["Celery", "Redis"], ["Redis acts as task broker", "Celery worker processes run asynchronously", "Task retries with backoff"], ["Celery Beat", "Result backends"]],
  ["JWT Authentication", "Security", "Intermediate", "technical", "Explain how to implement stateless JWT access and refresh tokens in Python.", ["JWT", "Security"], ["Short-lived access tokens", "Secure refresh token rotation", "Revocation list in Redis"], ["PyJWT", "OAuth2 password flow"]],
  ["N+1 in Django ORM", "Django", "Intermediate", "technical", "What is the difference between select_related and prefetch_related in Django ORM?", ["Django ORM", "Performance"], ["select_related does SQL JOIN for foreign keys", "prefetch_related executes separate query in Python", "Solves N+1 query problem"], ["QuerySet evaluation", "only() and defer()"]],
  ["Redis Caching", "Caching", "Intermediate", "technical", "How do you implement the Cache-Aside pattern using Redis in a Python API?", ["Redis", "Caching"], ["Check cache on request, load DB on miss, store with TTL", "Invalidate on entity update/delete", "Prevent cache stampede"], ["Distributed locks", "Redis data structures"]],
  ["WebSockets in FastAPI", "WebSockets", "Intermediate", "technical", "How do you implement real-time bidirectional communication using WebSockets in FastAPI?", ["WebSockets", "FastAPI"], ["@app.websocket route handler", "ConnectionManager tracks active sockets", "Broadcast events to connected clients"], ["Redis Pub/Sub scaling", "Socket heartbeats"]],
  ["ASGI vs WSGI", "Networking", "Advanced", "technical", "Explain ASGI vs WSGI. Why is ASGI necessary for asynchronous Python servers?", ["ASGI", "Uvicorn"], ["WSGI is synchronous single request-response", "ASGI handles async HTTP and persistent WebSockets", "Uvicorn ASGI runner"], ["Gunicorn worker classes", "Event loop"]],
  ["Rate Limiting", "Security", "Intermediate", "technical", "How do you implement API rate limiting in Python using Redis Sliding Window?", ["Rate Limiting", "Redis"], ["ZSET tracking timestamps of requests", "Prune entries outside sliding window", "Return 429 Too Many Requests"], ["slowapi library", "Token bucket algorithm"]],
  ["PostgreSQL Query Tuning", "Database", "Advanced", "scenario", "A PostgreSQL query executed by your API takes 5 seconds under load. How do you diagnose it?", ["PostgreSQL", "Performance"], ["Run EXPLAIN (ANALYZE, BUFFERS)", "Identify sequential scans and missing indexes", "Check connection pool saturation"], ["Index selectivity", "VACUUM and query stats"]],
  ["Dockerizing FastAPI", "Deployment", "Intermediate", "technical", "How do you structure a production-ready Dockerfile for a FastAPI application?", ["Docker", "Deployment"], ["Multi-stage build to reduce image footprint", "Run as non-root user", "Gunicorn with Uvicorn worker process manager"], ["HEALTHCHECK instruction", ".dockerignore"]],
  ["Clean Architecture in Python", "Architecture", "Advanced", "technical", "How do you structure a Python backend using Clean or Hexagonal Architecture?", ["Architecture", "Design Patterns"], ["Separation into Domain, Use Case, and Adapter layers", "Dependency Inversion with Protocols", "Framework-independent business logic"], ["Repository pattern", "Service layer"]],
  ["HTTP Status Codes", "REST APIs", "Easy", "technical", "What HTTP status codes should a REST API return for 201, 400, 401, 403, 404, and 422?", ["REST APIs", "HTTP"], ["201 for Created", "400 for Bad Request, 422 for Unprocessable Entity", "401 Unauthorized vs 403 Forbidden"], ["204 No Content", "409 Conflict"]],
  ["Integration Testing with httpx", "Testing", "Intermediate", "practical", "How do you write async API tests using pytest-asyncio and httpx.AsyncClient?", ["Testing", "pytest"], ["AsyncClient with asgi app instance", "Database rollback fixtures per test", "Mocking external services with respx"], ["Testcontainers", "Fixtures"]],
  ["File Uploads to S3", "Cloud", "Intermediate", "technical", "How do you handle large file uploads securely in Python without loading everything into memory?", ["FastAPI", "AWS S3"], ["Stream via UploadFile or use S3 presigned URLs", "Validate file size and MIME content type", "boto3 upload_fileobj"], ["Presigned URLs", "Virus scanning"]],
  ["Password Hashing", "Security", "Easy", "technical", "Why should you never use SHA256 or MD5 for password storage? What should you use instead?", ["Security", "Cryptography"], ["Fast hashes are vulnerable to brute-force and rainbow tables", "Use adaptive salted algorithms: bcrypt or Argon2", "Configurable work factor (rounds)"], ["passlib", "Timing attack prevention"]],
  ["Microservices Saga Pattern", "Distributed Systems", "Advanced", "technical", "How do you manage distributed transactions across microservices using the Saga pattern?", ["Microservices", "Architecture"], ["Choreographed events vs central orchestrator", "Compensating transactions on failure", "Avoids brittle two-phase commits"], ["Outbox pattern", "Idempotency keys"]],
  ["Database Migrations with Alembic", "Database", "Easy", "technical", "How does Alembic generate and apply schema migrations for SQLAlchemy models?", ["Alembic", "DevOps"], ["alembic revision --autogenerate detects changes", "alembic upgrade head applies migrations", "Managing migration conflicts in team branches"], ["Downgrades", "Branching migrations"]],
  ["Prometheus Observability", "Monitoring", "Intermediate", "technical", "How do you instrument a Python REST API with Prometheus metrics and OpenTelemetry?", ["Prometheus", "Observability"], ["Expose /metrics endpoint using prometheus-fastapi-instrumentator", "Track request count, latency histograms, and error rates", "Distributed tracing with OpenTelemetry trace_id"], ["Grafana", "Alertmanager"]],
  ["CPU-Bound Task Pitfall", "Async", "Intermediate", "scenario", "Why does a CPU-heavy loop inside an async def route freeze all API traffic, and how do you fix it?", ["Async", "Concurrency"], ["Event loop is blocked by synchronous CPU execution", "Offload with asyncio.to_thread() or ProcessPoolExecutor", "Or dispatch to background Celery queue"], ["concurrent.futures", "def vs async def"]],
  ["gRPC in Python", "gRPC", "Advanced", "technical", "What are the performance advantages of using gRPC over REST for microservice communication?", ["gRPC", "Protocol Buffers"], ["Compact binary Protocol Buffers vs text JSON", "HTTP/2 multiplexing and streaming support", "Strict contract generation from .proto files"], ["grpcio-tools", "Bi-directional streaming"]],
  ["Database Connection Pooling", "Database", "Intermediate", "technical", "Why is database connection pooling critical for high-throughput Python backends?", ["Database", "Performance"], ["Reuses established connections, eliminating handshake overhead", "Prevents exhausting database max_connections", "Configuring pool_size and max_overflow in SQLAlchemy"], ["pgBouncer", "Connection timeouts"]],
  ["API Versioning Strategies", "API Design", "Easy", "technical", "What are the main approaches to API versioning in Python backends?", ["API Design"], ["URI path versioning (/api/v1/)", "Header versioning (Accept header)", "Query parameter versioning"], ["Deprecation lifecycle", "Backward compatibility"]],
  ["Bulk Database Operations", "Database", "Intermediate", "practical", "How do you insert or update 10,000 records efficiently in PostgreSQL from Python?", ["SQLAlchemy", "Database"], ["Avoid issuing 10,000 individual queries in a loop", "Use bulk_insert_mappings or PostgreSQL COPY", "Execute within a single database transaction"], ["temporary tables", "ON CONFLICT DO UPDATE"]],
  ["SQL Injection Prevention", "Security", "Easy", "technical", "How do you prevent SQL injection when writing dynamic queries in Python?", ["Security", "SQL"], ["Always use parameterized queries or ORM expressions", "Never format raw strings into SQL queries", "SQLAlchemy text() with bindparams"], ["OWASP Top 10", "Input validation"]],
  ["Cursor vs Offset Pagination", "API Design", "Intermediate", "technical", "Compare Offset-based vs Keyset (Cursor-based) pagination for large datasets.", ["API Design", "Database"], ["Offset scans and discards preceding rows (slow on page 1000)", "Cursor pagination seeks index directly (WHERE id > cursor)", "Cursor prevents duplicate/missed rows during live inserts"], ["FastAPI-pagination", "Infinite scroll"]],
  ["Mocking External Services", "Testing", "Easy", "practical", "How do you mock an external third-party payment API in Python unit tests?", ["Testing", "Mocking"], ["unittest.mock.patch or respx library for httpx", "Assert mock called with exact expected payload", "Ensure tests never hit live third-party network"], ["Responses library", "VCR.py"]],
  ["Idempotent API Design", "REST APIs", "Intermediate", "technical", "What is an idempotency key and how do you implement it for financial transactions?", ["API Design", "Distributed Systems"], ["Client sends unique Idempotency-Key header", "Server caches request result in Redis", "Duplicate requests return cached response without re-processing"], ["POST vs PUT", "Payment gateways"]],
  ["Environment Secrets Management", "Security", "Easy", "technical", "How do you manage database passwords and API keys securely in Python applications?", ["Security", "DevOps"], ["Never commit secrets to Git repositories", "Load from environment variables using pydantic-settings", "Use cloud secrets managers (AWS Secrets Manager, HashiCorp Vault) in production"], [".env.example", "12-Factor App"]],
  ["Structured JSON Logging", "Logging", "Easy", "technical", "Why is structured JSON logging preferred over plain text logs in cloud-native backends?", ["Logging", "Observability"], ["Easily parsed and indexed by ELK, Datadog, CloudWatch", "Enables filtering by correlation_id, user_id, and log level", "Consistent schema across all microservices"], ["Loguru", "structlog"]],
  ["Handling Backend Outages", "Behavioral", "Intermediate", "behavioral", "Describe a time a production backend service crashed. How did you triage, resolve, and prevent it?", ["Problem Solving", "Incident Response"], ["Check server logs and monitoring metrics immediately", "Identify root cause (memory leak, unindexed query, deadlock)", "Deploy hotfix and write post-mortem with preventative tests"], ["Root cause analysis", "Runbooks"]],
  ["Designing a Real-World Microservice", "Project Experience", "Intermediate", "behavioral", "Walk me through the architecture of a Python backend API you designed from scratch.", ["System Design", "Communication"], ["Requirements analysis and tech stack selection", "Data schema design and entity relationships", "Deployment, caching, and CI/CD pipelines"], ["Scalability trade-offs", "Lessons learned"]],
  ["Cross-Team Contract Collaboration", "Behavioral", "Easy", "behavioral", "How do you coordinate API changes with frontend mobile and web teams without breaking production?", ["Collaboration", "API Contracts"], ["Publish OpenAPI / Swagger schemas", "Maintain backward compatibility and deprecation notices", "Use feature flags for gradual rollouts"], ["Contract testing", "API design first"]]
];

const pybQuestions = pybTopics.map((t, idx) => ({
  id: `pyb-${String(idx + 1).padStart(3, '0')}`,
  role: "Python Backend Developer",
  category: t[1],
  difficulty: t[2],
  format: t[3],
  question: t[4],
  expectedSkills: t[5],
  evaluationPoints: t[6],
  followUpTopics: t[7]
}));
save('pythonBackend.ts', 'PYTHON_BACKEND_QUESTIONS', pybQuestions);
