const fs = require('fs');
const path = require('path');
const targetDir = 'C:/sih/src/data/interviewQuestions/banks';

function save(filename, exportName, questions) {
  const code = `import { RoleQuestion } from '../types';\n\nexport const ${exportName}: RoleQuestion[] = ${JSON.stringify(questions, null, 2)};\n`;
  fs.writeFileSync(path.join(targetDir, filename), code, 'utf-8');
  console.log(`✓ ${filename} written (${questions.length} questions)`);
}

const sqlTopics = [
  ["SQL Query Execution Order", "Core SQL", "Easy", "technical", "What is the logical processing order of clauses in a SQL SELECT query?", ["SQL Internals"], ["FROM / JOIN -> WHERE -> GROUP BY -> HAVING -> SELECT -> DISTINCT -> ORDER BY -> LIMIT / OFFSET", "Explains why aliases defined in SELECT cannot be used in WHERE", "Explains why HAVING evaluates after GROUP BY"], ["SELECT aliasing", "Evaluation phases"]],
  ["All Types of SQL Joins", "Joins", "Easy", "technical", "Explain INNER, LEFT, RIGHT, FULL OUTER, CROSS, and SELF joins with use cases.", ["SQL Joins"], ["INNER returns rows with matching keys in both tables", "LEFT returns all rows from left plus matches from right (NULL if none)", "FULL OUTER returns all rows from both tables, filling unmatched with NULL", "CROSS produces Cartesian product (N * M)", "SELF join joins table with itself (e.g. employee-manager hierarchy)"], ["Anti-joins", "Natural joins"]],
  ["Finding 2nd / Nth Highest Salary", "Advanced SQL", "Intermediate", "practical", "Write two different SQL queries to find the Nth highest salary in an Employee table.", ["SQL", "Problem Solving"], ["Method 1: DENSE_RANK() OVER (ORDER BY salary DESC) in CTE, filter WHERE rank = N", "Method 2: SELECT DISTINCT salary ORDER BY salary DESC LIMIT 1 OFFSET N-1", "Handling ties gracefully using DENSE_RANK vs OFFSET"], ["Handling ties", "Subquery approach"]],
  ["Window Functions: LEAD and LAG", "Window Functions", "Intermediate", "practical", "How do LEAD() and LAG() window functions work? Write a query to find month-over-month revenue growth.", ["SQL", "Window Functions"], ["LAG(metric, 1) accesses previous row's value within window partition", "LEAD accesses next row's value", "MoM calculation: (current_revenue - LAG(revenue, 1) OVER (ORDER BY month)) / LAG(revenue, 1) OVER (ORDER BY month) * 100"], ["PARTITION BY", "Handling first row NULLs"]],
  ["Cumulative Running Total in SQL", "Window Functions", "Intermediate", "practical", "Write a query to compute a cumulative running total of deposits per user ordered by transaction date.", ["SQL", "Window Functions"], ["SUM(amount) OVER (PARTITION BY user_id ORDER BY transaction_date ROWS UNBOUNDED PRECEDING)", "Contrast between ROWS UNBOUNDED PRECEDING and default RANGE window framing", "Handling same-day multiple transactions"], ["Window frames", "RANGE vs ROWS"]],
  ["Recursive CTE for Hierarchies", "CTEs", "Advanced", "practical", "Write a recursive CTE to traverse an employee hierarchy and display all reports under a manager.", ["Recursive CTEs", "Hierarchies"], ["Anchor member selects root manager", "UNION ALL links recursive member joining Employee table to CTE on manager_id", "Termination condition when no further subordinate rows match"], ["Recursion depth limit", "Organizational charts"]],
  ["COALESCE vs NULLIF vs NVL", "Functions", "Easy", "technical", "Explain the difference between COALESCE, NULLIF, and ISNULL/NVL in SQL.", ["SQL Functions"], ["COALESCE(val1, val2, ...) returns the first non-NULL expression in list (ANSI standard)", "NULLIF(expr1, expr2) returns NULL if expr1 equals expr2; otherwise returns expr1 (useful for preventing division by zero: amount / NULLIF(qty, 0))", "ISNULL (SQL Server) / NVL (Oracle) are proprietary two-argument alternatives to COALESCE"], ["Division by zero prevention", "Three-valued logic"]],
  ["Three-Valued Logic & NULLs", "Core SQL", "Intermediate", "technical", "Explain SQL three-valued logic (TRUE, FALSE, UNKNOWN). Why does 'WHERE col != 5' exclude NULL rows?", ["SQL Internals", "NULLs"], ["Any comparison with NULL (e.g. col = NULL or col != 5) evaluates to UNKNOWN", "WHERE clause only returns rows where condition evaluates strictly to TRUE", "Must use IS NULL or IS NOT NULL explicitly"], ["NULL in IN clauses", "NOT IN with NULL pitfall"]],
  ["Pitfall of NOT IN with NULLs", "Core SQL", "Intermediate", "technical", "Why does 'WHERE id NOT IN (SELECT foreign_id FROM table)' return 0 rows if any foreign_id is NULL?", ["SQL Pitfalls"], ["NOT IN evaluates to: id != 1 AND id != NULL ...", "Since id != NULL evaluates to UNKNOWN, the entire AND chain evaluates to UNKNOWN/FALSE", "Fix: Use NOT EXISTS or filter WHERE foreign_id IS NOT NULL in subquery"], ["NOT EXISTS vs NOT IN", "Anti-joins"]],
  ["GROUP BY with ROLLUP and CUBE", "Aggregation", "Intermediate", "technical", "What do ROLLUP and CUBE extensions to GROUP BY do in SQL reports?", ["Aggregation", "Reporting"], ["ROLLUP generates hierarchical subtotal aggregates from right to left plus grand total", "CUBE generates all possible subtotal combinations across all specified dimensions (2^N groupings)", "Used for dimensional cross-tab reporting without multiple UNION ALL queries"], ["GROUPING SETS", "GROUPING() function"]],
  ["EXISTS vs IN Performance", "Optimization", "Intermediate", "technical", "When is EXISTS faster than IN in SQL and how does query execution differ?", ["SQL Optimization"], ["EXISTS stops evaluating as soon as first matching row is found (short-circuit boolean)", "IN historically evaluated and materialized the entire subquery list before checking membership", "Modern query optimizers often rewrite IN as semi-joins, but EXISTS is safer with NULLs"], ["Correlated subqueries", "Semi-joins"]],
  ["Deleting Duplicate Rows in SQL", "Data Manipulation", "Intermediate", "practical", "Write a query to delete all duplicate rows in a table while keeping only the row with the lowest ID.", ["SQL", "Data Manipulation"], ["DELETE FROM table WHERE id NOT IN (SELECT MIN(id) FROM table GROUP BY email)", "Or using CTE with ROW_NUMBER(): WITH cte AS (SELECT id, ROW_NUMBER() OVER(PARTITION BY email ORDER BY id) as rn FROM table) DELETE FROM cte WHERE rn > 1", "Performance implications on large tables"], ["Deduplication", "CTEs"]],
  ["Conditional Aggregation with CASE", "Aggregation", "Easy", "practical", "How do you pivot row data into columns using conditional aggregation (SUM with CASE WHEN)?", ["SQL", "Pivoting"], ["SELECT year, SUM(CASE WHEN quarter=1 THEN sales ELSE 0 END) as Q1, SUM(CASE WHEN quarter=2 THEN sales ELSE 0 END) as Q2 ... GROUP BY year", "Clean ANSI standard method for cross-tabulation without proprietary PIVOT keywords", "Handles dynamic condition filtering"], ["PIVOT operator", "Cross-tabulation"]],
  ["Optimizing Slow Wildcard LIKE Queries", "Optimization", "Intermediate", "technical", "Why is 'WHERE name LIKE '%smith%' slow, and how do you optimize wildcard text search in SQL?", ["SQL Optimization", "Indexing"], ["Leading wildcard ('%smith%') prevents B-Tree index seek, forcing a full table scan", "Trailing wildcard ('smith%') can use standard B-Tree index seek", "To optimize leading/contains searches: use Full-Text Search (tsvector/GIN) or trigram indexes (pg_trgm in Postgres)"], ["Trigram indexes", "Full-text search"]],
  ["Handling Dates & Timezones in SQL", "Date Handling", "Easy", "technical", "How do you handle timestamps, timezones (UTC), and date truncation in SQL queries?", ["SQL Dates"], ["Always store timestamps in UTC (TIMESTAMP WITH TIME ZONE)", "Convert to user timezone at query time (AT TIME ZONE 'America/New_York')", "Use DATE_TRUNC('month', created_at) to bucket timestamps into daily/monthly periods for aggregation"], ["DATE_TRUNC", "EXTRACT function"]],
  ["String Manipulation Functions", "Functions", "Easy", "practical", "Explain common SQL string functions: SUBSTRING, CONCAT, TRIM, REPLACE, and COALESCE.", ["SQL Strings"], ["CONCAT / || operator joins strings together", "SUBSTRING / SUBSTR extracts portion based on offset and length", "TRIM removes leading/trailing whitespace", "REPLACE substitutes target substring with replacement"], ["REGEXP_REPLACE", "SPLIT_PART"]],
  ["Transaction Savepoints", "Transactions", "Intermediate", "technical", "What is a SAVEPOINT in SQL transactions and how does it allow partial rollbacks?", ["Transactions"], ["SAVEPOINT savepoint_name creates checkpoint within an active transaction", "ROLLBACK TO SAVEPOINT savepoint_name undoes changes made after the savepoint while keeping earlier work intact", "Allows error recovery within complex stored procedures without aborting entire transaction"], ["Nested transactions", "COMMIT"]],
  ["MERGE (UPSERT) Statement", "Data Manipulation", "Intermediate", "technical", "How does the SQL MERGE statement perform an atomic UPSERT (insert if not exists, update if exists)?", ["SQL MERGE", "UPSERT"], ["MERGE INTO target USING source ON match_condition", "WHEN MATCHED THEN UPDATE ... WHEN NOT MATCHED THEN INSERT ...", "PostgreSQL alternative: INSERT INTO table ... ON CONFLICT (id) DO UPDATE SET ..."], ["ON CONFLICT DO UPDATE", "Concurrency and race conditions"]],
  ["Window Framing: ROWS vs RANGE", "Window Functions", "Advanced", "technical", "What is the critical difference between ROWS and RANGE window frames in SQL?", ["Window Functions"], ["ROWS treats duplicates as individual distinct physical lines (e.g. ROWS BETWEEN 1 PRECEDING AND CURRENT ROW)", "RANGE groups duplicate peer values together based on ORDER BY expression value", "Default frame when ORDER BY is present is RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW, which can cause unexpected results with duplicate order keys"], ["UNBOUNDED PRECEDING", "Window framing"]],
  ["User-Defined Aggregate Functions", "Advanced SQL", "Advanced", "technical", "What is a User-Defined Aggregate (UDA) function in PostgreSQL and how is it defined?", ["PostgreSQL", "UDA"], ["Requires a state transition function (executes for each row updating state)", "State value type (state data structure)", "Optional final function (transforms state to return value)", "Example: custom geometric median or string accumulator"], ["CREATE AGGREGATE", "State transition function"]],
  ["Dynamic SQL in Stored Procedures", "Programmability", "Intermediate", "technical", "What is Dynamic SQL, how is it executed, and what security precautions must be taken?", ["Stored Procedures", "Security"], ["Constructing SQL query string dynamically at runtime and executing with EXEC / EXECUTE format()", "Used for dynamic column filtering and table partitioning", "Vulnerable to SQL injection if parameters are concatenated directly; must use format() with %I for identifiers and %L for literals or parameterized sp_executesql"], ["EXECUTE statement", "format() in PostgreSQL"]],
  ["Optimizing Sorting (ORDER BY)", "Optimization", "Intermediate", "technical", "How do indexes optimize ORDER BY queries, and what is the cost of sorting in memory vs disk (tempdb)?", ["SQL Optimization", "Sorting"], ["An index with matching sort order (INDEX on col_a ASC, col_b DESC) provides pre-sorted rows, eliminating sort step", "Without index, database must perform sort: in-memory (quicksort) or external merge sort on disk if work_mem / tempdb exceeds memory", "Disk-based external sort causes massive I/O slowdown"], ["work_mem tuning", "Sort spills"]],
  ["Finding Gaps and Islands in Sequences", "Advanced SQL", "Advanced", "practical", "Explain the classic 'Gaps and Islands' SQL problem and how to group contiguous dates using window functions.", ["SQL", "Window Functions"], ["Islands: contiguous sequences of values/dates; Gaps: missing values in sequence", "Solution: calculate difference between date and ROW_NUMBER() over date; the difference is constant for contiguous sequences (island group ID)", "GROUP BY island ID with MIN(date) and MAX(date) to identify island start and end"], ["Gaps and islands", "ROW_NUMBER trick"]],
  ["JSON Path Querying in Modern SQL", "Modern SQL", "Intermediate", "practical", "How do you query and filter nested JSON fields inside a SQL table in PostgreSQL or MySQL?", ["JSON", "Modern SQL"], ["PostgreSQL: data->'user'->>'email' extracts text value; jsonb_path_query() evaluates JSONPath expressions", "MySQL: JSON_EXTRACT(data, '$.user.email') or ->> operator", "Filtering: WHERE data @> '{\"status\": \"active\"}' utilizing GIN index"], ["JSON operators", "JSON_TABLE"]],
  ["Preventing Implicit Data Type Conversion", "Optimization", "Intermediate", "technical", "Why does implicit data type conversion in a WHERE clause cause performance bottlenecks?", ["Optimization", "Data Types"], ["Comparing VARCHAR column to integer parameter causes database to apply conversion function to every row in table (e.g. CAST(col AS INT))", "Applying function on indexed column invalidates B-Tree index usage, forcing a full table scan", "Always match parameter data types to column schema types"], ["SARGable queries", "Type casting"]],
  ["Temporary Tables vs Table Variables", "Programmability", "Intermediate", "technical", "Compare Temporary Tables (#temp) vs Table Variables / In-Memory tables in SQL.", ["Temporary Tables"], ["Temporary tables (#table) persist across transaction scope in session, support indexes, constraints, and cost-based statistics", "Table variables are scoped to batch/stored procedure and traditionally lack statistics, leading to bad execution plans on large datasets", "Use temporary tables for large datasets (>1000 rows); table variables for small lookup sets"], ["Global temp tables", "Session scope"]],
  ["Writing SARGable Queries", "Optimization", "Intermediate", "technical", "What does 'SARGable' (Search Argument Able) mean in SQL query writing? Give examples.", ["SQL Optimization"], ["A query is SARGable if the optimizer can use an index to seek data rather than scanning entire table", "Non-SARGable: WHERE YEAR(order_date) = 2024 (function on column disables index)", "SARGable refactor: WHERE order_date >= '2024-01-01' AND order_date < '2025-01-01'"], ["SARGable", "Index seek vs scan"]],
  ["Optimizing Pagination: Keyset Seek", "Optimization", "Intermediate", "practical", "Rewrite an inefficient deep pagination query 'SELECT * FROM logs ORDER BY id LIMIT 20 OFFSET 500000' using Keyset Seek.", ["Pagination", "Optimization"], ["Offset 500,000 scans and discards 500,000 index rows, causing high disk reads", "Keyset Seek refactor: WHERE id > last_seen_id ORDER BY id LIMIT 20", "Direct B-Tree index seek to target ID in sub-millisecond time regardless of page depth"], ["Keyset pagination", "Deep pagination"]],
  ["Cross-Table Integrity with CHECK Constraints", "Data Integrity", "Easy", "technical", "How do CHECK constraints enforce domain validation rules at the table level in SQL?", ["Constraints", "Data Integrity"], ["CHECK (price > 0 AND discount_price <= price)", "Enforced by database on every INSERT and UPDATE; rejects invalid data with constraint violation", "Ensures data validity regardless of which application or script writes to database"], ["Domain constraints", "Constraint violations"]],
  ["Simulating PIVOT and UNPIVOT", "Aggregation", "Intermediate", "practical", "How do you UNPIVOT columns (Q1, Q2, Q3, Q4) back into normalized row format in standard SQL?", ["Pivoting", "Normalization"], ["Using CROSS JOIN with VALUES: SELECT year, qtr, amount FROM sales CROSS JOIN LATERAL (VALUES ('Q1', q1), ('Q2', q2), ('Q3', q3), ('Q4', q4)) AS q(qtr, amount)", "Or using UNION ALL across each quarterly column", "Normalizes denormalized reporting tables into clean relational form"], ["CROSS JOIN LATERAL", "UNPIVOT"]],
  ["Identifying Long-Running Queries", "Performance Tuning", "Intermediate", "practical", "Write a query in PostgreSQL or SQL Server to find the top 5 longest running active queries.", ["Performance", "Diagnostics"], ["PostgreSQL: SELECT pid, now() - query_start AS duration, query, state FROM pg_stat_activity WHERE state != 'idle' ORDER BY duration DESC LIMIT 5", "Allows DBA to identify stuck locks, runaway batch jobs, or unindexed queries", "Can terminate offending query using pg_cancel_backend(pid) or pg_terminate_backend(pid)"], ["pg_stat_activity", "Query termination"]],
  ["Database Collation & Case Sensitivity", "Core SQL", "Easy", "technical", "What is SQL Collation and how does it affect string comparisons, sorting, and index usage?", ["Collation", "Strings"], ["Collation defines rules for sorting and comparing string characters (case-sensitive vs case-insensitive, accent-sensitive)", "Latin1_General_CI_AS treats 'apple' and 'Apple' as equal; Latin1_General_CS_AS treats them as distinct", "Changing collation in query on-the-fly disables standard index seeks"], ["Case sensitivity", "UTF-8 collation"]],
  ["Refactoring Legacy SQL Experience", "Project Experience", "Intermediate", "behavioral", "Describe an analytical or transactional SQL query you refactored that had dramatic performance improvements.", ["Project Experience", "Optimization"], ["Initial query bottleneck and baseline execution time (e.g. 45 seconds down to 200ms)", "Diagnostic analysis using execution plans (identifying missing index, full scan, or N+1 subquery)", "Refactoring technique applied and business impact"], ["EXPLAIN before and after", "Business impact"]],
  ["Maintaining Complex SQL Codebases", "Code Quality", "Easy", "behavioral", "How do you maintain readable, testable, and version-controlled SQL code across an engineering team?", ["Best Practices", "Collaboration"], ["Formatting standards (uppercase keywords, consistent indentation, descriptive table aliases)", "Version-controlling all DDL and stored procedures in Git repository with migration tools (Flyway/Liquibase)", "Writing modular CTEs with clear commenting on business logic assumptions"], ["SQL formatting", "Version control"]],
  ["Future of SQL (Distributed SQL & DuckDB)", "Modern Trends", "Intermediate", "technical", "Why has in-process analytical SQL (DuckDB) and Distributed SQL become prominent in modern data stacks?", ["DuckDB", "Modern SQL"], ["DuckDB provides columnar, vectorized SQL engine embedded directly in application memory without server setup (SQLite for analytics)", "Vectorized execution processes data in CPU SIMD batches, delivering 10-100x speedups on analytical OLAP queries", "Bridges gap between Python/Pandas dataframes and large-scale SQL queries"], ["Vectorized query execution", "Columnar vs row stores"]]
];

const sqlQuestions = sqlTopics.map((t, idx) => ({
  id: `sqldev-${String(idx + 1).padStart(3, '0')}`,
  role: "SQL Developer",
  category: t[1],
  difficulty: t[2],
  format: t[3],
  question: t[4],
  expectedSkills: t[5],
  evaluationPoints: t[6],
  followUpTopics: t[7]
}));
save('sqlDeveloper.ts', 'SQL_DEVELOPER_QUESTIONS', sqlQuestions);
