const fs = require('fs');
const path = require('path');
const targetDir = 'C:/sih/src/data/interviewQuestions/banks';

function save(filename, exportName, questions) {
  const code = `import { RoleQuestion } from '../types';\n\nexport const ${exportName}: RoleQuestion[] = ${JSON.stringify(questions, null, 2)};\n`;
  fs.writeFileSync(path.join(targetDir, filename), code, 'utf-8');
  console.log(`✓ ${filename} written (${questions.length} questions)`);
}

const cloudTopics = [
  ["Cloud Service Models", "Cloud Fundamentals", "Easy", "technical", "Compare IaaS, PaaS, and SaaS cloud service models with examples across AWS, Azure, and GCP.", ["Cloud Fundamentals"], ["IaaS: raw compute, storage, networking (EC2, Azure VM, GCE)", "PaaS: managed application platform, cloud provider manages OS/runtime (AWS Elastic Beanstalk, App Service, Cloud Run)", "SaaS: end-user software delivered over the web (Salesforce, Office 365)"], ["Shared responsibility model", "FaaS / Serverless"]],
  ["AWS Shared Responsibility Model", "Security", "Easy", "technical", "Explain the Shared Responsibility Model between the cloud provider and the customer.", ["Security", "AWS"], ["Provider is responsible for security OF the cloud (physical datacenters, hardware, host OS, virtualization)", "Customer is responsible for security IN the cloud (customer data, IAM, OS patching on EC2, network firewall rules)", "Varies by service model (IaaS vs PaaS vs SaaS)"], ["Compliance certifications", "Customer security responsibilities"]],
  ["VPC Architecture & Subnets", "Networking", "Intermediate", "technical", "How do you design a secure Virtual Private Cloud (VPC) with public and private subnets?", ["Networking", "AWS VPC"], ["Public subnet has route to Internet Gateway (IGW) for public load balancers/bastions", "Private subnet has route to NAT Gateway in public subnet for outbound internet access only", "Database and backend instances placed strictly in private subnets with no public IPs"], ["Route tables", "CIDR blocks"]],
  ["Security Groups vs NACLs", "Security", "Easy", "technical", "Compare Security Groups and Network Access Control Lists (NACLs) in cloud networking.", ["AWS", "Networking"], ["Security Groups operate at instance/ENI level and are stateful (inbound return traffic automatically allowed)", "NACLs operate at subnet level and are stateless (require explicit inbound and outbound rules)", "Security Groups support allow rules only; NACLs support allow and deny rules in numbered evaluation order"], ["Default rules", "Stateful vs stateless"]],
  ["IAM Roles vs Policies", "IAM", "Easy", "technical", "What is the difference between IAM Users, Groups, Roles, and Policies in AWS?", ["IAM", "Security"], ["IAM User has persistent credentials (password/access keys)", "IAM Role has no permanent credentials; assumed dynamically by users or AWS services (EC2, Lambda) via STS", "IAM Policy is a JSON document defining Allow/Deny permissions (Action, Resource, Condition)"], ["Least privilege", "IAM condition keys"]],
  ["Cloud Storage: S3 vs EBS vs EFS", "Storage", "Intermediate", "technical", "Compare object storage (S3), block storage (EBS), and file storage (EFS). When do you choose each?", ["Storage", "AWS"], ["S3: highly durable, infinitely scalable object storage accessed via HTTP API (static assets, backups, data lakes)", "EBS: low-latency block storage attached to a single EC2 instance as a virtual hard drive", "EFS: scalable NFS network file system shareable concurrently across hundreds of EC2 instances"], ["S3 storage classes", "IOPS provisioning"]],
  ["High Availability & Multi-AZ", "Architecture", "Intermediate", "technical", "How do you design a Multi-AZ, highly available web application on AWS?", ["High Availability", "Architecture"], ["Deploy Application Load Balancer across multiple Availability Zones", "Auto Scaling Group distributing EC2 instances across multiple AZs", "Multi-AZ database deployment (e.g. RDS Multi-AZ) with synchronous standby replica in secondary AZ"], ["RTO and RPO", "Failover mechanisms"]],
  ["Serverless with AWS Lambda", "Serverless", "Intermediate", "technical", "How does AWS Lambda work? What causes cold starts and how do you minimize them?", ["Serverless", "AWS Lambda"], ["Event-driven compute executing code in response to triggers (API Gateway, S3, SQS)", "Cold start occurs when new container execution environment is initialized", "Mitigate using Provisioned Concurrency, lightweight runtimes, and minimizing deployment package size"], ["Lambda SnapStart", "Execution timeout"]],
  ["Cloud Database: RDS vs DynamoDB", "Database", "Intermediate", "technical", "Compare Amazon RDS (relational) vs Amazon DynamoDB (NoSQL). How do you choose?", ["Database", "AWS"], ["RDS is managed relational database (PostgreSQL, MySQL) supporting complex SQL joins and ACID transactions", "DynamoDB is fully managed serverless key-value/document store with single-digit millisecond latency at any scale", "Use RDS for relational data; DynamoDB for high-throughput partitioned key-value access patterns"], ["DynamoDB partition keys", "Aurora Serverless"]],
  ["Auto Scaling & Target Tracking", "Compute", "Intermediate", "technical", "How does an Auto Scaling Group scale compute capacity using Target Tracking scaling policies?", ["Auto Scaling", "Compute"], ["Monitors CloudWatch metric (e.g. average CPU utilization at 70% or ALB request count per target)", "Dynamically adds or terminates instances to keep metric at target value", "Includes cooldown periods to prevent rapid oscillation (thrashing)"], ["Launch Templates", "Step scaling"]],
  ["AWS KMS & Encryption at Rest", "Security", "Intermediate", "technical", "How does AWS Key Management Service (KMS) provide envelope encryption for S3 and EBS?", ["Security", "KMS"], ["Customer Master Key (CMK) generates a plaintext Data Encryption Key (DEK) and encrypted DEK", "Data is encrypted locally using the plaintext DEK, which is then wiped from memory", "Only the encrypted DEK is stored alongside the ciphertext data"], ["KMS key rotation", "Customer Managed vs AWS Managed keys"]],
  ["CloudWatch Monitoring & Alarms", "Monitoring", "Easy", "technical", "How do you set up CloudWatch metrics, alarms, and SNS notifications for production operations?", ["Monitoring", "CloudWatch"], ["CloudWatch collects default and custom metrics from EC2, RDS, and Lambda", "Alarms trigger state transitions (OK, ALARM, INSUFFICIENT_DATA) based on metric thresholds over evaluation periods", "Actions publish to Amazon SNS topics routing alerts to Slack, email, or PagerDuty"], ["CloudWatch Logs Insights", "Anomaly detection"]],
  ["Content Delivery with CloudFront (CDN)", "Networking", "Easy", "technical", "How does Amazon CloudFront accelerate global content delivery and what is origin shielding?", ["CDN", "CloudFront"], ["Caches static and dynamic content at edge locations worldwide closest to users", "Reduces origin server load and minimizes TTFB (Time to First Byte)", "Origin Shield adds an extra caching layer between edge locations and origin to protect backend servers"], ["Cache-Control headers", "Signed URLs for restricted content"]],
  ["Cloud Cost Optimization", "FinOps", "Intermediate", "technical", "What strategies do you use to reduce AWS cloud infrastructure spend by 30%?", ["FinOps", "Cost Optimization"], ["Purchase Compute Savings Plans or Reserved Instances for steady-state workloads", "Use Spot instances for non-critical, fault-tolerant batch workloads", "Identify and terminate orphaned EBS volumes, unattached Elastic IPs, and idle RDS instances", "Apply S3 Lifecycle policies moving old data to Glacier"], ["AWS Cost Explorer", "AWS Compute Optimizer"]],
  ["Infrastructure as Code with AWS CDK", "IaC", "Intermediate", "technical", "Compare AWS CloudFormation vs AWS Cloud Development Kit (CDK).", ["IaC", "AWS CDK"], ["CloudFormation uses declarative JSON/YAML templates defining AWS resources", "CDK allows developers to define cloud infrastructure using familiar programming languages (TypeScript, Python, Java)", "CDK synthesizes code into standard CloudFormation templates for deployment"], ["Constructs (L1, L2, L3)", "CDK pipelines"]],
  ["Disaster Recovery Strategies", "Disaster Recovery", "Advanced", "technical", "Compare Backup & Restore, Pilot Light, Warm Standby, and Multi-Region Active-Active DR strategies.", ["Disaster Recovery", "Architecture"], ["Backup & Restore: cheapest, highest RTO/RPO (rebuilding from backups)", "Pilot Light: core data replicated, minimal compute running, scaled up on disaster", "Warm Standby: scaled-down fully functional copy running 24/7 in secondary region", "Active-Active: traffic served across both regions simultaneously, near-zero RTO/RPO but highest cost"], ["Route 53 latency routing", "RTO vs RPO"]],
  ["Container Orchestration: ECS vs EKS", "Containers", "Intermediate", "technical", "Compare Amazon ECS (Fargate) vs Amazon EKS (Kubernetes). When do you recommend ECS?", ["Containers", "AWS"], ["ECS is AWS-native, deeply integrated, simpler to operate with lower operational overhead", "EKS is standard managed Kubernetes with full open-source ecosystem portability across multi-cloud", "Choose ECS for smaller teams wanting simplicity; choose EKS for complex Kubernetes microservice requirements"], ["AWS Fargate", "Task definitions vs Pods"]],
  ["AWS WAF (Web Application Firewall)", "Security", "Easy", "technical", "How does AWS WAF protect web applications against OWASP Top 10 exploits and DDoS attacks?", ["Security", "AWS WAF"], ["Deployed on CloudFront, ALB, or API Gateway", "Inspects HTTP headers, body, query strings for SQL injection (SQLi) and XSS patterns", "Rate-based rules block IP addresses exceeding request thresholds, mitigating HTTP flood DDoS"], ["AWS Shield Advanced", "Managed Rule Groups"]],
  ["Transit Gateway in Enterprise Networking", "Networking", "Advanced", "technical", "What problem does AWS Transit Gateway solve compared to complex VPC Peering meshes?", ["Networking", "Enterprise Cloud"], ["VPC peering requires full mesh n*(n-1)/2 direct peering connections (hard to manage)", "Transit Gateway acts as a central cloud router connecting hundreds of VPCs and on-premises VPNs/Direct Connect", "Simplifies network routing, hub-and-spoke architecture, and traffic inspection"], ["Direct Connect", "Hub and spoke network"]],
  ["Zero Trust Cloud Architecture", "Security", "Advanced", "technical", "What is Zero Trust in cloud security and how do you implement it across services?", ["Security", "Zero Trust"], ["'Never trust, always verify' principle; assuming network perimeter is already breached", "Enforce mutual TLS (mTLS) for all service-to-service communication", "Strict identity verification, short-lived tokens, and least privilege access policies on every request"], ["Service mesh mTLS", "IAM identity center"]],
  ["Database Read Replicas vs Sharding", "Database", "Intermediate", "technical", "How do RDS Read Replicas scale read-heavy applications and how is replication lag managed?", ["Database", "Scalability"], ["Asynchronously replicates database updates from primary writer instance to read-only replicas", "Application routes SELECT queries to replica endpoints, relieving pressure on primary writer", "Replication lag means replicas may return slightly stale data; critical read-after-write operations should query writer"], ["Aurora Global Database", "Aurora read endpoints"]],
  ["AWS Organizations & Multi-Account Strategy", "Governance", "Intermediate", "technical", "Why should an enterprise use AWS Organizations with multiple separate AWS accounts?", ["Governance", "Cloud Architecture"], ["Isolates blast radius: security breach in Dev cannot compromise Production account", "Clear billing separation and allocation across departments", "Service Control Policies (SCPs) apply guardrails restricting actions across member accounts"], ["Service Control Policies (SCPs)", "AWS Control Tower"]],
  ["Event-Driven Architecture with EventBridge", "Event-Driven", "Intermediate", "technical", "How does Amazon EventBridge route events between AWS services, SaaS apps, and microservices?", ["EventBridge", "Architecture"], ["Serverless event bus that ingests events from multiple sources", "Rules filter incoming JSON event payloads and route to targets (Lambda, SQS, Step Functions)", "Decouples producers from consumers with high throughput and schema registry"], ["Event bus", "Schema registry"]],
  ["AWS Step Functions vs Lambda Orchestration", "Serverless", "Intermediate", "technical", "Why should you use AWS Step Functions instead of chaining Lambda functions directly?", ["Serverless", "Workflow"], ["Step Functions provides visual state machine orchestrating multi-step workflows", "Built-in error handling, retries with exponential backoff, and timeouts", "Saves execution state across steps, avoiding costly Lambda-invoking-Lambda idle wait charges"], ["State machines", "Saga pattern with Step Functions"]],
  ["Cloud Migration Strategies (The 7 Rs)", "Migration", "Intermediate", "technical", "Explain the 7 Rs of cloud migration (Rehost, Replatform, Refactor, Repurchase, Retain, Retire, Relocate).", ["Cloud Migration"], ["Rehost: Lift-and-shift to VMs without code changes", "Replatform: Lift-and-reshape, moving to managed database (RDS) or container service without modifying core app code", "Refactor: Redesigning application into cloud-native microservices and serverless", "Retire: Decommissioning redundant legacy systems"], ["AWS Application Migration Service", "Total Cost of Ownership (TCO)"]],
  ["Storage Gateway: Hybrid Cloud Storage", "Hybrid Cloud", "Intermediate", "technical", "How does AWS Storage Gateway connect on-premises environments to cloud storage?", ["Hybrid Cloud", "Storage"], ["File Gateway: presents S3 buckets as local NFS/SMB network shares with local caching", "Volume Gateway: provides iSCSI block storage backed by S3 with EBS snapshots", "Tape Gateway: replaces on-premises physical tape backups with Glacier"], ["Direct Connect", "AWS Outposts"]],
  ["Kubernetes on Cloud (EKS) Node Groups", "Containers", "Intermediate", "technical", "Compare EKS Managed Node Groups vs Karpenter for dynamic Kubernetes node provisioning.", ["EKS", "Kubernetes"], ["Managed Node Groups automate node provisioning, updating, and autoscaling using EC2 Auto Scaling Groups", "Karpenter is open-source cluster autoscaler that bypasses node groups, directly launching optimal EC2 instances in seconds based on pending pod requirements", "Karpenter significantly improves bin-packing and lowers compute costs with Spot"], ["Karpenter", "EKS Fargate"]],
  ["AWS CloudTrail vs CloudWatch Logs", "Compliance", "Easy", "technical", "What is the operational difference between AWS CloudTrail and CloudWatch Logs?", ["Compliance", "Auditing"], ["CloudTrail audits governance and API activity: records WHO made WHAT API call WHEN and from WHERE", "CloudWatch Logs aggregates and monitors application and server runtime logs (syslog, web server logs)", "CloudTrail for security audits; CloudWatch for operational health and debugging"], ["CloudTrail Insights", "Log tampering prevention"]],
  ["Handling Production IAM Privilege Escalation", "Security", "Intermediate", "scenario", "An attacker gains access to an IAM role. How do you audit permissions and remediate immediately?", ["Security", "Incident Response"], ["Revoke active STS sessions for the compromised role in the IAM console", "Inspect CloudTrail event history to identify all actions taken by the role's temporary credentials", "Apply restrictive inline deny policy or delete role, and rotate all exposed secrets"], ["IAM Access Analyzer", "Credential exposure"]],
  ["Cross-Region Replication & Latency Routing", "Networking", "Intermediate", "technical", "How do Route 53 Latency-Based Routing and S3 Cross-Region Replication improve global user experience?", ["Route 53", "Global Architecture"], ["Route 53 routes DNS queries to the AWS region that provides the lowest network latency for the end user", "S3 Cross-Region Replication automatically synchronizes object buckets to destination regions asynchronously for low-latency reads and disaster recovery"], ["Geolocation routing", "Failover routing"]],
  ["API Gateway Throttling & Caching", "API Gateway", "Easy", "technical", "How do you protect backend microservices from traffic surges using Amazon API Gateway?", ["API Gateway", "Performance"], ["Configure usage plans with rate limits (requests per second) and burst limits to prevent backend exhaustion", "Enable API Gateway response caching to serve frequent identical GET requests without hitting backend compute", "Return HTTP 429 when client exceeds throttle limits"], ["API keys", "Mutual TLS"]],
  ["Cloud Incident Management Experience", "Incident Response", "Intermediate", "behavioral", "Describe a production cloud outage or degradation you resolved. What was your systematic approach?", ["Troubleshooting", "Communication"], ["Incident triage and assessing customer blast radius", "Leveraging CloudWatch dashboards, traces, and metrics to identify bottleneck", "Executing immediate mitigation followed by root-cause fix and blameless post-mortem"], ["Post-mortem", "On-call response"]],
  ["Architecting a Large-Scale Cloud System", "Project Experience", "Intermediate", "behavioral", "Walk me through an enterprise cloud architecture you designed. What were the key non-functional requirements?", ["Architecture", "System Design"], ["System availability, scalability, and disaster recovery SLA targets", "Network topology, compute selection, and storage tiering", "Security posture, compliance requirements, and cost optimization results"], ["Non-functional requirements", "Design trade-offs"]],
  ["Managing Cloud Vendor Lock-In", "Strategy", "Intermediate", "behavioral", "How do you evaluate and balance the benefits of proprietary cloud managed services against vendor lock-in?", ["Architecture", "Strategy"], ["Managed services provide faster time-to-market, lower operational burden, and automatic scaling", "Mitigate risk by adopting open standards (containers, Kubernetes, OpenTelemetry, PostgreSQL)", "Accept strategic lock-in where productivity gains vastly outweigh migration costs"], ["Multi-cloud reality", "Open-source standards"]],
  ["Future of Cloud Architecture (Edge & Serverless)", "Modern Trends", "Easy", "technical", "What is Edge Computing (e.g. CloudFront Functions, Lambda@Edge) and when is it necessary?", ["Edge Computing", "Serverless"], ["Executes compute logic at edge locations globally, within single-digit milliseconds of users", "Ideal for URL rewrites, A/B routing, header manipulation, bot detection, and authentication checks before traffic hits origin", "Eliminates origin round-trips for simple requests"], ["CloudFront Functions", "Distributed edge data"]]
];

const cloudQuestions = cloudTopics.map((t, idx) => ({
  id: `ce-${String(idx + 1).padStart(3, '0')}`,
  role: "Cloud Engineer",
  category: t[1],
  difficulty: t[2],
  format: t[3],
  question: t[4],
  expectedSkills: t[5],
  evaluationPoints: t[6],
  followUpTopics: t[7]
}));
save('cloudEngineer.ts', 'CLOUD_ENGINEER_QUESTIONS', cloudQuestions);
