const fs = require('fs');
const path = require('path');
const targetDir = 'C:/sih/src/data/interviewQuestions/banks';

function save(filename, exportName, questions) {
  const code = `import { RoleQuestion } from '../types';\n\nexport const ${exportName}: RoleQuestion[] = ${JSON.stringify(questions, null, 2)};\n`;
  fs.writeFileSync(path.join(targetDir, filename), code, 'utf-8');
  console.log(`✓ ${filename} written (${questions.length} questions)`);
}

// 1. QA ENGINEER (35 questions)
const qaTopics = [
  ["STLC vs SDLC", "Testing Fundamentals", "Easy", "technical", "Explain the stages of Software Testing Life Cycle (STLC) and how it integrates with SDLC.", ["STLC", "SDLC"], ["Requirement Analysis -> Test Planning -> Test Case Development -> Environment Setup -> Test Execution -> Test Closure", "Entry and exit criteria for each phase", "Traceability matrix linking test cases back to business requirements"], ["RTM (Requirements Traceability Matrix)", "Agile QA"]],
  ["Bug Lifecycle & States", "Defect Management", "Easy", "technical", "Describe the complete Bug Life Cycle from New to Closed and deferred states.", ["Defect Management"], ["New -> Assigned -> Open -> Fixed -> Retest -> Verified -> Closed", "Alternative paths: Rejected, Duplicate, Deferred, Cannot Reproduce", "Key fields in a professional bug report: Steps to Reproduce, Expected vs Actual, Severity, Priority, Environment, Screenshots/Logs"], ["Bug Severity vs Priority", "Jira bug workflows"]],
  ["Severity vs Priority", "Defect Management", "Easy", "technical", "Explain the difference between Severity and Priority with examples of High Severity/Low Priority and Low Severity/High Priority.", ["Defect Management"], ["Severity is technical impact on the system; Priority is urgency of fix from business perspective", "High Severity / Low Priority: App crashes on legacy OS version used by 0.01% of users", "Low Severity / High Priority: Company logo is misspelled on public login page"], ["Triage meetings", "SLA for bug fixes"]],
  ["Equivalence Partitioning & BVA", "Test Design", "Intermediate", "technical", "Explain Equivalence Partitioning and Boundary Value Analysis (BVA) for testing an input field accepting ages 18 to 60.", ["Test Design Techniques"], ["Equivalence classes: Invalid (<18), Valid (18-60), Invalid (>60)", "BVA checks edge boundaries: 17, 18, 19 and 59, 60, 61", "Most bugs occur at the boundary conditions"], ["Robustness testing", "Decision table testing"]],
  ["Smoke vs Sanity Testing", "Testing Types", "Easy", "technical", "What is the difference between Smoke Testing and Sanity Testing?", ["Testing Types"], ["Smoke testing (build verification) tests basic critical functionality on a new build to decide if it is testable", "Sanity testing tests specific bugs fixed and related modules after a minor build release", "Smoke is wide and shallow; Sanity is narrow and deep"], ["Regression testing", "Automated smoke tests"]],
  ["Regression Testing Strategy", "Testing Types", "Intermediate", "technical", "How do you select test cases for a regression suite when time is limited before a release?", ["Regression Testing"], ["Prioritize critical business flows (login, payments, checkout)", "Include tests for recently modified code and adjacent dependent modules", "Include high-risk areas with historical defect density"], ["Risk-based testing", "Automated regression"]],
  ["API Testing Fundamentals with Postman", "API Testing", "Intermediate", "practical", "How do you test a REST API using Postman? What assertions and status codes do you verify?", ["API Testing", "Postman"], ["Verify status codes (200, 201, 400, 401, 404, 500)", "Assert response payload schema and values using pm.test and pm.expect()", "Test response latency, boundary inputs, authentication headers, and error response formats"], ["Postman collections", "Newman CLI runner"]],
  ["Testing in Agile / Scrum", "Agile Testing", "Easy", "technical", "What is the role of a QA Engineer in Agile Scrum ceremonies (Sprint Planning, Daily Standup, Retro)?", ["Agile", "Scrum"], ["Sprint Planning: review user stories for testability, acceptance criteria, and story point sizing", "Daily Standup: report testing progress, blockers, and defect discoveries", "Retrospective: discuss process improvements and quality bottlenecks"], ["Definition of Done (DoD)", "Three Amigos meeting"]],
  ["Exploratory Testing vs Scripted Testing", "Testing Types", "Easy", "technical", "What is Exploratory Testing? When is it superior to formal scripted test cases?", ["Exploratory Testing"], ["Simultaneous learning, test design, and test execution without pre-written test scripts", "Relies on tester's domain knowledge, intuition, and creativity to find unexpected edge cases", "Complements automated regression tests by uncovering subtle usability and workflow issues"], ["Session-based testing", "Chartered testing"]],
  ["SQL for QA Verification", "Database Testing", "Intermediate", "practical", "How do you use SQL queries to verify backend data integrity after submitting a web form?", ["SQL", "Database Testing"], ["Query database table to verify record was inserted with correct field mappings and timestamps", "Verify foreign key relationships across related tables", "Check default values, constraints, and audit log entries"], ["Data integrity checks", "Backend verification"]],
  ["Non-Functional Testing Types", "Testing Types", "Easy", "technical", "What are the major types of Non-Functional Testing (Performance, Security, Usability, Accessibility)?", ["Non-Functional Testing"], ["Performance testing: verify speed, scalability, and stability under load", "Security testing: identify vulnerabilities and unauthorized access risks", "Usability testing: evaluate user interface intuitiveness and navigation ease", "Accessibility testing: verify compliance with WCAG standards for disabled users"], ["Load testing", "WCAG standards"]],
  ["Testing Microservices Architecture", "Architecture", "Intermediate", "technical", "What are the challenges of testing microservices and how does Contract Testing (Pact) solve them?", ["Microservices", "Contract Testing"], ["Dependencies between services make end-to-end testing slow, brittle, and hard to isolate", "Contract testing verifies that consumer and provider agree on API request/response format independently", "Pact creates contract files validated in CI without spinning up full service mesh"], ["Pact framework", "Consumer-driven contracts"]],
  ["Performance Testing with JMeter", "Performance Testing", "Intermediate", "technical", "How do you design a load test in Apache JMeter? Explain Thread Groups, Ramp-Up, and Listeners.", ["JMeter", "Performance"], ["Thread Group simulates number of concurrent virtual users", "Ramp-up period defines time to bring all virtual users online gradually", "HTTP Request Sampler defines API calls; Listeners collect and graph metrics (Response Time, Throughput, Error Rate)"], ["Stress testing vs Load testing", "Throughput metrics"]],
  ["Cross-Browser & Cross-Platform Testing", "Web Testing", "Easy", "technical", "How do you approach cross-browser testing across Chrome, Safari, Firefox, and mobile browsers?", ["Cross-Browser", "Compatibility"], ["Identify target browsers and versions from Google Analytics user demographics", "Focus manual testing on known engine differences (WebKit/Safari vs Chromium vs Gecko)", "Leverage cloud grid tools (BrowserStack, SauceLabs) for automated matrix execution"], ["Browser engines", "Device emulators vs real devices"]],
  ["Security Testing: OWASP Top 10 for QA", "Security Testing", "Intermediate", "technical", "How do QA engineers test web applications for common vulnerabilities like SQLi and XSS?", ["Security Testing", "OWASP"], ["Test input fields with SQL injection payloads (' OR '1'='1) to check for unhandled SQL errors", "Test inputs with script tags (<script>alert('XSS')</script>) to check for lack of sanitization", "Verify authentication, session timeout, and secure HTTPS cookie flags"], ["OWASP ZAP", "Penetration testing basics"]],
  ["Root Cause Analysis (5 Whys)", "Quality Assurance", "Easy", "behavioral", "Explain the 5 Whys methodology for conducting root cause analysis on a critical escaped defect.", ["Root Cause Analysis", "Process Improvement"], ["Iteratively ask 'Why' 5 times to peel away superficial symptoms and identify systemic failure", "Focus on process, tooling, and communication gaps rather than placing individual blame", "Implement systemic guardrails (automated test in CI, linter rule) to prevent recurrence"], ["Defect leakage", "Preventative actions"]],
  ["Mobile App Testing Specifics", "Mobile Testing", "Intermediate", "technical", "What mobile-specific test scenarios must you cover for iOS and Android apps?", ["Mobile Testing"], ["Device interruptions (phone calls, SMS, push notifications, low battery alerts)", "Network switching (Wi-Fi to 4G/5G, flight mode, offline behavior)", "Screen rotation, backgrounding, app memory kill by OS, and app update data migration"], ["Appium basics", "OS version fragmentation"]],
  ["Accessibility Testing (WCAG)", "Accessibility", "Easy", "technical", "How do you test a web application for accessibility compliance (WCAG 2.1 AA)?", ["Accessibility Testing"], ["Verify all interactive elements are reachable and operable via keyboard only (Tab, Enter, Space, Esc)", "Audit color contrast ratios for text readability (minimum 4.5:1 ratio)", "Use screen readers (NVDA, VoiceOver) and automated tools (axe, Lighthouse) to verify ARIA labels and alt text"], ["Axe DevTools", "Keyboard navigation"]],
  ["Writing Good Test Cases", "Test Documentation", "Easy", "practical", "What makes a test case effective, reusable, and easy to maintain?", ["Test Documentation"], ["Clear, concise title and unique ID", "Explicit pre-conditions and test environment requirements", "Step-by-step reproduction instructions with concrete test data", "Precise expected result against which actual outcome is objectively validated"], ["Test case management tools", "Test reusability"]],
  ["Handling Flaky Tests", "Test Quality", "Intermediate", "technical", "What causes test flakiness in testing suites and how do you eliminate it?", ["Quality Assurance", "Flaky Tests"], ["Asynchronous timing issues, race conditions, and hardcoded sleep statements", "Shared mutable test data and non-isolated test environments", "Eliminate by using explicit dynamic waits, isolating test data, and running tests in containers"], ["Explicit waits", "Test isolation"]],
  ["Defect Triage Meetings", "Process", "Easy", "technical", "What is a Defect Triage meeting, who attends, and what decisions are made?", ["Defect Management"], ["Regular meeting between QA, Product Manager, and Tech Lead to review newly filed bugs", "Validate bug validity, assign accurate Severity and Priority ratings", "Decide whether bug is fixed in current sprint, deferred to future sprint, or closed as won't fix"], ["Sprint planning", "Backlog grooming"]],
  ["Test Data Management", "Data Management", "Intermediate", "technical", "How do you manage test data for automated and manual testing without polluting production?", ["Test Data Management"], ["Use synthetic test data generators (Faker libraries) and dedicated staging databases", "Implement automated database seed and cleanup scripts per test suite execution", "Mask or anonymize production data copies to comply with privacy regulations (GDPR, HIPAA)"], ["Data masking", "Synthetic data"]],
  ["Continuous Integration in QA", "CI/CD", "Easy", "technical", "How does automated testing fit into a CI/CD pipeline (e.g. GitHub Actions, Jenkins)?", ["CI/CD", "Automation"], ["Trigger smoke test suite on every pull request to validate commit before merge", "Trigger full regression test suite on nightly builds or merge to main", "Block deployment if automated test gates fail, alerting team with detailed reports"], ["Test reporting", "Quality gates"]],
  ["Shift-Left Testing", "Modern QA", "Easy", "technical", "What is 'Shift-Left' testing and how does it reduce software development costs?", ["Modern QA", "Shift-Left"], ["Involving QA early in requirements analysis and design phases before code is written", "Catching ambiguities, logic flaws, and architectural gaps early when they are 10x cheaper to fix", "Developers write unit tests; QA collaborates on acceptance criteria (BDD)"], ["BDD (Behavior Driven Development)", "Cost of quality"]],
  ["Behavior Driven Development (BDD)", "BDD", "Intermediate", "technical", "Explain Behavior-Driven Development (BDD) and write a Gherkin scenario (Given-When-Then) for user login.", ["BDD", "Gherkin"], ["Collaboration approach using natural language accessible to non-technical business stakeholders", "Feature: User Login; Scenario: Successful login with valid credentials", "Given user is on login page; When user enters valid credentials; Then user is redirected to dashboard"], ["Cucumber framework", "Step definitions"]],
  ["Testing Payment Gateways", "Scenario Analysis", "Intermediate", "scenario", "How do you design a comprehensive test suite for an e-commerce credit card checkout flow?", ["Test Design", "Scenario Analysis"], ["Positive tests: valid cards with sufficient funds, correct 3D Secure OTP verification", "Negative tests: expired card, invalid CVV, incorrect billing address, card with insufficient funds", "Edge cases: network timeout during payment processing, duplicate submit clicks, currency conversions, webhook confirmation handling"], ["Idempotency in payments", "Test card numbers"]],
  ["Localization & Internationalization Testing", "Testing Types", "Easy", "technical", "What is the difference between Internationalization (i18n) and Localization (l10n) testing?", ["i18n", "l10n"], ["Internationalization verifies software architecture supports multiple languages without code changes", "Localization verifies translation accuracy, currency formats, date formats (MM/DD vs DD/MM), and cultural appropriateness for specific locales", "Test for text truncation/wrapping in languages with longer words (e.g. German) and RTL layout (Arabic/Hebrew)"], ["RTL layouts", "Pseudo-localization"]],
  ["Testing Webhook Integrations", "API Testing", "Intermediate", "technical", "How do you test that your application correctly receives and processes asynchronous third-party webhooks?", ["Webhooks", "API Testing"], ["Simulate webhook delivery using tools like ngrok or mock webhook dispatchers", "Verify signature verification (HMAC secret header) to prevent spoofing", "Test duplicate webhook delivery to verify idempotency (not creating duplicate transactions)"], ["ngrok", "HMAC verification"]],
  ["Defect Leakage & Escaped Defects", "Metrics", "Intermediate", "technical", "What is Defect Leakage (Defect Escape Rate) and how do you analyze it?", ["QA Metrics"], ["Percentage of defects discovered by end users in production vs total defects discovered", "Defect Leakage = (Production Defects / Total Defects) * 100", "Low leakage indicates high QA effectiveness; high leakage triggers root-cause review of testing coverage"], ["Defect density", "QA metrics"]],
  ["Testing Micro-Frontends", "Web Testing", "Intermediate", "technical", "What are the testing challenges when multiple independent teams build micro-frontends on a single page?", ["Micro-Frontends", "Web Testing"], ["Shared state and event communication collisions between independent micro-apps", "CSS styling collisions and conflicting third-party library versions", "Testing isolated micro-apps with unit/component tests and verifying composite shell integration"], ["Module Federation", "Contract testing in UI"]],
  ["Testing WebSocket Real-Time Features", "Real-Time Testing", "Intermediate", "technical", "How do you test real-time chat or live notification features powered by WebSockets?", ["WebSockets", "Testing"], ["Verify connection establishment, message delivery, and latency under multiple concurrent clients", "Test connection drop, network interruption, and automatic reconnection logic", "Verify message ordering and offline message synchronization upon reconnecting"], ["Postman WebSockets", "Load testing WebSockets"]],
  ["Handling Disagreements with Developers", "Behavioral", "Easy", "behavioral", "How do you handle a situation where a developer marks your bug report as 'Not a Bug' or 'Works on My Machine'?", ["Communication", "Collaboration"], ["Do not get defensive; communicate directly with developer", "Demonstrate reproduction steps on a clean environment with video recording or logs", "Refer to agreed product specification / acceptance criteria, and involve Product Manager if requirement is ambiguous"], ["Conflict resolution", "Reproducing bugs"]],
  ["High-Pressure Release Experience", "Project Experience", "Intermediate", "behavioral", "Describe a challenging release deadline where QA was squeezed. How did you ensure product quality without burning out?", ["Project Experience", "Time Management"], ["Perform risk-based testing: focus strictly on P0 critical paths and high-risk changes", "Leverage automated regression tests to cover stable modules rapidly", "Communicate residual quality risks transparently to release stakeholders for sign-off"], ["Risk-based testing", "Stakeholder communication"]],
  ["Building a QA Process from Scratch", "Strategy", "Intermediate", "behavioral", "If you join a startup with zero formal QA processes, what are the first three improvements you implement?", ["Process Improvement", "Strategy"], ["Define standard bug reporting template and bug lifecycle in issue tracker", "Establish clear Definition of Done (DoD) including acceptance criteria and smoke tests", "Set up automated smoke tests in CI/CD to prevent broken builds from reaching staging"], ["Quality culture", "CI integration"]],
  ["AI in Software Testing", "Modern Trends", "Easy", "technical", "How is Generative AI transforming software testing (test case generation, synthetic data, visual testing)?", ["Modern QA", "AI in Testing"], ["Auto-generating test cases and edge cases from user story descriptions", "Generating realistic synthetic test datasets with complex constraints", "Visual regression testing with AI comparing UI layouts and catching visual anomalies across screen sizes"], ["Applitools Eyes", "AI test automation"]]
];

const qaQuestions = qaTopics.map((t, idx) => ({
  id: `qa-${String(idx + 1).padStart(3, '0')}`,
  role: "QA Engineer",
  category: t[1],
  difficulty: t[2],
  format: t[3],
  question: t[4],
  expectedSkills: t[5],
  evaluationPoints: t[6],
  followUpTopics: t[7]
}));
save('qaEngineer.ts', 'QA_ENGINEER_QUESTIONS', qaQuestions);
